/* Svenska årskurs 7: two pilot units. The second story reuses the first one's words (nervös, märka, lättad, klasskamrat, försiktigt). */
{const {rx,boxes,pic,kid,W,sent,cap}=SVH;

/* ---------------- unit 1: Första dagen (ordföljd: verbet på plats 2) ---------------- */
W("nervos",{sv:"nervös",m:rx("nervös(a|t)?"),d:t3("Orolig och spänd inför något.","Worried and tense about something.","قلق ومتوتر من شيء."),ex:"Hon var nervös inför provet.",tr:{en:"nervous",ar:"متوتّر"},syn:["orolig","spänd"],opp:["lugn"],wrong:["hungrig","glad"],gap:["Inför provet var hon","nervös","."],gapForm:"nervös",form:"nervös – nervöst – nervösa"});
W("korridor",{sv:"korridor (en)",m:rx("korridor(en|er|erna)?"),d:t3("En lång gång inne i en byggnad.","A long passage inside a building.","ممر طويل داخل مبنى."),ex:"Skåpen står i korridoren.",tr:{en:"corridor",ar:"ممرّ"},syn:["gång"],wrong:["trappa","gård"],gap:["Eleverna väntade i","korridoren","före lektionen."],gapForm:"korridoren",form:"en korridor – korridorer"});
W("schema",{sv:"schema (ett)",m:rx("schema(t|n|na)?"),d:t3("En lista över lektioner och tider.","A list of lessons and times.","قائمة بالحصص وأوقاتها."),ex:"Enligt schemat har vi idrott.",tr:{en:"timetable",ar:"جدول الحصص"},syn:["tidtabell"],wrong:["läxa","betyg"],gap:["Titta på ditt","schema","så ser du vilken sal det är."],gapForm:"schema",form:"ett schema – scheman"});
W("klasskamrat",{sv:"klasskamrat (en)",m:rx("klasskamrat(en|er|erna)?"),d:t3("En som går i samma klass som du.","Someone in the same class as you.","شخص في صفّك نفسه."),ex:"Sara är min klasskamrat.",tr:{en:"classmate",ar:"زميل الصف"},syn:["klasskompis"],wrong:["lärare","granne"],gap:["Hon fick hjälp av en","klasskamrat","med läxan."],gapForm:"klasskamrat",form:"en klasskamrat – klasskamrater"});
W("forsiktig",{sv:"försiktigt",m:rx("försiktig(t|a)?"),d:t3("Lugnt och noga, så att inget går fel.","Calmly and carefully, so nothing goes wrong.","بهدوء وانتباه حتى لا يحدث خطأ."),ex:"Bär glaset försiktigt!",tr:{en:"carefully",ar:"بحذر"},syn:["varsamt"],opp:["slarvigt"],wrong:["snabbt","högt"],gap:["Han öppnade dörren","försiktigt","för att inte väcka någon."],gapForm:"försiktigt",form:"försiktig – försiktigt – försiktiga"});
W("presentera",{sv:"presentera sig",m:rx("presentera(r|de|t)?( sig)?"),d:t3("Berätta vem man är för nya människor.","Tell new people who you are.","أن تخبر الناس الجدد من أنت."),ex:"Hon presenterade sig för klassen.",tr:{en:"introduce yourself",ar:"يعرّف بنفسه"},syn:["berätta vem man är"],wrong:["gömma sig","springa iväg"],gap:["Den nya eleven fick","presentera sig","för klassen."],gapForm:"presentera sig",form:"presentera – presenterade – har presenterat"});
W("marka",{sv:"märka",m:rx("märk(a|er|te|t)"),d:t3("Se eller förstå att något händer.","See or realise that something is happening.","أن ترى أو تفهم أن شيئًا يحدث."),ex:"Hon märkte att det regnade.",tr:{en:"notice",ar:"يلاحظ"},syn:["upptäcka","lägga märke till"],wrong:["glömma","sova"],gap:["Läraren","märkte","att Amir var trött."],gapForm:"märkte",form:"märka – märkte – har märkt"});
W("lattad",{sv:"lättad",m:rx("lättad(e|t)?"),d:t3("Glad för att något jobbigt är över.","Glad that something hard is over.","مرتاح لأن شيئًا صعبًا انتهى."),ex:"Han var lättad efter provet.",tr:{en:"relieved",ar:"مرتاح"},syn:["lugn igen"],opp:["orolig"],wrong:["arg","hungrig"],gap:["När hon hittade nyckeln blev hon","lättad","."],gapForm:"lättad",form:"lättad – lättat – lättade"});
W("ordfoljd",{sv:"ordföljd",m:rx("ordföljd(en)?"),d:t3("I vilken ordning orden står i en mening.","The order of the words in a sentence.","ترتيب الكلمات في الجملة."),ex:"I dag går jag.",tr:{en:"word order",ar:"ترتيب الكلمات"}});
W("verb",{sv:"verb",m:rx("verb(et|en)?"),d:t3("Ett ord som säger vad någon gör.","A word that says what someone does.","كلمة تقول ماذا يفعل شخص ما."),ex:"springa, läser, åt",tr:{en:"verb",ar:"فعل"}});
W("subjekt",{sv:"subjekt",m:rx("subjekt(et)?"),d:t3("Den som gör något i meningen.","The one who does something in the sentence.","من يقوم بالفعل في الجملة."),ex:"Amir springer. (Amir)",tr:{en:"subject",ar:"الفاعل"}});
W("mening",{sv:"mening",m:rx("mening(en|ar|arna)?"),d:t3("Ord som hör ihop, från stor bokstav till punkt.","Words that belong together, from capital letter to full stop.","كلمات مترابطة من الحرف الكبير إلى النقطة."),ex:"Jag heter Amir.",tr:{en:"sentence",ar:"جملة"}});
const V2=[["I dag","börjar","Amir","i en ny klass"],["Efter lunchen","spelar","de","fotboll"],["På måndag","har","vi","matte"],["Ibland","glömmer","Sara","sin nyckel"],["I korridoren","står","eleverna","och väntar"],["Klockan åtta","ringer","skolklockan","in"],["Sedan","presenterar","Amir","sig"],["På rasten","märker","han","en tjej"]];
const P1=[pic(`<rect x="40" y="70" width="220" height="150" rx="6" fill="#f6d8a8"/><rect x="40" y="58" width="220" height="18" fill="#c0573e"/><rect x="134" y="160" width="32" height="60" fill="#7a4b2a"/>${[0,1,2,3].map(i=>`<rect x="${58+i*52}" y="96" width="30" height="30" fill="#bfe0f5"/>`).join("")}<rect y="220" width="300" height="80" fill="#9fcf8f"/>${kid(90,200,"#2a7d9c","#3b2a1e",.8)}<text x="130" y="186" font-size="22">💭</text>`),
 pic(`<rect x="0" y="0" width="300" height="300" fill="#e9eef5"/><path d="M0 230 L300 230" stroke="#c6cfdc" stroke-width="4"/>${[0,1,2,3,4,5].map(i=>`<rect x="${10+i*48}" y="80" width="40" height="150" fill="${["#5aa0d8","#e98a5a","#5aa0d8","#7cc08a","#e98a5a","#5aa0d8"][i]}" stroke="#33415c" stroke-width="2"/><circle cx="${42+i*48}" cy="155" r="3" fill="#33415c"/>`).join("")}${kid(150,170,"#2a7d9c","#3b2a1e",.9)}<rect x="176" y="182" width="40" height="30" rx="3" fill="#fff" stroke="#33415c"/><text x="196" y="202" font-size="12" text-anchor="middle">204</text>`),
 pic(`<rect x="30" y="30" width="240" height="110" rx="6" fill="#2f4a3a"/><text x="150" y="95" font-family="Caveat,cursive" font-size="40" fill="#fff" text-anchor="middle">Välkommen Amir!</text>${kid(90,170,"#2a7d9c","#3b2a1e",.9)}${kid(230,190,"#d35f8d","#7a3b1e",.8)}`),
 pic(`<rect x="20" y="170" width="260" height="20" rx="4" fill="#b98757"/><rect x="40" y="190" width="10" height="70" fill="#8d6440"/><rect x="250" y="190" width="10" height="70" fill="#8d6440"/>${kid(105,110,"#2a7d9c","#3b2a1e",.85)}${kid(195,110,"#d35f8d","#7a3b1e",.85)}<circle cx="150" cy="250" r="22" fill="#fff" stroke="#1d2433" stroke-width="3"/><path d="M150 236l10 8-4 12h-12l-4-12z" fill="#1d2433"/>`)];
const U1={id:"sv7a",year:7,ord:1,title:t3("Första dagen","The first day","اليوم الأول"),storyTitle:"Första dagen i nya klassen",
 icon:`<svg viewBox="0 0 320 180"><rect width="320" height="180" fill="#eef4fb"/><rect x="60" y="40" width="200" height="110" rx="6" fill="#f6d8a8"/><rect x="60" y="30" width="200" height="16" fill="#c0573e"/><rect x="146" y="100" width="28" height="50" fill="#7a4b2a"/>${[0,1,2,3].map(i=>`<rect x="${78+i*46}" y="60" width="26" height="24" fill="#bfe0f5"/>`).join("")}<text x="290" y="168" font-family="Caveat,cursive" font-weight="700" font-size="34" fill="#1f4fb0" text-anchor="end">Hej!</text></svg>`,
 pic:pic(""),words:["nervos","korridor","schema","klasskamrat","forsiktig","presentera","marka","lattad"],terms:["ordfoljd","verb","subjekt"],
 story:[
  {text:["Amir stod utanför den stora skolan med ryggsäcken på ena axeln. Det var hans första dag i en ny klass, och han var nervös.", "Magen kändes konstig, och händerna var kalla fast det var varmt ute. Familjen hade flyttat från Göteborg i somras, och han kände ingen här."],
   pic:P1[0],
   say:t3("Läs första delen. Tryck på de blå orden om du inte förstår dem.","Read the first part. Tap the blue words if you don't understand them.","اقرأ الجزء الأول. اضغط على الكلمات الزرقاء إن لم تفهمها.")},
  {text:["Telefonen surrade i fickan. Det var mamma. ”Det kommer att gå bra”, sa hon. ”Kom ihåg att alla var nya någon gång.”", "Amir svarade inte direkt. Han tittade på eleverna som skrattade vid porten. ”Okej”, sa han till slut. Sedan tog han ett djupt andetag och gick in."],
   pic:P1[0],
   say:t3("Vad menar mamma med att alla var nya någon gång? Fundera medan du läser.","What does Mum mean by 'everyone was new once'? Think about it as you read.","ماذا تقصد الأم بأن الجميع كانوا جددًا يومًا؟ فكّر وأنت تقرأ.")},
  {text:["I korridoren var det fullt av elever. Några stod vid sina skåp, andra sprang mot trappan. Alla verkade veta vart de skulle.", "Amir tittade på sitt schema: Matematik, sal 204. Han gick försiktigt uppför trappan och letade efter rätt dörr. Sal 201, 202, 203 … Där!"],
   pic:P1[1],
   say:t3("Ett schema visar vilka lektioner du har. Vad står på Amirs schema?","A timetable shows your lessons. What does Amir's say?","الجدول يبيّن حصصك. ماذا يقول جدول أمير؟")},
  {text:["Han knackade och öppnade dörren. Lektionen hade redan börjat. Alla vände sig om och stirrade på honom.", "”Du måste vara Amir”, sa läraren och log. ”Välkommen! Vill du presentera dig för klassen?” Amirs kinder blev varma."],
   pic:P1[2],
   say:t3("Att presentera sig betyder att säga vem man är. Varför blir Amirs kinder varma?","'Presentera sig' means saying who you are. Why do Amir's cheeks get warm?","«presentera sig» يعني أن تقول من أنت. لماذا احمرّ خدّا أمير؟")},
  {text:["”Jag heter Amir och jag kommer från Göteborg”, sa han tyst. ”Jag gillar fotboll och … matte.”", "Några skrattade, men inte elakt. En tjej längst bak log mot honom och pekade på den tomma stolen bredvid sig. Hon hette Sara."],
   pic:P1[2],
   say:t3("Några skrattade, ”men inte elakt”. Vad betyder det för Amir?","Some laughed, 'but not in a mean way'. What does that mean for Amir?","ضحك بعضهم «لكن ليس بسوء». ماذا يعني ذلك لأمير؟")},
  {text:["På lunchen stod Amir med sin bricka och visste inte var han skulle sitta. Då vinkade Sara. ”Kom hit!”", "Han satte sig bredvid henne. ”Vill du vara med och spela fotboll efter skolan?” frågade hon. ”Vi behöver en till i laget.”"],
   pic:P1[3],
   say:t3("Varför frågar Sara om Amir vill spela? Läs noga.","Why does Sara ask Amir to play? Read carefully.","لماذا تسأل سارة أمير إن كان يريد اللعب؟ اقرأ بانتباه.")},
  {text:["Amir märkte att han inte var nervös längre. Magen kändes som vanligt igen. Han var lättad.", "På vägen hem skickade han ett meddelande till mamma: ”Det gick bra. Jag ska spela fotboll i morgon.” Kanske skulle hans nya klasskamrater bli hans vänner."],
   pic:P1[3],
   say:t3("Hur känner sig Amir nu? Hitta ordet i texten.","How does Amir feel now? Find the word in the text.","كيف يشعر أمير الآن؟ ابحث عن الكلمة في النص.")}],
 wordsSay:t3("Här är de nya orden. Tryck på ett ord för att se vad det betyder, en synonym och ett exempel.","Here are the new words. Tap a word to see its meaning, a synonym and an example.","هذه هي الكلمات الجديدة. اضغط على كلمة لترى معناها ومرادفها ومثالًا."),
 grammar:[
  {draw:()=>[A.wipe(),A.tx(L(t3("Ordföljd: verbet på plats 2","Word order: the verb in place 2","ترتيب الكلمات: الفعل في المكان الثاني")),400,70,40,"b"),...boxes([["Amir","b","subjekt"],["går","r","verb"],["till skolan",null]],210,48)],
   say:t3("I en svensk mening står verbet nästan alltid på plats 2. Här: Amir (1) går (2).","In a Swedish sentence the verb is almost always in place 2. Here: Amir (1) går (2).","في الجملة السويدية يأتي الفعل دائمًا تقريبًا في المكان الثاني. هنا: Amir (1) går (2).")},
  {draw:()=>[...boxes([["I dag","o","plats 1"],["går","r","plats 2: verb"],["Amir","b","subjekt"],["till skolan",null]],380,44)],
   say:t3("Börjar meningen med något annat, till exempel ”I dag”, så stannar verbet på plats 2. Subjektet flyttar efter verbet.","If the sentence starts with something else, like ”I dag”, the verb stays in place 2. The subject moves after the verb.","إذا بدأت الجملة بشيء آخر مثل «I dag» يبقى الفعل في المكان الثاني، وينتقل الفاعل إلى ما بعد الفعل.")},
  {draw:()=>[A.wipe(),A.tx("Today Amir goes to school.",400,100,36,"k"),A.tx("✗  I dag Amir går till skolan.",400,210,40,"r"),A.tx("✓  I dag går Amir till skolan.",400,300,40,"g"),A.p(R.line(150,222,640,222,.3),"r",3),A.hl(130,262,540,56)],
   say:t3("På engelska säger man ”Today Amir goes”. På svenska blir det fel! Rätt är: I dag går Amir.","In English you say ”Today Amir goes”. In Swedish that is wrong! Right: I dag går Amir.","بالإنجليزية نقول «Today Amir goes». بالسويدية هذا خطأ! الصحيح: I dag går Amir.")}],
 read:[
  {q:"Varför var Amir nervös?",o:["Det var hans första dag i en ny klass.", "Han hade glömt sin mat.", "Han kom för sent."],why:"Del 1: hans första dag i en ny klass."},
  {q:"Varför kände Amir ingen på skolan?",o:["Familjen hade flyttat från Göteborg.", "Han hade varit sjuk länge.", "Skolan var helt ny."],why:"Del 1: Familjen hade flyttat i somras."},
  {q:"Vad menar mamma med ”alla var nya någon gång”?",o:["Alla har någon gång känt sig som Amir.", "Alla elever är nya i år.", "Skolan har många nya lärare."],why:"Alla har varit nya och nervösa förut."},
  {q:"Vilken lektion stod först på Amirs schema?",o:["Matematik i sal 204", "Idrott i sal 204", "Engelska i sal 104"],why:"Del 3: Matematik, sal 204."},
  {q:"Varför blev Amirs kinder varma?",o:["Han blev generad när alla tittade.", "Det var för varmt i salen.", "Han hade sprungit i trappan."],why:"Del 4: Alla stirrade på honom."},
  {q:"Vem log mot Amir i klassrummet?",o:["Sara", "Läraren", "Mamma"],why:"Del 5: En tjej längst bak log. Hon hette Sara."},
  {q:"Varför frågade Sara om Amir ville spela?",o:["Laget behövde en spelare till.", "Hon ville vinna över honom.", "Läraren sa åt henne."],why:"Del 6: ”Vi behöver en till i laget.”"},
  {q:"Hur vet vi att Amir mår bättre i slutet?",o:["Magen kändes som vanligt igen.", "Han gick hem tidigt.", "Han ringde till Sara."],why:"Del 7: Magen kändes som vanligt igen."},
  {q:"”Magen kändes konstig.” Vad betyder det här?",o:["Amir var orolig.", "Amir var mätt.", "Amir var trött."],why:"När man är nervös kan magen kännas konstig."}],
 gram(lv,write){const [a,v,s,r]=pick(V2),right=sent([a,v,s,r]);
  if(write||lv===2){const base=sent([cap(s),v,r]);
   return{kind:"text",ans:[right],show:right,q:[A.wipe(),A.tx(L(t3("Skriv om meningen. Börja med:","Rewrite the sentence. Start with:","أعد كتابة الجملة. ابدأ بـ:")),400,80,32,"b"),A.tx(`”${a} …”`,400,150,44,"o"),...svLines(base,270,40)],
    sol:[A.tx(right,400,420,38,"g")],hint:{say:t3("Verbet ska stå på plats 2, direkt efter ”"+a+"”.","The verb goes in place 2, right after ”"+a+"”.","يجب أن يأتي الفعل في المكان الثاني مباشرة بعد «"+a+"»."),draw:[]}}}
  const wrong1=sent([a,s,v,r]),wrong2=sent([a,s,r,v]),opts=shuffle([right,wrong1,wrong2]);
  return{kind:"choice",opts,ans:opts.indexOf(right),show:right,q:[A.wipe(),A.tx(L(t3("Vilken mening har rätt ordföljd?","Which sentence has the right word order?","أي جملة ترتيبها صحيح؟")),400,120,38,"b"),A.tx(L(t3("Tänk: verbet på plats 2.","Think: the verb in place 2.","فكّر: الفعل في المكان الثاني.")),400,200,30,"k")],
   sol:[...boxes([[a,"o","1"],[v,"r","2"],[s,"b",""],...(r?[[r,null]]:[])],380,36)],hint:{say:t3("Hitta verbet. Står det som ord nummer 2?","Find the verb. Is it word number 2?","ابحث عن الفعل. هل هو الكلمة رقم 2؟"),draw:[]}}},
 help:[{say:t3("Verbet står på plats 2: I dag (1) går (2) Amir.","The verb is in place 2: I dag (1) går (2) Amir.","الفعل في المكان 2: I dag (1) går (2) Amir."),draw:()=>boxes([["I dag","o","1"],["går","r","2"],["Amir","b",""]],250,48)}]};
LESSONS.push(svUnit(U1));

/* ---------------- unit 2: Matchen i regnet (verbets tider) ---------------- */
W("tranare",{sv:"tränare (en)",m:rx("tränar(e|en|na)"),d:t3("En person som leder och lär upp ett lag.","A person who leads and teaches a team.","شخص يقود الفريق ويدرّبه."),ex:"Tränaren gav oss råd.",tr:{en:"coach",ar:"مدرّب"},syn:["coach","ledare"],wrong:["domare","publik"],gap:["Vår","tränare","säger att vi ska värma upp."],gapForm:"tränare",form:"en tränare – tränare"});
W("motstandare",{sv:"motståndare (en)",m:rx("motståndar(e|en|na)"),d:t3("Den man tävlar eller spelar mot.","The one you compete or play against.","من تنافسه أو تلعب ضده."),ex:"Motståndarna var snabba.",tr:{en:"opponent",ar:"خصم"},syn:["konkurrent"],opp:["lagkamrat"],wrong:["tränare","kompis"],gap:["Vi vann mot våra","motståndare","med 3–0."],gapForm:"motståndare",form:"en motståndare – motståndare"});
W("avgorande",{sv:"avgörande",m:rx("avgörande"),d:t3("Mycket viktig, den bestämmer hur det slutar.","Very important, it decides how it ends.","مهم جدًا، يحدد كيف ينتهي الأمر."),ex:"Det var en avgörande match.",tr:{en:"decisive",ar:"حاسم"},syn:["mycket viktig"],opp:["oviktig"],wrong:["tråkig","lång"],gap:["Det sista målet blev","avgörande","för matchen."],gapForm:"avgörande",form:"avgörande"});
W("jubla",{sv:"jubla",m:rx("jubla(r|de|t)?"),d:t3("Ropa och skrika av glädje.","Shout and cheer with joy.","يصرخ ويهتف من الفرح."),ex:"Publiken jublade.",tr:{en:"cheer",ar:"يهتف فرحًا"},syn:["hurra","ropa av glädje"],opp:["sörja"],wrong:["viska","gråta"],gap:["Alla började","jubla","när bollen gick in."],gapForm:"jubla",form:"jubla – jublade – har jublat"});
W("utmattad",{sv:"utmattad",m:rx("utmattad(e|t)?"),d:t3("Väldigt, väldigt trött.","Very, very tired.","متعب جدًا جدًا."),ex:"Efter loppet var hon utmattad.",tr:{en:"exhausted",ar:"منهَك"},syn:["slutkörd","jättetrött"],opp:["pigg"],wrong:["arg","hungrig"],gap:["Efter tre timmars träning var vi","utmattade","."],gapForm:"utmattade",form:"utmattad – utmattat – utmattade"});
W("peppa",{sv:"peppa",m:rx("peppa(r|de|t)?"),d:t3("Ge någon mod och energi med ord.","Give someone courage and energy with words.","تعطي شخصًا شجاعة وطاقة بالكلام."),ex:"Hon peppade sin kompis.",tr:{en:"pep up, encourage",ar:"يشجّع"},syn:["uppmuntra"],opp:["trycka ner"],wrong:["skämta","vänta"],gap:["Tränaren försökte","peppa","laget före matchen."],gapForm:"peppa",form:"peppa – peppade – har peppat"});
W("lagkamrat",{sv:"lagkamrat (en)",m:rx("lagkamrat(en|er|erna)?"),d:t3("En som spelar i samma lag som du.","Someone who plays in the same team as you.","شخص يلعب معك في الفريق نفسه."),ex:"Han passade till sin lagkamrat.",tr:{en:"teammate",ar:"زميل في الفريق"},syn:["medspelare"],opp:["motståndare"],wrong:["domare","granne"],gap:["Hon passade bollen till en","lagkamrat","."],gapForm:"lagkamrat",form:"en lagkamrat – lagkamrater"});
W("forlora",{sv:"förlora",m:rx("förlora(r|de|t)?"),d:t3("Inte vinna. Eller: bli av med något.","Not win. Or: lose something.","ألّا تفوز. أو: أن تفقد شيئًا."),ex:"Vi förlorade med 1–2.",tr:{en:"lose",ar:"يخسر"},syn:["torska (vardagligt)"],opp:["vinna"],wrong:["träna","springa"],gap:["Ingen vill","förlora","en final."],gapForm:"förlora",form:"förlora – förlorade – har förlorat"});
W("presens",{sv:"presens",m:rx("presens"),d:t3("Verbets nu-form: det händer nu eller ofta.","The verb's now-form: it happens now or often.","زمن الحاضر: يحدث الآن أو غالبًا."),ex:"jag spelar",tr:{en:"present tense",ar:"المضارع"}});
W("preteritum",{sv:"preteritum",m:rx("preteritum"),d:t3("Verbets då-form: det hände förut.","The verb's then-form: it happened before.","زمن الماضي: حدث من قبل."),ex:"jag spelade",tr:{en:"past tense",ar:"الماضي"}});
W("perfekt",{sv:"perfekt",m:rx("perfekt"),d:t3("har + verb: det har hänt och märks nu.","har + verb: it has happened and matters now.","har + فعل: حدث ونرى أثره الآن."),ex:"jag har spelat",tr:{en:"present perfect",ar:"الماضي التام"}});
W("infinitiv",{sv:"infinitiv",m:rx("infinitiv(en)?"),d:t3("Verbets grundform, ofta efter ”att”.","The verb's basic form, often after ”att”.","صيغة المصدر، غالبًا بعد «att»."),ex:"att spela",tr:{en:"infinitive",ar:"المصدر"}});
const VB=[["spela","spelar","spelade","har spelat"],["jubla","jublar","jublade","har jublat"],["förlora","förlorar","förlorade","har förlorat"],["peppa","peppar","peppade","har peppat"],["träna","tränar","tränade","har tränat"],["märka","märker","märkte","har märkt"],["skjuta","skjuter","sköt","har skjutit"],["springa","springer","sprang","har sprungit"],["få","får","fick","har fått"],["vinna","vinner","vann","har vunnit"]];
const FR=[["spela",2,"Igår {v} vi fotboll i regnet."],["spela",1,"Varje lördag {v} Sara med laget."],["spela",3,"Vi har aldrig {v} i en final förut."],["jubla",2,"Publiken {v} när bollen gick in."],["jubla",1,"Nu {v} alla på läktaren."],
 ["förlora",3,"Laget har inte {v} någon match i höst."],["förlora",2,"Förra året {v} de finalen."],["peppa",2,"Tränaren {v} laget före matchen."],["träna",3,"Ni har {v} hårt hela hösten."],["träna",1,"Varje tisdag {v} vi efter skolan."],
 ["märka",2,"Amir {v} att Sara var glad."],["skjuta",2,"Sara {v} – och bollen gick in!"],["skjuta",3,"Amir har {v} två mål i år."],["springa",2,"Han {v} försiktigt på den hala planen."],["springa",1,"Varje morgon {v} hon tre kilometer."],
 ["få",2,"I sista minuten {v} Amir bollen igen."],["vinna",3,"Vi har {v} fem matcher i rad."],["vinna",2,"Igår {v} laget med 2–1."]];
const STRONG=["skjuta","springa","få","vinna"];
const P2=[pic(`${[...Array(16)].map((_,i)=>`<path d="M${10+i*18} ${20+(i%4)*30}l-7 16" stroke="#4d7fe0" stroke-width="3" stroke-linecap="round"/>`).join("")}<rect y="200" width="300" height="100" fill="#5fae5a"/>${kid(110,140,"#e0b43a","#3b2a1e",.85)}${kid(190,140,"#e0b43a","#7a3b1e",.85)}`,"#cfe3ee"),
 pic(`${kid(150,120,"#33415c","#5b4636",1)}<circle cx="172" cy="150" r="5" fill="#c0c7d4"/><path d="M60 250h180" stroke="#fff" stroke-width="4"/><text x="150" y="80" font-size="30" text-anchor="middle">📣</text>`,"#cfe3ee"),
 pic(`<rect y="160" width="300" height="140" fill="#5fae5a"/><rect x="190" y="110" width="96" height="70" fill="none" stroke="#fff" stroke-width="6"/>${kid(80,150,"#e0b43a","#7a3b1e",.75)}<circle cx="232" cy="150" r="13" fill="#fff" stroke="#1d2433" stroke-width="3"/><path d="M100 170 Q170 110 220 148" stroke="#1d2433" stroke-dasharray="6 6" stroke-width="3" fill="none"/>`,"#cfe3ee"),
 pic(`<rect y="200" width="300" height="100" fill="#5fae5a"/>${kid(110,140,"#e0b43a","#3b2a1e",.85)}${kid(190,140,"#e0b43a","#7a3b1e",.85)}<path d="M80 150l-20-40M220 150l20-40" stroke="#e0b43a" stroke-width="12" stroke-linecap="round"/><text x="150" y="70" font-family="Caveat,cursive" font-weight="700" font-size="54" text-anchor="middle" fill="#1d2433">2–1!</text>`,"#cfe3ee")];
const U2={id:"sv7b",year:7,ord:2,title:t3("Matchen i regnet","The match in the rain","المباراة تحت المطر"),storyTitle:"Matchen i regnet",
 icon:`<svg viewBox="0 0 320 180"><rect width="320" height="180" fill="#cfe3ee"/><rect y="110" width="320" height="70" fill="#5fae5a"/>${[...Array(14)].map((_,i)=>`<path d="M${12+i*23} ${10+(i%3)*14}l-6 14" stroke="#4d7fe0" stroke-width="3" stroke-linecap="round"/>`).join("")}<rect x="230" y="70" width="70" height="44" fill="none" stroke="#fff" stroke-width="5"/><circle cx="120" cy="120" r="16" fill="#fff" stroke="#1d2433" stroke-width="3"/><text x="40" y="70" font-family="Caveat,cursive" font-weight="700" font-size="40" fill="#1d2433">2–1</text></svg>`,
 pic:pic(""),words:["tranare","motstandare","avgorande","jubla","utmattad","peppa","lagkamrat","forlora"],terms:["presens","preteritum","perfekt","infinitiv"],
 story:[
  {text:["Det regnade hela lördagen. Stora pölar låg på fotbollsplanen bakom skolan. Sara och Amir skulle spela en avgörande match mot Hammarby.", "Om de vann, skulle laget gå till final för första gången på tio år. Sara hade tagit med sig ett paraply, men det hjälpte inte mycket i den kalla vinden."],
   pic:P2[0],
   say:t3("En ny berättelse om Amir och Sara. Kommer du ihåg orden från förra gången? De är understrukna.","A new story about Amir and Sara. Do you remember the words from last time? They are underlined.","قصة جديدة عن أمير وسارة. هل تتذكر كلمات المرة الماضية؟ تحتها خط.")},
  {text:["Amir var lite nervös. Han hade bara spelat i laget i tre veckor. I omklädningsrummet satt alla tysta och knöt sina skor.", "Då ställde sig tränaren mitt i rummet och började peppa dem."],
   pic:P2[1],
   say:t3("Varför är Amir nervös den här gången? Det är en annan orsak än förra berättelsen.","Why is Amir nervous this time? It's a different reason from the last story.","لماذا أمير متوتر هذه المرة؟ السبب مختلف عن القصة السابقة.")},
  {text:["”Ni har tränat hårt hela hösten”, sa tränaren. ”Ni har sprungit i mörker och regn. Spela tillsammans, prata med varandra och var inte rädda.", "Regnet är samma för båda lagen.” Några skrattade, och stämningen i rummet blev bättre."],
   pic:P2[1],
   say:t3("Tränaren säger: ”Ni har tränat.” Det är perfekt: har + tränat. Vi tittar på det sedan.","The coach says: ”Ni har tränat.” That is perfekt: har + tränat. We'll look at it later.","يقول المدرب: «Ni har tränat». هذا زمن perfekt: har + tränat. سنراه لاحقًا.")},
  {text:["Motståndarna var stora och snabba. Redan efter tio minuter gjorde de ett mål, och Hammarbys supportrar började jubla.", "Amirs lag såg ledset ut. En försvarare sparkade argt i en vattenpöl så att det stänkte. ”Det gör inget, det är lång tid kvar”, sa Sara, men hon lät inte säker."],
   pic:P2[2],
   say:t3("Hur visar texten att laget blev ledset, utan att bara säga ”ledset”?","How does the text show the team got sad, without only saying 'sad'?","كيف يُظهر النص حزن الفريق دون أن يقول «حزين» فقط؟")},
  {text:["Amir märkte att hans lagkamrater började tappa modet. ”Kom igen, vi kan fortfarande vinna!” ropade han.", "Han sprang försiktigt på den hala planen, tog bollen från en motståndare och passade till Sara. Hon sköt – och bollen gick in! Det stod 1–1."],
   pic:P2[2],
   say:t3("Sprang och sköt är preteritum av springa och skjuta. Lägg märke till att vokalen ändras.","Sprang and sköt are the past tense of springa and skjuta. Notice that the vowel changes.","sprang و sköt ماضي springa و skjuta. لاحظ أن حرف العلة يتغيّر.")},
  {text:["Andra halvlek var tuff. Det regnade ännu mer, och alla var leriga upp till knäna. Ingen ville förlora.", "Tränaren gick fram och tillbaka vid sidlinjen och tittade på klockan. Domaren gjorde samma sak. Bara en minut kvar."],
   pic:P2[2],
   say:t3("Spänningen ökar. Vilka ord i texten visar att det är spännande?","The tension grows. Which words show it's exciting?","التشويق يزداد. أي كلمات في النص تُظهر ذلك؟")},
  {text:["I sista minuten fick Amir bollen igen. Han sköt hårt, och bollen gick in i krysset. 2–1! Publiken började jubla.", "Efter matchen var alla utmattade men glada. ”Vi har aldrig förlorat en match i regn”, skrattade Sara. Amir var lättad. På bussen hem sjöng hela laget, och ingen brydde sig om att de var blöta. Nu väntade finalen."],
   pic:P2[3],
   say:t3("Hur kändes det för laget efter matchen? Två ord i texten berättar det.","How did the team feel after the match? Two words in the text tell you.","كيف شعر الفريق بعد المباراة؟ كلمتان في النص تخبرانك.")}],
 wordsSay:t3("Nya ord! Tryck på dem. Orden nervös, märka, lättad och försiktigt kommer från förra berättelsen.","New words! Tap them. The words nervös, märka, lättad and försiktigt come from the last story.","كلمات جديدة! اضغط عليها. الكلمات nervös وmärka وlättad وförsiktigt من القصة السابقة."),
 grammar:[
  {draw:()=>{const y=250,X=[170,400,630];return[A.wipe(),A.tx(L(t3("Verbets tider","The verb's tenses","أزمنة الفعل")),400,64,40,"b"),A.arrow(60,y,750,y,"k"),
    ...[["förut","spelade","preteritum","o"],["nu","spelar","presens","b"],["har hänt, märks nu","har spelat","perfekt","g"]].flatMap(([t,v,n,c],i)=>[A.p(R.line(X[i],y-14,X[i],y+14,.2),c,5),qt(t,X[i],y+48,24,c),A.tx(v,X[i],y-40,42,c),qt(n,X[i],y+86,26,c)])]},
   say:t3("Ett verb ändrar form efter när något händer. Igår spelade vi. Nu spelar vi. Vi har spelat många matcher.","A verb changes form with when something happens. Igår spelade vi. Nu spelar vi. Vi har spelat många matcher.","يتغيّر شكل الفعل حسب وقت الحدث. Igår spelade vi. Nu spelar vi. Vi har spelat många matcher.")},
  {draw:()=>{const C=[150,320,490,660],rows=[["infinitiv","presens","preteritum","perfekt"],["spela","spelar","spelade","har spelat"],["jubla","jublar","jublade","har jublat"],["förlora","förlorar","förlorade","har förlorat"]];
    return[A.wipe(),...rows.flatMap((r,j)=>r.map((s,i)=>j?A.tx(s,C[i],150+j*80,34,["k","b","o","g"][i]):qt(s,C[i],110,26,["k","b","o","g"][i]))),A.hl(560,330,200,52)]},
   say:t3("Många verb följer samma mönster: -r i presens, -de i preteritum och har + -t i perfekt.","Many verbs follow the same pattern: -r in presens, -de in preteritum and har + -t in perfekt.","أفعال كثيرة تتبع النمط نفسه: ‎-r في الحاضر، ‎-de في الماضي، وhar + ‎-t في perfekt.")},
  {draw:()=>{const C=[180,400,620],rows=[["skjuta","sköt","har skjutit"],["springa","sprang","har sprungit"],["få","fick","har fått"],["vinna","vann","har vunnit"]];
    return[A.wipe(),A.tx(L(t3("Starka verb byter vokal","Strong verbs change vowel","الأفعال القوية تغيّر حرف العلة")),400,64,36,"r"),...rows.flatMap((r,j)=>r.map((s,i)=>A.tx(s,C[i],150+j*80,36,["k","o","g"][i])))]},
   say:t3("Vissa verb är starka: de byter vokal, som skjuta – sköt. Dem lär man sig utantill, lite i taget.","Some verbs are strong: they change vowel, like skjuta – sköt. You learn them by heart, a few at a time.","بعض الأفعال قوية: تغيّر حرف العلة مثل skjuta – sköt. نحفظها شيئًا فشيئًا.")}],
 read:[
  {q:"Varför var matchen avgörande?",o:["Om de vann, gick laget till final.", "Det var säsongens första match.", "Tränaren skulle sluta."],why:"Del 1: Om de vann, skulle laget gå till final."},
  {q:"Varför var Amir lite nervös före matchen?",o:["Han var ny i laget.", "Han hade ont i benet.", "Han hade glömt skorna."],why:"Del 2: bara spelat i laget i tre veckor."},
  {q:"Vad menar tränaren med ”Regnet är samma för båda lagen”?",o:["Inget lag får en fördel av regnet.", "Det regnar bara på ena planhalvan.", "Matchen kan ställas in."],why:"Båda lagen spelar i samma regn."},
  {q:"Hur märks det att laget var ledset efter 0–1?",o:["En försvarare sparkade argt i en pöl.", "Tränaren gick hem.", "Alla skrattade."],why:"Del 4: sparkade argt i en vattenpöl."},
  {q:"Vad gjorde Amir när lagkamraterna tappade modet?",o:["Han ropade att de kunde vinna.", "Han bytte tröja.", "Han pratade med domaren."],why:"Del 5: ”Kom igen, vi kan fortfarande vinna!”"},
  {q:"Vem gjorde det första målet för Amirs lag?",o:["Sara", "Amir", "Tränaren"],why:"Del 5: Hon sköt – och bollen gick in!"},
  {q:"Varför sprang Amir försiktigt?",o:["Planen var hal av regnet.", "Han hade ont i foten.", "Tränaren sa åt honom."],why:"Del 5: den hala planen."},
  {q:"Hur slutade matchen?",o:["2–1 till Amirs lag", "1–1", "1–2 till Hammarby"],why:"Del 7: 2–1!"},
  {q:"Vad tror du händer sedan?",o:["Laget spelar final.", "Laget lägger ner.", "Sara byter lag."],why:"Sista meningen: Nu väntade finalen."}],
 gram(lv,write){const [inf,t,frame]=pick(FR.filter(f=>lv>0||!STRONG.includes(f[0]))),vb=VB.find(v=>v[0]===inf),word=t===3?vb[3].slice(4):vb[t];
  const q=frame.replace("{v}","____"),done=frame.replace("{v}",word),tense=["","presens","preteritum","perfekt"][t];
  const head=[A.wipe(),A.tx(L(t3("Skriv verbet i rätt form","Write the verb in the right form","اكتب الفعل بالصيغة الصحيحة")),400,70,34,"b"),...svLines(q,200,40),A.tx(`(${vb[0]})`,400,300,36,"o")];
  if(write||lv===2)return{kind:"text",ans:[word],show:word,q:head,sol:[A.tx(done,400,410,36,"g"),qt(tense,400,460,26,"g")],hint:{say:t3(`Tänk på tiden: ${tense}.`,`Think about the tense: ${tense}.`,`فكّر في الزمن: ${tense}.`),draw:[]}};
  const opts=shuffle([...new Set([vb[1],vb[2],vb[3].slice(4)])]);if(opts.length<3)return null;
  return{kind:"choice",opts,ans:opts.indexOf(word),show:word,q:head.slice(0,4).concat([A.tx(L(t3("Välj rätt form","Choose the right form","اختر الصيغة الصحيحة")),400,300,30,"k")]),sol:[A.tx(done,400,410,36,"g"),qt(tense,400,460,26,"g")],
   hint:{say:t3("Titta på tidsordet: igår = preteritum, nu/varje = presens, har = perfekt.","Look at the time word: igår = past, nu/varje = present, har = perfekt.","انظر إلى كلمة الزمن: igår = ماضٍ، nu/varje = حاضر، har = perfekt."),draw:[]}}},
 help:[{say:t3("Igår → preteritum (spelade). Nu → presens (spelar). Har → perfekt (har spelat).","Igår → past (spelade). Nu → present (spelar). Har → perfekt (har spelat).","Igår ← ماضٍ (spelade). Nu ← حاضر (spelar). Har ← perfekt (har spelat)."),draw:()=>[A.tx("igår: spelade",400,160,44,"o"),A.tx("nu: spelar",400,250,44,"b"),A.tx("har spelat",400,340,44,"g")]}]};
LESSONS.push(svUnit(U2));
}
