/* Svenska årskurs 7, units 3–5: Finalen (ordklasser), Skollaget i tidningen (substantiv: en/ett, bestämd form, plural),
   Mobilen som försvann (adjektivets böjning). The stories go on from sv7a/sv7b and bring back their words. */
{const {rx,boxes,pic,kid,W,sent,cap}=SVH;
/* a kid with a sad mouth (covers kid()'s smile) */
const sad7=(x,y,shirt,hair,s=1)=>kid(x,y,shirt,hair,s)+`<path d="M${x-6*s} ${y+11*s} Q${x} ${y+15*s} ${x+6*s} ${y+11*s}" stroke="#f1c7a3" stroke-width="${4*s}" fill="none"/><path d="M${x-6*s} ${y+14*s} Q${x} ${y+9*s} ${x+6*s} ${y+14*s}" stroke="#1d2433" stroke-width="${2*s}" fill="none" stroke-linecap="round"/>`;

/* ---------------- unit 3: Finalen (ordklasser: substantiv, verb, adjektiv) ---------------- */
W("laktare",{sv:"läktare (en)",m:rx("läktar(e|en|na)"),d:t3("Platsen där publiken sitter och tittar på en match.","The stands where the audience sits and watches a match.","المكان الذي يجلس فيه الجمهور لمشاهدة المباراة."),ex:"Läktaren var full av folk.",tr:{en:"stand, stands",ar:"مدرّجات"},syn:["tribun"],wrong:["omklädningsrum","målvakt"],gap:["Föräldrarna satt på","läktaren","och tittade på matchen."],gapForm:"läktaren",form:"en läktare – läktare"});
W("domare",{sv:"domare (en)",m:rx("domar(e|en|na)"),d:t3("Den som leder matchen och ser till att alla följer reglerna.","The person who leads the match and makes sure everyone follows the rules.","الشخص الذي يدير المباراة ويتأكد من أن الجميع يتبعون القواعد."),ex:"Domaren blåste i visslan.",tr:{en:"referee",ar:"حَكَم"},syn:["skiljedomare"],wrong:["tränare","publik"],gap:["När matchen var slut, blåste","domaren","i visslan."],gapForm:"domaren",form:"en domare – domare"});
W("straff",{sv:"straffspark (en)",m:rx("straff(spark)?(en|ar|arna)?"),d:t3("En spark mot mål från en punkt, med bara målvakten emot. Kallas också straff.","A kick at goal from a spot, with only the goalkeeper against you. Also called straff.","ركلة نحو المرمى من نقطة محددة، ولا يقف أمامك إلا حارس المرمى. تُسمّى أيضًا straff."),ex:"Amir satte sin straff.",tr:{en:"penalty kick",ar:"ركلة جزاء"},syn:["straff"],wrong:["hörna","inkast"],gap:["Finalen avgjordes med","straffsparkar","efter 1–1."],gapForm:"straffsparkar",form:"en straffspark – straffsparkar"});
W("waga",{sv:"våga",m:rx("våga(r|de|t)?"),d:t3("Göra något fast man är rädd.","Do something even though you are scared.","أن تفعل شيئًا رغم أنك خائف."),ex:"Han vågade skjuta den sista straffen.",tr:{en:"dare",ar:"يجرؤ"},syn:["ha mod","töras"],wrong:["sova","glömma"],gap:["Han var rädd, men han bestämde sig för att","våga","skjuta."],gapForm:"våga",form:"våga – vågade – har vågat"});
W("besviken",{sv:"besviken",m:rx("besvik(en|et|na)"),d:t3("Ledsen för att något inte blev som man hoppades.","Sad because something did not turn out as you hoped.","حزين لأن شيئًا لم يحدث كما كنت تأمل."),ex:"Sara var besviken när hon missade.",tr:{en:"disappointed",ar:"خائب الأمل"},syn:["nedstämd","ledsen"],wrong:["hungrig","pigg"],gap:["Hon blev","besviken","när målvakten räddade hennes straff."],gapForm:"besviken",form:"besviken – besviket – besvikna"});
W("stolt",{sv:"stolt",m:rx("stolt(a)?"),d:t3("Glad och nöjd över något som man själv eller någon annan har gjort.","Happy and pleased about something you or someone else has done.","سعيد وراضٍ عن شيء فعلته أنت أو فعله شخص آخر."),ex:"Tränaren var stolt över laget.",tr:{en:"proud",ar:"فخور"},syn:["nöjd"],opp:["skamsen"],wrong:["rädd","trött"],gap:["Tränaren var så","stolt","över laget."],gapForm:"stolt",form:"stolt – stolt – stolta"});
W("tvivla",{sv:"tvivla",m:rx("tvivla(r|de|t)?"),d:t3("Inte vara säker på något, till exempel på att man klarar det.","Not be sure about something, for example that you can do it.","ألّا تكون متأكدًا من شيء، مثلًا من أنك تستطيع فعله."),ex:"Han började tvivla på sig själv.",tr:{en:"doubt",ar:"يشكّ"},syn:["vara osäker"],opp:["vara säker"],wrong:["springa","skratta"],gap:["Amir började","tvivla","på att han skulle klara det."],gapForm:"tvivla",form:"tvivla – tvivlade – har tvivlat"});
W("applodera",{sv:"applådera",m:rx("applådera(r|de|t)?"),d:t3("Klappa händerna för att visa att man tycker om något.","Clap your hands to show that you like something.","أن تصفّق بيديك لتُظهر أنك أعجبت بشيء."),ex:"Publiken applåderade länge.",tr:{en:"applaud, clap",ar:"يصفّق"},syn:["klappa händerna"],opp:["bua"],wrong:["viska","gråta"],gap:["Efter målet reste sig alla och började","applådera","."],gapForm:"applådera",form:"applådera – applåderade – har applåderat"});
W("ordklass",{sv:"ordklass",m:rx("ordklass(en|er|erna)?"),d:t3("En grupp ord som fungerar på samma sätt, till exempel substantiv eller verb.","A group of words that work in the same way, for example nouns or verbs.","مجموعة كلمات تعمل بالطريقة نفسها، مثل الأسماء أو الأفعال."),ex:"substantiv, verb, adjektiv",tr:{en:"word class",ar:"نوع الكلمة"}});
W("substantiv",{sv:"substantiv",m:rx("substantiv(et|en)?"),d:t3("Ett ord för en sak, en person, ett djur eller en plats.","A word for a thing, a person, an animal or a place.","كلمة تدلّ على شيء أو شخص أو حيوان أو مكان."),ex:"en domare, ett mål, Sara",tr:{en:"noun",ar:"اسم"}});
W("adjektiv",{sv:"adjektiv",m:rx("adjektiv(et|en)?"),d:t3("Ett ord som beskriver hur något eller någon är.","A word that describes what something or someone is like.","كلمة تصف كيف يكون شيء أو شخص."),ex:"stolt, besviken, röd",tr:{en:"adjective",ar:"صفة"}});
/* sentences with exactly one noun (n), one verb (v) and one adjective (a) */
const WC7=["Läktaren/n var/v full/a","Sara/n blev/v besviken/a","Den nya/a domaren/n blåste/v","Den glada/a publiken/n applåderade/v","Bollen/n var/v blöt/a","Vi vann/v en viktig/a match/n","Han sköt/v en hård/a straffspark/n","Han tog/v ett djupt/a andetag/n","De trötta/a spelarna/n sjöng/v","Tränaren/n var/v stolt/a","Den snabba/a målvakten/n räddade/v","Amir/n kände/v sig nervös/a","Det kalla/a vattnet/n stänkte/v","Motståndarna/n var/v starka/a","Hon köpte/v en gul/a flagga/n","Den lilla/a pojken/n jublade/v"];
const WCN7={n:["substantiv","b"],v:["verb","r"],a:["adjektiv","g"]};
const WCT7={n:t3("Skriv substantivet i meningen.","Write the noun from the sentence.","اكتب الاسم الموجود في الجملة."),v:t3("Skriv verbet i meningen.","Write the verb from the sentence.","اكتب الفعل الموجود في الجملة."),a:t3("Skriv adjektivet i meningen.","Write the adjective from the sentence.","اكتب الصفة الموجودة في الجملة.")};
const WCH7={n:t3("Substantiv: kan du sätta en, ett eller den framför ordet? Namn är också substantiv.","Noun: can you put en, ett or den in front of the word? Names are nouns too.","الاسم: هل يمكنك أن تضع en أو ett أو den قبل الكلمة؟ أسماء الأشخاص أسماء أيضًا."),v:t3("Verb: vilket ord säger vad någon gör eller gjorde?","Verb: which word says what someone does or did?","الفعل: أي كلمة تقول ماذا يفعل أو فعل شخص ما؟"),a:t3("Adjektiv: vilket ord beskriver hur något är? Prova ”mycket” framför.","Adjective: which word describes what something is like? Try ”mycket” in front.","الصفة: أي كلمة تصف كيف يكون الشيء؟ جرّب أن تضع «mycket» قبلها.")};
const PC=[pic(`<rect y="200" width="300" height="100" fill="#5fae5a"/><path d="M20 200 L280 200 L262 72 L38 72Z" fill="#c6cfdc"/>${[0,1,2].map(r=>[...Array(8)].map((_,i)=>`<circle cx="${62+i*25+(r%2)*6}" cy="${96+r*36}" r="10" fill="${["#f1c7a3","#c98e63","#8a5a3b"][(i+r)%3]}"/><rect x="${52+i*25+(r%2)*6}" y="${106+r*36}" width="20" height="16" rx="6" fill="${["#e0b43a","#d35f8d","#2a7d9c","#7b5ea7"][(i+2*r)%4]}"/>`).join("")).join("")}<path d="M74 92 V40" stroke="#5b4636" stroke-width="3"/><rect x="74" y="40" width="44" height="28" fill="#e0b43a"/><text x="150" y="250" font-family="Caveat,cursive" font-weight="700" font-size="36" text-anchor="middle" fill="#fff">FINAL</text>`,"#dbeaf7"),
 pic(`<rect y="210" width="300" height="90" fill="#5fae5a"/>${kid(110,110,"#1d2433","#5b4636",1)}<circle cx="126" cy="140" r="6" fill="#c0c7d4"/><rect x="186" y="84" width="28" height="38" rx="3" fill="#f2c94c" transform="rotate(12 200 103)"/><circle cx="222" cy="240" r="16" fill="#fff" stroke="#1d2433" stroke-width="3"/><path d="M140 60 q10 -12 20 0 M150 48 q14 -16 28 0" stroke="#1d2433" stroke-width="3" fill="none" stroke-linecap="round"/>`,"#dbeaf7"),
 pic(`<rect y="150" width="300" height="150" fill="#5fae5a"/>${[...Array(8)].map((_,i)=>`<path d="M${74+i*22} 64v92" stroke="#fff" stroke-opacity=".45" stroke-width="2"/>`).join("")}<path d="M60 160 V60 H240 V160" fill="none" stroke="#fff" stroke-width="8"/>${kid(150,82,"#7cc08a","#3b2a1e",.7)}<ellipse cx="150" cy="242" rx="30" ry="6" fill="#fff" opacity=".7"/><circle cx="150" cy="228" r="13" fill="#fff" stroke="#1d2433" stroke-width="3"/>`,"#dbeaf7"),
 pic(`<rect y="200" width="300" height="100" fill="#5fae5a"/><rect x="40" y="185" width="220" height="14" rx="4" fill="#8d6440"/>${sad7(150,96,"#e0b43a","#7a3b1e",1.1)}<path d="M140 104 q-4 9 0 13 q4 -4 0 -13z" fill="#7cc4f0"/>`,"#e3e8ef"),
 pic(`<rect y="210" width="300" height="90" fill="#5fae5a"/>${[...Array(16)].map((_,i)=>{const x=(i*47)%270+15,y=(i*31)%80+90;return`<rect x="${x}" y="${y}" width="8" height="12" fill="${["#e0b43a","#d35f8d","#2a7d9c","#7cc08a"][i%4]}" transform="rotate(${i*25} ${x+4} ${y+6})"/>`}).join("")}<path d="M74 152 L54 110 M106 152 L126 110 M134 140 L118 98 M166 140 L182 98 M194 152 L174 110 M226 152 L246 110" stroke="#e0b43a" stroke-width="10" stroke-linecap="round"/>${kid(90,135,"#e0b43a","#7a3b1e",.85)}${kid(150,122,"#e0b43a","#3b2a1e",.95)}${kid(210,135,"#e0b43a","#5b4636",.85)}<text x="150" y="62" font-family="Caveat,cursive" font-weight="700" font-size="52" text-anchor="middle" fill="#1d2433">4–3!</text>`,"#dbeaf7"),
 pic(`<rect y="220" width="300" height="80" fill="#5fae5a"/>${kid(70,140,"#e0b43a","#7a3b1e",.8)}${kid(230,140,"#e0b43a","#3b2a1e",.8)}${kid(150,100,"#33415c","#5b4636",1.05)}<path d="M132 18 h36 v14 q0 22 -18 22 q-18 0 -18 -22z" fill="#f2c94c" stroke="#b8860b" stroke-width="2"/><path d="M132 26 q-12 0 -10 10 q2 8 12 6 M168 26 q12 0 10 10 q-2 8 -12 6" stroke="#b8860b" stroke-width="3" fill="none"/><rect x="146" y="54" width="8" height="8" fill="#b8860b"/><rect x="138" y="62" width="24" height="6" fill="#b8860b"/>`,"#dbeaf7")];
const U3={id:"sv7c",year:7,ord:3,title:t3("Finalen","The final","المباراة النهائية"),storyTitle:"Finalen",
 icon:`<svg viewBox="0 0 320 180"><rect width="320" height="180" fill="#dbeaf7"/><rect y="120" width="320" height="60" fill="#5fae5a"/><path d="M30 120 L290 120 L274 40 L46 40Z" fill="#c6cfdc"/>${[0,1].map(r=>[...Array(9)].map((_,i)=>`<circle cx="${70+i*23+r*8}" cy="${62+r*30}" r="9" fill="${["#e0b43a","#d35f8d","#2a7d9c"][(i+r)%3]}"/>`).join("")).join("")}<path d="M140 128 h40 v12 q0 22 -20 22 q-20 0 -20 -22z" fill="#f2c94c" stroke="#b8860b" stroke-width="2"/><rect x="155" y="162" width="10" height="8" fill="#b8860b"/><text x="300" y="172" font-family="Caveat,cursive" font-weight="700" font-size="34" fill="#1f4fb0" text-anchor="end">4–3</text></svg>`,
 pic:pic(""),words:["laktare","domare","straff","waga","besviken","stolt","tvivla","applodera"],terms:["ordklass","substantiv","adjektiv"],
 story:[
  {text:["Äntligen var det dags för finalen mellan Björkskolan och Norrvik. Läktaren var full av föräldrar, lärare och elever från 7B. Amirs mamma satt längst fram med en stor gul flagga.","Amir var nervös igen, men på ett nytt sätt. Nu visste han att laget räknade med honom. Det kändes både läskigt och roligt."],
   pic:PC[0],
   say:t3("Nu är det finalen! Vilket ord i texten betyder platsen där publiken sitter?","It's the final! Which word in the text means the place where the audience sits?","إنها المباراة النهائية! أي كلمة في النص تعني المكان الذي يجلس فيه الجمهور؟")},
  {text:["Domaren blåste i visslan, och matchen började. Motståndarna från Norrvik var snabba och spelade tufft.","Efter tjugo minuter gjorde Sara 1–0 med ett långskott. Folk på läktaren reste sig och började applådera. Men strax före paus kvitterade Norrvik. 1–1."],
   pic:PC[1],
   say:t3("Domaren leder matchen. Vad gör publiken när Sara gör mål?","The referee leads the match. What does the audience do when Sara scores?","الحَكَم يدير المباراة. ماذا يفعل الجمهور عندما تسجّل سارة هدفًا؟")},
  {text:["Andra halvlek blev lång och svår. Inget av lagen gjorde mål, och spelarna blev mer och mer utmattade.","När domaren blåste av, stod det fortfarande 1–1. Nu skulle finalen avgöras med straffsparkar. Fem spelare från varje lag skulle skjuta."],
   pic:PC[2],
   say:t3("Det står fortfarande lika. Hur ska finalen avgöras nu?","It's still a draw. How will the final be decided now?","النتيجة ما زالت متعادلة. كيف ستُحسم المباراة النهائية الآن؟")},
  {text:["Sara sköt först, men målvakten räddade. Hon gick tillbaka med blicken i marken. Hon var så besviken att hon inte kunde säga något.","Sedan gick det fram och tillbaka. Efter nio straffar stod det 3–3. Nu var det Amirs tur. Om han satte sin straff, skulle Björkskolan vinna."],
   pic:PC[3],
   say:t3("Sara missar. Hur visar texten att hon är besviken?","Sara misses. How does the text show that she is disappointed?","سارة تُضيّع ركلتها. كيف يُظهر النص أنها خائبة الأمل؟")},
  {text:["Amir lade bollen på punkten. Plötsligt började han tvivla. Tänk om han missade? Tänk om alla blev arga på honom?","Då hörde han Sara ropa: ”Du klarar det, Amir!” Tränaren nickade lugnt mot honom. Amir tog ett djupt andetag. Han bestämde sig för att våga."],
   pic:PC[2],
   say:t3("”Tänk om …” – Amir tvivlar. Vad får honom att våga ändå?","”What if …” – Amir doubts himself. What makes him dare anyway?","«ماذا لو…» – أمير يشكّ في نفسه. ما الذي يجعله يجرؤ رغم ذلك؟")},
  {text:["Han sprang fram och sköt hårt mot det högra hörnet. Målvakten kastade sig åt fel håll. Mål! 4–3!","Hela laget sprang fram och kramade honom. På läktaren började alla jubla och applådera, och mamma viftade så mycket med flaggan att den nästan gick sönder."],
   pic:PC[4],
   say:t3("Vad händer när Amir skjuter? Hur reagerar folket på läktaren?","What happens when Amir shoots? How do the people in the stands react?","ماذا يحدث عندما يسدّد أمير؟ كيف يتفاعل الناس في المدرّجات؟")},
  {text:["Efter matchen satt Sara tyst på bänken. ”Jag missade”, sa hon. ”Men vi vann tillsammans”, svarade Amir. ”Utan ditt mål hade vi aldrig kommit till straffar.”","Tränaren samlade laget. ”Jag är så stolt över er. Ni gav aldrig upp.” Sara log äntligen. Amir märkte att han inte var nervös längre, bara glad och väldigt trött."],
   pic:PC[5],
   say:t3("Sara missade, men laget vann. Varför säger Amir ”vi vann tillsammans”?","Sara missed, but the team won. Why does Amir say ”we won together”?","أضاعت سارة ركلتها لكن الفريق فاز. لماذا يقول أمير «فزنا معًا»؟")}],
 wordsSay:t3("Nya ord från finalen! Tryck på ett ord för att se vad det betyder, en synonym och ett exempel.","New words from the final! Tap a word to see its meaning, a synonym and an example.","كلمات جديدة من المباراة النهائية! اضغط على كلمة لترى معناها ومرادفها ومثالًا عليها."),
 grammar:[
  {draw:()=>[A.wipe(),A.tx(L(t3("Ordklasser","Word classes","أنواع الكلمات")),400,64,40,"b"),...boxes([["Den",null],["stolta","g","adjektiv"],["tränaren","b","substantiv"],["applåderade","r","verb"]],220,44),...boxes([["Sara","b","substantiv"],["blev","r","verb"],["besviken","g","adjektiv"]],380,44)],
   say:t3("Ord hör till olika ordklasser. Substantiv (blått) är namn på personer, saker och platser. Verb (rött) säger vad någon gör. Adjektiv (grönt) beskriver hur något är.","Words belong to different word classes. Nouns (blue) name people, things and places. Verbs (red) say what someone does. Adjectives (green) describe what something is like.","تنتمي الكلمات إلى أنواع مختلفة. الأسماء (بالأزرق) تسمّي الأشخاص والأشياء والأماكن. الأفعال (بالأحمر) تقول ماذا يفعل شخص ما. الصفات (بالأخضر) تصف كيف يكون الشيء.")},
  {draw:()=>{const X=[150,400,650],C=["b","r","g"];return[A.wipe(),A.tx(L(t3("Testa ordet!","Test the word!","اختبر الكلمة!")),400,64,38,"k"),
    ...["substantiv","verb","adjektiv"].map((s,i)=>qt(s,X[i],120,26,C[i])),...["en / ett …","att …","mycket …"].map((s,i)=>A.tx(s,X[i],195,40,C[i])),A.p(R.line(60,230,740,230,.3),"k",2),
    ...[["en domare","att våga","mycket stolt"],["en läktare","att tvivla","mycket besviken"],["ett mål","att applådera","mycket nervös"]].flatMap((r,j)=>r.map((s,i)=>A.tx(s,X[i],290+j*65,32,C[i])))]},
   say:t3("Kan du sätta en eller ett framför ordet? Då är det ett substantiv. Kan du sätta att framför? Då är det ett verb. Kan du sätta mycket framför? Då är det ett adjektiv.","Can you put en or ett in front of the word? Then it's a noun. Can you put att in front? Then it's a verb. Can you put mycket (very) in front? Then it's an adjective.","هل يمكنك أن تضع en أو ett قبل الكلمة؟ إذن هي اسم. هل يمكنك أن تضع att قبلها؟ إذن هي فعل. هل يمكنك أن تضع mycket (جدًّا) قبلها؟ إذن هي صفة.")},
  {draw:()=>[A.wipe(),A.tx(L(t3("Adjektivet står före substantivet","The adjective comes before the noun","الصفة تأتي قبل الاسم")),400,64,34,"b"),...boxes([["en",null],["stolt","g","adjektiv"],["tränare","b","substantiv"]],200,48),
    A.tx("English: a proud coach  ✓",400,320,34,"k"),A.tx("مدرّب فخور",400,410,44,"o"),qt(L(t3("arabiska: substantivet först","Arabic: the noun first","بالعربية: الاسم أولًا")),400,458,24,"o")],
   say:t3("På svenska står adjektivet före substantivet: en stolt tränare. Det är som på engelska. På arabiska kommer adjektivet efter.","In Swedish the adjective comes before the noun: en stolt tränare. It's like English. In Arabic the adjective comes after.","في السويدية تأتي الصفة قبل الاسم: en stolt tränare، كما في الإنجليزية. أما في العربية فتأتي الصفة بعد الاسم: مدرّب فخور.")}],
 read:[
  {q:"Vem satt längst fram på läktaren med en flagga?",o:["Amirs mamma","Lena","Tränaren"],why:"Del 1: Amirs mamma satt längst fram med en stor gul flagga."},
  {q:"Vem gjorde lagets mål under matchen?",o:["Sara","Amir","Målvakten"],why:"Del 2: Efter tjugo minuter gjorde Sara 1–0."},
  {q:"Hur avgjordes finalen?",o:["Med straffsparkar","Med förlängning","Med lottdragning"],why:"Del 3: finalen skulle avgöras med straffsparkar."},
  {q:"Varför var Sara besviken?",o:["Målvakten räddade hennes straff.","Hon fick inte spela.","Hennes mamma kom inte."],why:"Del 4: Sara sköt först, men målvakten räddade."},
  {q:"Vad tänkte Amir när han lade bollen på punkten?",o:["Tänk om han missade?","Att matchen var tråkig.","Att han var hungrig."],why:"Del 5: Han började tvivla. Tänk om han missade?"},
  {q:"Vad hjälpte Amir att våga skjuta?",o:["Sara och tränaren visade att de trodde på honom.","Domaren sa att han skulle vinna.","Målvakten var skadad."],why:"Del 5: Sara ropade ”Du klarar det!” och tränaren nickade."},
  {q:"Hur slutade straffsparkarna?",o:["4–3 till Björkskolan","3–3","4–3 till Norrvik"],why:"Del 6: Mål! 4–3!"},
  {q:"Varför sa Amir ”vi vann tillsammans” till Sara?",o:["Han ville trösta henne.","Han ville ha mer beröm själv.","Tränaren bad honom säga det."],why:"Sara var ledsen. Utan hennes mål hade laget inte kommit till straffar."},
  {q:"Varför var tränaren stolt över laget?",o:["Laget gav aldrig upp.","Laget vann med 5–0.","Ingen missade en straff."],why:"Del 7: ”Ni gav aldrig upp.”"}],
 gram(lv,write){const tok=pick(WC7).split(" ").map(t=>t.split("/")),plain=tok.map(t=>t[0]).join(" ")+".",[w,c]=pick(tok.filter(t=>t[1]));
  const sol=boxes(tok.map(([x,k])=>[x,k?WCN7[k][1]:null,k?WCN7[k][0]:""]),400,36);
  if(write||lv===2)return{kind:"text",ans:[w,w.toLowerCase()],show:w,q:[A.wipe(),A.tx(L(WCT7[c]),400,80,34,"b"),...svLines(plain,230,44)],sol,hint:{say:WCH7[c],draw:[]}};
  const opts=shuffle(["substantiv","verb","adjektiv"]);
  return{kind:"choice",opts,ans:opts.indexOf(WCN7[c][0]),show:WCN7[c][0],q:[A.wipe(),A.tx(L(t3("Vilken ordklass är ordet?","Which word class is the word?","ما نوع هذه الكلمة؟")),400,80,34,"b"),...svLines(plain,190,40),A.tx(`”${w}”`,400,300,60,"o")],
   sol,hint:{say:t3("Testa: en/ett framför = substantiv, att framför = verb, mycket framför = adjektiv.","Test: en/ett in front = noun, att in front = verb, mycket in front = adjective.","اختبر: en/ett قبلها = اسم، att قبلها = فعل، mycket قبلها = صفة."),draw:[]}}},
 help:[{say:t3("Substantiv: en/ett framför. Verb: att framför. Adjektiv: mycket framför.","Noun: en/ett in front. Verb: att in front. Adjective: mycket in front.","الاسم: نضع قبله en أو ett. الفعل: نضع قبله att. الصفة: نضع قبلها mycket."),draw:()=>[A.tx("en domare",400,160,44,"b"),A.tx("att våga",400,250,44,"r"),A.tx("mycket stolt",400,340,44,"g")]}]};
LESSONS.push(svUnit(U3));

/* ---------------- unit 4: Skollaget i tidningen (substantiv: en/ett, bestämd form, plural) ---------------- */
W("reporter",{sv:"reporter (en)",m:rx("(reporter(n)?|reportrar(na)?)"),d:t3("En person som tar reda på nyheter och berättar om dem i tidningen, på radio eller på tv.","A person who finds out news and reports it in the newspaper, on radio or on TV.","شخص يبحث عن الأخبار وينقلها في الصحيفة أو الإذاعة أو التلفاز."),ex:"Reportern ställde frågor till laget.",tr:{en:"reporter",ar:"مراسل صحفي"},syn:["journalist"],wrong:["domare","rektor"],gap:["En","reporter","från tidningen skrev om matchen."],gapForm:"reporter",form:"en reporter – reportrar"});
W("intervju",{sv:"intervju (en), intervjua",m:rx("intervju(n|er|erna|a|ar|ade|at|ad)?"),d:t3("Ett samtal där någon ställer frågor och en annan svarar, ofta för en tidning.","A conversation where someone asks questions and another person answers, often for a newspaper.","حديث يطرح فيه شخص أسئلة ويجيب آخر، غالبًا من أجل صحيفة."),ex:"Amir gav en intervju till tidningen.",tr:{en:"interview",ar:"مقابلة"},syn:["samtal"],wrong:["tävling","läxa"],gap:["Tidningen gjorde en","intervju","med tränaren efter matchen."],gapForm:"intervju",form:"en intervju – intervjuer · intervjua – intervjuade"});
W("rubrik",{sv:"rubrik (en)",m:rx("rubrik(en|er|erna)?"),d:t3("Den korta texten med stora bokstäver över en artikel.","The short text in big letters above an article.","النص القصير بأحرف كبيرة فوق المقال."),ex:"Rubriken stod på första sidan.",tr:{en:"headline",ar:"عنوان"},syn:["överskrift"],wrong:["bild","sida"],gap:["Amir läste den stora","rubriken","på första sidan."],gapForm:"rubriken",form:"en rubrik – rubriker"});
W("invanare",{sv:"invånare (en)",m:rx("invånar(e|en|na)"),d:t3("En person som bor på en viss plats.","A person who lives in a certain place.","شخص يسكن في مكان معيّن."),ex:"Hagaby har 8 000 invånare.",tr:{en:"inhabitant, resident",ar:"ساكن"},syn:["boende"],opp:["besökare"],wrong:["turist","spelare"],gap:["Många","invånare","i Hagaby kom för att titta."],gapForm:"invånare",form:"en invånare – invånare"});
W("lokal",{sv:"lokal",m:rx("lokal(a|t)?"),d:t3("Som hör till en viss ort eller ett visst område, inte till hela landet.","Belonging to a certain town or area, not to the whole country.","يخصّ بلدة أو منطقة معيّنة، لا البلد كلّه."),ex:"Mamma läser den lokala tidningen.",tr:{en:"local",ar:"محلّي"},syn:["från orten"],opp:["nationell"],wrong:["rolig","snabb"],gap:["Laget var med i den","lokala","tidningen."],gapForm:"lokala",form:"lokal – lokalt – lokala"});
W("enligt",{sv:"enligt",m:rx("enligt"),d:t3("Som någon säger, eller som det står i något.","As someone says, or as it says in something.","حسب ما يقوله شخص ما، أو حسب ما هو مكتوب في شيء ما."),ex:"Enligt domaren var matchen spännande.",tr:{en:"according to",ar:"حسب"},syn:["som någon säger"],wrong:["bakom","utan"],gap:["Det var 300 personer på läktaren,","enligt","tidningen."],gapForm:"enligt",form:"enligt (preposition)"});
W("handelse",{sv:"händelse (en)",m:rx("händelse(n|r|rna)?"),d:t3("Något som händer, ofta något viktigt eller ovanligt.","Something that happens, often something important or unusual.","شيء يحدث، غالبًا يكون مهمًّا أو غير عادي."),ex:"Finalen var veckans stora händelse.",tr:{en:"event",ar:"حَدَث"},syn:["evenemang"],wrong:["fråga","plats"],gap:["Finalen var veckans stora","händelse","i Hagaby."],gapForm:"händelse",form:"en händelse – händelser"});
W("fira",{sv:"fira",m:rx("fira(r|de|t)?"),d:t3("Göra något roligt för att visa att man är glad över något.","Do something fun to show that you are happy about something.","أن تفعل شيئًا ممتعًا لتُظهر أنك سعيد بشيء ما."),ex:"Skolan firar segern med tårta.",tr:{en:"celebrate",ar:"يحتفل"},syn:["ha fest för"],opp:["sörja"],wrong:["städa","träna"],gap:["Hela skolan ska","fira","segern med tårta."],gapForm:"fira",form:"fira – firade – har firat"});
W("enord",{sv:"en-ord",m:rx("en-ord(en|et)?"),d:t3("Ett substantiv som har en framför sig.","A noun that has en in front of it.","اسم تسبقه كلمة en."),ex:"en rubrik, en match",tr:{en:"en-word (common gender)",ar:"اسم من نوع en"}});
W("ettord",{sv:"ett-ord",m:rx("ett-ord(en|et)?"),d:t3("Ett substantiv som har ett framför sig.","A noun that has ett in front of it.","اسم تسبقه كلمة ett."),ex:"ett lag, ett mål",tr:{en:"ett-word (neuter)",ar:"اسم من نوع ett"}});
W("bestamd",{sv:"bestämd form",m:rx("bestämd(a)? form(en)?"),d:t3("Formen för något vi redan vet vilket det är. På svenska blir det en ändelse.","The form for something we already know about. In Swedish it is an ending.","الصيغة لشيء نعرفه مسبقًا. في السويدية تكون نهاية تُضاف إلى الكلمة."),ex:"rubriken, laget",tr:{en:"definite form",ar:"صيغة المعرفة"}});
W("plural",{sv:"plural",m:rx("plural(en|form(en)?)?"),d:t3("Formen för flera av något.","The form for more than one of something.","صيغة الجمع لأكثر من شيء واحد."),ex:"rubriker, lag, flickor",tr:{en:"plural",ar:"الجمع"}});
/* [en/ett, singular, definite, plural, wrong definite, wrong plural] */
const NN7=[["en","rubrik","rubriken","rubriker","rubriket","rubrikar"],["en","reporter","reportern","reportrar","reporteret","reporterer"],["en","händelse","händelsen","händelser","händelset","händelsar"],["en","intervju","intervjun","intervjuer","intervjuet","intervjuor"],
 ["en","tidning","tidningen","tidningar","tidninget","tidninger"],["en","match","matchen","matcher","matchet","matchor"],["en","flicka","flickan","flickor","flickat","flickar"],["en","spelare","spelaren","spelare","spelaret","spelarer"],["en","skola","skolan","skolor","skolat","skolar"],
 ["en","straffspark","straffsparken","straffsparkar","straffsparket","straffsparker"],["ett","lag","laget","lag","lagen","lagor"],["ett","mål","målet","mål","målen","målor"],["ett","foto","fotot","foton","fotoen","fotor"],["ett","ord","ordet","ord","orden","ordar"],["ett","program","programmet","program","programet","programer"],["ett","pris","priset","priser","prisen","prisar"]];
/* write the noun in the right form: [sentence, base, answer, b = definite, p = plural] */
const NF7=[["Björkskolan vann ____ i söndags.","en final","finalen","b"],["Amir läste ____ på första sidan.","en rubrik","rubriken","b"],["Två ____ kom till matchen.","en reporter","reportrar","p"],["Sara har gjort fem ____ i höst.","ett mål","mål","p"],
 ["Hela ____ sjöng på bussen hem.","ett lag","laget","b"],["Många ____ i Hagaby kom och tittade.","en invånare","invånare","p"],["Lena satte upp ____ på väggen.","en artikel","artikeln","b"],["Laget har spelat sex ____ i höst.","en match","matcher","p"],
 ["Reportern ställde många ____ till Amir.","en fråga","frågor","p"],["Amir var nöjd med ____ i tidningen.","en intervju","intervjun","b"],["Alla ____ i laget fick en medalj.","en spelare","spelare","p"],["Mamma har sparat ____ från tidningen.","ett foto","fotot","b"],
 ["Målvakten räddade två ____ i finalen.","en straffspark","straffsparkar","p"],["Under ____ ringde mammas telefon.","en match","matchen","b"],["Det står tre ____ på första sidan.","en rubrik","rubriker","p"]];
const PD=[pic(`<rect width="300" height="200" fill="#f4ead7"/><rect y="200" width="300" height="100" fill="#d9b48a"/><rect x="205" y="28" width="70" height="60" fill="#bfe0f5" stroke="#fff" stroke-width="5"/>${kid(75,105,"#7b5ea7","#5b4636",1)}<g transform="rotate(-6 190 200)"><rect x="128" y="150" width="134" height="92" fill="#fff" stroke="#9aa8c4"/><rect x="138" y="160" width="114" height="14" fill="#1d2433"/><rect x="138" y="182" width="52" height="42" fill="#e0b43a"/><rect x="198" y="184" width="54" height="5" fill="#9aa8c4"/><rect x="198" y="196" width="54" height="5" fill="#9aa8c4"/><rect x="198" y="208" width="40" height="5" fill="#9aa8c4"/></g><path d="M30 238 h30 v24 q-15 8 -30 0z" fill="#fff" stroke="#9aa8c4"/>`),
 pic(`<rect x="40" y="22" width="220" height="256" fill="#fff" stroke="#9aa8c4" stroke-width="2"/><text x="150" y="52" font-family="Georgia,serif" font-weight="700" font-size="20" text-anchor="middle" fill="#1d2433">HAGABY-POSTEN</text><path d="M55 62 h190" stroke="#1d2433" stroke-width="2"/><text x="150" y="90" font-family="Arial,sans-serif" font-weight="800" font-size="18" text-anchor="middle" fill="#c0392b">Björkskolan vann!</text><rect x="58" y="102" width="184" height="92" fill="#cfe3ee"/><rect x="58" y="164" width="184" height="30" fill="#5fae5a"/>${[90,130,170,210].map(x=>`<circle cx="${x}" cy="134" r="11" fill="#f1c7a3"/><rect x="${x-12}" y="146" width="24" height="28" rx="8" fill="#e0b43a"/>`).join("")}${[206,218,230,242,254].map(y=>`<rect x="58" y="${y}" width="${y===254?110:184}" height="5" fill="#c6cfdc"/>`).join("")}`,"#e9eef5"),
 pic(`<rect y="220" width="300" height="80" fill="#5fae5a"/><path d="M30 24 h90 a10 10 0 0 1 10 10 v26 a10 10 0 0 1 -10 10 h-50 l-14 14 v-14 h-26 a10 10 0 0 1 -10 -10 v-26 a10 10 0 0 1 10 -10z" fill="#fff" stroke="#9aa8c4" stroke-width="2"/><text x="75" y="58" font-size="28" text-anchor="middle" font-weight="700" fill="#1f4fb0">?</text>${kid(85,115,"#c0573e","#1d2433",1.05)}${kid(215,128,"#e0b43a","#3b2a1e",.9)}<path d="M106 150 L170 140" stroke="#33415c" stroke-width="5" stroke-linecap="round"/><circle cx="176" cy="139" r="9" fill="#33415c"/><rect x="40" y="150" width="24" height="32" rx="2" fill="#fff" stroke="#9aa8c4"/>`,"#dbeaf7"),
 pic(`${[[20,"#e98a5a"],[110,"#5aa0d8"],[200,"#7cc08a"]].map(([x,c])=>`<rect x="${x}" y="92" width="80" height="80" fill="${c}"/><path d="M${x-6} 94 L${x+40} 56 L${x+86} 94Z" fill="#8d6440"/><rect x="${x+30}" y="132" width="20" height="40" fill="#fff"/>`).join("")}<rect y="172" width="300" height="128" fill="#9fcf8f"/>${kid(150,168,"#7b5ea7","#c6cfdc",.95)}<path d="M176 212 v60" stroke="#8d6440" stroke-width="5" stroke-linecap="round"/>`,"#e3eef8"),
 pic(`<rect y="205" width="300" height="95" fill="#b98757"/><rect x="70" y="140" width="160" height="70" rx="10" fill="#f7d6e0"/><rect x="70" y="140" width="160" height="18" rx="9" fill="#fff"/><rect x="85" y="110" width="130" height="35" rx="8" fill="#f2b8c9"/><path d="M150 110 V52" stroke="#5b4636" stroke-width="3"/><rect x="150" y="52" width="40" height="26" fill="#e0b43a"/><text x="170" y="71" font-size="16" text-anchor="middle" font-weight="700" fill="#1d2433">1</text>${[105,195].map(x=>`<rect x="${x-3}" y="88" width="6" height="22" fill="#5aa0d8"/><path d="M${x} 78 q6 6 0 10 q-6 -4 0 -10z" fill="#e07b00"/>`).join("")}`,"#fdf3e7"),
 pic(`<rect width="300" height="200" fill="#f6e7c8"/><rect y="200" width="300" height="100" fill="#c9a77c"/><g transform="rotate(-3 150 85)"><rect x="95" y="25" width="110" height="122" fill="#fff" stroke="#9aa8c4"/><rect x="105" y="40" width="90" height="10" fill="#1d2433"/><rect x="105" y="58" width="90" height="45" fill="#e0b43a"/>${[112,122,132].map(y=>`<rect x="105" y="${y}" width="90" height="4" fill="#c6cfdc"/>`).join("")}</g><circle cx="150" cy="30" r="5" fill="#d63b2f"/>${kid(55,168,"#4f8a5b","#c9a24a",.95)}${kid(165,195,"#2a7d9c","#3b2a1e",.75)}${kid(240,195,"#d35f8d","#7a3b1e",.75)}`)];
const U4={id:"sv7d",year:7,ord:4,title:t3("Skollaget i tidningen","The school team in the paper","فريق المدرسة في الصحيفة"),storyTitle:"Skollaget i tidningen",
 icon:`<svg viewBox="0 0 320 180"><rect width="320" height="180" fill="#e9eef5"/><g transform="rotate(-4 160 90)"><rect x="70" y="18" width="180" height="150" fill="#fff" stroke="#9aa8c4" stroke-width="2"/><text x="160" y="44" font-family="Georgia,serif" font-weight="700" font-size="16" text-anchor="middle" fill="#1d2433">HAGABY-POSTEN</text><rect x="84" y="54" width="152" height="12" fill="#c0392b"/><rect x="84" y="74" width="74" height="60" fill="#cfe3ee"/><rect x="84" y="114" width="74" height="20" fill="#5fae5a"/><circle cx="108" cy="96" r="8" fill="#f1c7a3"/><circle cx="134" cy="96" r="8" fill="#f1c7a3"/>${[78,90,102,114,126,146,156].map(y=>`<rect x="${y>140?84:166}" y="${y}" width="${y>140?150:70}" height="5" fill="#c6cfdc"/>`).join("")}</g></svg>`,
 pic:pic(""),words:["reporter","intervju","rubrik","invanare","lokal","enligt","handelse","fira"],terms:["enord","ettord","bestamd","plural"],
 story:[
  {text:["På måndagsmorgonen kom Amirs mamma in i köket med den lokala tidningen. ”Titta!” sa hon och pekade. ”Ni är på första sidan!”","Amir läste den stora rubriken: ”Björkskolan vann finalen – efter straffar”. Under rubriken fanns ett foto av hela laget med medaljer runt halsen."],
   pic:PD[0],
   say:t3("Nu läser vi en nyhetsartikel. Rubriken står överst med stora bokstäver.","Now we read a news article. The headline is at the top in big letters.","الآن نقرأ مقالًا إخباريًا. العنوان في الأعلى بأحرف كبيرة.")},
  {text:["HAGABY. I söndags vann Björkskolans fotbollslag finalen i skolserien. Det var första gången på tio år som skolan spelade final. Över 300 personer satt på läktaren.","Enligt domaren var det en av de mest spännande finalerna på länge. Matchen slutade 1–1, och vinnaren fick avgöras med straffsparkar."],
   pic:PD[1],
   say:t3("En nyhet börjar med det viktigaste: vad, var och när. Hitta det i texten.","A news story starts with the most important things: what, where and when. Find them in the text.","يبدأ الخبر بأهم المعلومات: ماذا وأين ومتى. ابحث عنها في النص.")},
  {text:["Den avgörande straffen sköts av Amir, 13 år, som bara har spelat i laget sedan i augusti.","– Precis innan började jag tvivla, men jag ville våga. Mina lagkamrater peppade mig hela tiden, säger Amir i en intervju med tidningen."],
   pic:PD[2],
   say:t3("Tankstrecket (–) visar att någon pratar. Vem pratar här?","The dash (–) shows that someone is speaking. Who is speaking here?","الشَّرطة (–) تدلّ على أن شخصًا يتكلّم. من يتكلّم هنا؟")},
  {text:["– De har tränat i regn och mörker hela hösten. Det här är deras belöning, säger lagets tränare, som är mycket stolt över spelarna.","Sara gjorde lagets enda mål under matchen. Hon berättar att hon var besviken när hon missade sin straff. – Men det viktigaste är att vi vann tillsammans, säger hon."],
   pic:PD[2],
   say:t3("Artikeln låter flera personer komma till tals. Vad säger tränaren och Sara?","The article lets several people have their say. What do the coach and Sara say?","يعطي المقال الكلمة لعدة أشخاص. ماذا يقول المدرّب وسارة؟")},
  {text:["Det var inte bara spelarna som jublade. Många invånare i Hagaby hade kommit för att titta på matchen.","– Alla här har pratat om finalen hela veckan, säger Gun Larsson, 72 år, som bor bredvid skolan. – Det är skönt med en positiv händelse i området."],
   pic:PD[3],
   say:t3("En invånare är någon som bor på en plats. Vad tycker Gun Larsson om finalen?","An inhabitant is someone who lives in a place. What does Gun Larsson think of the final?","الساكن هو من يعيش في مكان ما. ما رأي غون لارشون في المباراة النهائية؟")},
  {text:["I dag ska hela skolan fira segern med tårta i matsalen. Enligt rektorn får laget också åka på ett träningsläger i vår.","Och nästa mål? – Att vinna igen nästa år, säger Amir och skrattar."],
   pic:PD[4],
   say:t3("Slutet på artikeln berättar vad som händer nu. Hur ska skolan fira?","The end of the article tells what happens now. How will the school celebrate?","تخبرنا نهاية المقال بما سيحدث الآن. كيف ستحتفل المدرسة؟")},
  {text:["I klassrummet hade Lena redan satt upp artikeln på väggen. ”Hur kändes det att bli intervjuad av en riktig reporter?” frågade hon.","”Konstigt”, sa Amir. ”Hon skrev ju allt jag sa, till och med att jag tvivlade!” Hela 7B skrattade, och Sara applåderade högst av alla."],
   pic:PD[5],
   say:t3("Tillbaka i klassen. Varför tyckte Amir att det var konstigt att bli intervjuad?","Back in class. Why did Amir think it was strange to be interviewed?","العودة إلى الصف. لماذا وجد أمير أن إجراء مقابلة معه كان أمرًا غريبًا؟")}],
 wordsSay:t3("Nya ord från tidningen. Många av dem är vanliga i nyheter.","New words from the newspaper. Many of them are common in the news.","كلمات جديدة من الصحيفة. كثير منها شائع في الأخبار."),
 grammar:[
  {draw:()=>{const y1=200,y2=330;return[A.wipe(),A.tx(L(t3("en-ord och ett-ord","en-words and ett-words","أسماء en وأسماء ett")),400,60,38,"b"),qt(L(t3("obestämd form","indefinite form","صيغة النكرة")),230,120,24,"k"),qt(L(t3("bestämd form","definite form","صيغة المعرفة")),610,120,24,"k"),
    A.tx("en",195,y1,48,"b","end"),A.tx("rubrik",215,y1,48,"k","start"),A.arrow(390,y1-14,470,y1-14,"k"),A.tx("rubrik",620,y1,48,"k","end"),A.tx("en",620,y1,48,"b","start"),
    A.tx("ett",195,y2,48,"o","end"),A.tx("lag",215,y2,48,"k","start"),A.arrow(390,y2-14,470,y2-14,"k"),A.tx("lag",620,y2,48,"k","end"),A.tx("et",620,y2,48,"o","start"),
    qt("English: the headline",230,440,24,"k"),qt("العربية: العنوان",610,440,26,"k")]},
   say:t3("Substantiv är en-ord eller ett-ord. I bestämd form sätter svenskan ”the” sist, som en ändelse: rubrik + en = rubriken, lag + et = laget.","Nouns are en-words or ett-words. In the definite form Swedish puts ”the” at the end, as an ending: rubrik + en = rubriken, lag + et = laget.","الأسماء إمّا من نوع en أو من نوع ett. في صيغة المعرفة تضع السويدية أداة التعريف في آخر الكلمة: rubrik + en = rubriken، وlag + et = laget. أمّا العربية فتضع «ال» في أوّلها: العنوان.")},
  {draw:()=>{const C=[130,310,490,670],H=["obestämd","bestämd","plural","bestämd plural"],rows=[["en rubrik","rubriken","rubriker","rubrikerna"],["en händelse","händelsen","händelser","händelserna"],["en intervju","intervjun","intervjuer","intervjuerna"],["ett lag","laget","lag","lagen"],["ett mål","målet","mål","målen"]];
    return[A.wipe(),...H.map((s,i)=>qt(s,C[i],80,24,["k","b","o","g"][i])),...rows.flatMap((r,j)=>r.map((s,i)=>A.tx(s,C[i],150+j*68,32,["k","b","o","g"][i]))),A.hl(400,355,180,110)]},
   say:t3("Här är fyra former av samma ord. Titta på ett lag och ett mål: i plural får de ingen ändelse alls. Två lag, två mål.","Here are four forms of the same word. Look at ett lag and ett mål: in the plural they get no ending at all. Två lag, två mål.","هذه أربع صيغ للكلمة نفسها. انظر إلى ett lag وett mål: في الجمع لا تأخذان أي نهاية. Två lag، två mål.")},
  {draw:()=>{const rows=[["-or","en flicka – två flickor"],["-ar","en tidning – två tidningar"],["-er","en rubrik – två rubriker"],["-n","ett foto – två foton"],["–","ett lag – två lag"]];
    return[A.wipe(),A.tx(L(t3("Plural: fem grupper","Plural: five groups","الجمع: خمس مجموعات")),400,60,38,"b"),...rows.flatMap(([e,x],j)=>[A.tx(e,150,140+j*72,44,["r","o","g","b","k"][j]),A.tx(x,480,140+j*72,36,"k")])]},
   say:t3("Plural har olika ändelser: -or, -ar, -er, -n eller ingen ändelse alls. Lär dig ordet tillsammans med sin plural: en reporter – två reportrar.","Plural has different endings: -or, -ar, -er, -n or no ending at all. Learn each word together with its plural: en reporter – två reportrar.","للجمع نهايات مختلفة: ‎-or و‎-ar و‎-er و‎-n أو بلا نهاية. احفظ كل كلمة مع جمعها: en reporter – två reportrar.")}],
 read:[
  {q:"Var stod artikeln om laget?",o:["På första sidan i den lokala tidningen","På sista sidan i en tidning från Stockholm","På skolans hemsida"],why:"Del 1: ”Ni är på första sidan!”"},
  {q:"Hur många personer satt på läktaren, enligt artikeln?",o:["Över 300","Ungefär 30","Över 3 000"],why:"Del 2: Över 300 personer satt på läktaren."},
  {q:"Vem tyckte att det var en av de mest spännande finalerna på länge?",o:["Domaren","Amirs mamma","Rektorn"],why:"Del 2: Enligt domaren …"},
  {q:"Hur länge har Amir spelat i laget?",o:["Sedan i augusti","I tio år","Sedan förra året"],why:"Del 3: sedan i augusti."},
  {q:"Vad visar tankstrecket (–) i artikeln?",o:["Att någon börjar prata.","Att en mening är slut.","Att det kommer en fråga."],why:"I tidningar visar – att någon säger något (ett citat)."},
  {q:"Vem är Gun Larsson?",o:["En invånare som bor bredvid skolan","Lagets tränare","En reporter"],why:"Del 5: som bor bredvid skolan."},
  {q:"Hur ska skolan fira segern?",o:["Med tårta i matsalen","Med en resa till Stockholm","Med en ny match"],why:"Del 6: fira segern med tårta i matsalen."},
  {q:"Varför säger Gun Larsson att det är skönt med en positiv händelse?",o:["Det händer inte så ofta något glatt i området.","Hon vann pengar på matchen.","Hon är tränarens mamma."],why:"Alla har pratat om finalen. En glad nyhet är något extra för området."},
  {q:"Varför tyckte Amir att intervjun var konstig?",o:["Reportern skrev allt, även att han hade tvivlat.","Reportern skrev fel namn på honom.","Ingen läste artikeln."],why:"Del 7: ”Hon skrev ju allt jag sa, till och med att jag tvivlade!”"}],
 gram(lv,write){
  if(write||lv===2){const [s,base,ans,f]=pick(NF7);
   return{kind:"text",ans:[ans],show:ans,q:[A.wipe(),A.tx(L(t3("Skriv ordet i rätt form","Write the word in the right form","اكتب الكلمة بالصيغة الصحيحة")),400,70,34,"b"),...svLines(s,200,40),A.tx(`(${base})`,400,320,38,"o")],
    sol:svLines(s.replace("____",ans),410,34,"g"),hint:{say:f==="b"?t3("Vi vet vilken det är: bestämd form, -en eller -et.","We know which one: definite form, -en or -et.","نعرف أيّ واحد هو: صيغة المعرفة، ‎-en أو ‎-et."):t3("Det är flera: vilken plural har ordet?","There are several: what is the word's plural?","هناك أكثر من واحد: ما جمع هذه الكلمة؟"),draw:[]}}}
  const [art,sg,def,pl,wd,wp]=pick(NN7),plq=lv>0&&Math.random()<.6,right=plq?pl:def,opts=shuffle(plq?[pl,wp,def]:[def,wd,pl]);
  return{kind:"choice",opts,ans:opts.indexOf(right),show:right,q:[A.wipe(),A.tx(L(plq?t3("Vad heter ordet i plural?","What is the word in the plural?","ما جمع هذه الكلمة؟"):t3("Vad heter ordet i bestämd form?","What is the word in the definite form?","ما صيغة المعرفة لهذه الكلمة؟")),400,80,34,"b"),A.tx(plq?`${art} ${sg} → två …`:`${art} ${sg} → …`,400,230,56,art==="en"?"b":"o")],
   sol:[A.tx(`${art} ${sg} – ${def} – ${pl}`,400,420,38,"g")],hint:{say:plq?t3("Plural kan sluta på -or, -ar, -er, -n eller inget alls.","The plural can end in -or, -ar, -er, -n or nothing at all.","قد ينتهي الجمع بـ ‎-or أو ‎-ar أو ‎-er أو ‎-n أو بلا نهاية."):t3("En-ord får -en (eller -n). Ett-ord får -et (eller -t).","En-words get -en (or -n). Ett-words get -et (or -t).","أسماء en تأخذ ‎-en (أو ‎-n)، وأسماء ett تأخذ ‎-et (أو ‎-t)."),draw:[]}}},
 help:[{say:t3("En-ord: rubrik → rubriken. Ett-ord: lag → laget. Plural: rubriker, lag.","En-words: rubrik → rubriken. Ett-words: lag → laget. Plural: rubriker, lag.","أسماء en: ‏rubrik ← rubriken. أسماء ett: ‏lag ← laget. الجمع: rubriker، lag."),draw:()=>[A.tx("en rubrik → rubriken",400,170,42,"b"),A.tx("ett lag → laget",400,260,42,"o"),A.tx("två rubriker · två lag",400,350,42,"g")]}]};
LESSONS.push(svUnit(U4));

/* ---------------- unit 5: Mobilen som försvann (adjektivets böjning) ---------------- */
W("misstanka",{sv:"misstänka",m:rx("misstänk(a|er|te|t|ta)"),d:t3("Tro att någon har gjort något fel, utan att veta säkert.","Believe that someone did something wrong, without knowing for sure.","أن تظنّ أن شخصًا ما فعل شيئًا خاطئًا دون أن تكون متأكدًا."),ex:"Ingen ska misstänka någon utan bevis.",tr:{en:"suspect",ar:"يشتبه في"},syn:["ana"],opp:["lita på"],wrong:["hjälpa","glömma"],gap:["Lena sa att ingen fick","misstänka","någon förrän de visste mer."],gapForm:"misstänka",form:"misstänka – misstänkte – har misstänkt"});
W("ledtrad",{sv:"ledtråd (en)",m:rx("ledtråd(en|ar|arna)?"),d:t3("Något som hjälper en att lösa en gåta eller ett mysterium.","Something that helps you solve a riddle or a mystery.","شيء يساعدك على حلّ لغز."),ex:"Den gula plastbiten var en ledtråd.",tr:{en:"clue",ar:"قرينة"},syn:["spår","tips"],wrong:["larm","skåp"],gap:["Sara letade efter","ledtrådar","under bänkarna."],gapForm:"ledtrådar",form:"en ledtråd – ledtrådar"});
W("bevis",{sv:"bevis (ett)",m:rx("bevis(et|en|a|ar|ade)?"),d:t3("Något som visar säkert att något är sant.","Something that shows for certain that something is true.","شيء يُثبت بشكل أكيد أن أمرًا ما صحيح."),ex:"Larmet var ett bevis.",tr:{en:"proof, evidence",ar:"دليل"},syn:["belägg"],opp:["gissning"],wrong:["väska","rast"],gap:["Det ringande larmet var ett","bevis","på att Elias hade mobilen."],gapForm:"bevis",form:"ett bevis – bevis"});
W("skylla",{sv:"skylla på",m:rx("skyll(a|er|de|t)( på)?"),d:t3("Säga att någon annan har gjort något dåligt.","Say that someone else did something bad.","أن تقول إن شخصًا آخر هو من فعل شيئًا سيئًا."),ex:"Elias skyllde på Amir.",tr:{en:"blame",ar:"يلوم"},syn:["anklaga"],wrong:["hjälpa","fråga"],gap:["Elias","skyllde","på Amir fast Amir var oskyldig."],gapForm:"skyllde",form:"skylla – skyllde – har skyllt"});
W("arlig",{sv:"ärlig",m:rx("ärlig(t|a)?"),d:t3("Som säger sanningen och inte lurar någon.","Who tells the truth and doesn't trick anyone.","من يقول الحقيقة ولا يخدع أحدًا."),ex:"Till slut var Elias ärlig.",tr:{en:"honest",ar:"صادق"},syn:["uppriktig"],opp:["oärlig"],wrong:["arg","snabb"],gap:["Det är bra att du är","ärlig","nu."],gapForm:"ärlig",form:"ärlig – ärligt – ärliga"});
W("avsloja",{sv:"avslöja",m:rx("avslöja(r|de|t|s)?"),d:t3("Visa något som var hemligt, eller visa vem som har gjort något.","Show something that was secret, or show who did something.","أن تكشف شيئًا كان سرًّا، أو تكشف من فعل شيئًا ما."),ex:"Larmet avslöjade Elias.",tr:{en:"reveal, give away",ar:"يكشف"},syn:["röja"],wrong:["bära","måla"],gap:["Larmet","avslöjade","var mobilen fanns."],gapForm:"avslöjade",form:"avslöja – avslöjade – har avslöjat"});
W("gomma",{sv:"gömma",m:rx("göm(ma|mer|de|t|d|da)"),d:t3("Lägga något där ingen kan se eller hitta det.","Put something where nobody can see or find it.","أن تضع شيئًا حيث لا يراه أو يجده أحد."),ex:"Han gömde mobilen i ryggsäcken.",tr:{en:"hide",ar:"يُخفي"},syn:["dölja"],wrong:["sälja","laga"],gap:["Elias ville bara","gömma","mobilen en stund."],gapForm:"gömma",form:"gömma – gömde – har gömt"});
W("upprord",{sv:"upprörd",m:rx("(upprörd(a)?|upprört)"),d:t3("Arg och ledsen på samma gång, ofta för att något är orättvist.","Angry and upset at the same time, often because something is unfair.","غاضب وحزين في الوقت نفسه، غالبًا لأن شيئًا ما غير عادل."),ex:"Amir blev upprörd.",tr:{en:"upset",ar:"مستاء"},syn:["arg"],opp:["lugn"],wrong:["mätt","pigg"],gap:["Amir blev","upprörd","när Elias skyllde på honom."],gapForm:"upprörd",form:"upprörd – upprört – upprörda"});
W("kongruens",{sv:"kongruens",m:rx("kongruens(en)?"),d:t3("Att orden i en fras passar ihop i form.","That the words in a phrase match each other in form.","أن تتطابق الكلمات في العبارة في صيغتها."),ex:"ett rött skal, röda mobiler",tr:{en:"agreement",ar:"المطابقة"}});
W("bojning",{sv:"böjning",m:rx("böjning(en|ar|arna)?"),d:t3("Hur ett ord ändrar form.","How a word changes its form.","كيف تتغيّر صيغة الكلمة."),ex:"röd – rött – röda",tr:{en:"inflection",ar:"التصريف"}});
/* nouns [en/ett, singular, definite, plural, definite plural]; adjectives [en-form, ett-form, a-form] */
const NT7=[["en","mobil","mobilen","mobiler","mobilerna"],["en","väska","väskan","väskor","väskorna"],["ett","skal","skalet","skal","skalen"],["ett","skåp","skåpet","skåp","skåpen"],["en","låda","lådan","lådor","lådorna"],["en","ryggsäck","ryggsäcken","ryggsäckar","ryggsäckarna"],["ett","paraply","paraplyet","paraplyer","paraplyerna"],["en","jacka","jackan","jackor","jackorna"]];
const NP7=[["en","elev","eleven","elever","eleverna"],["ett","barn","barnet","barn","barnen"],["en","tränare","tränaren","tränare","tränarna"],["en","flicka","flickan","flickor","flickorna"],["en","pojke","pojken","pojkar","pojkarna"],["ett","lag","laget","lag","lagen"]];
const AT7=[["röd","rött","röda"],["grön","grönt","gröna"],["gul","gult","gula"],["stor","stort","stora"],["ny","nytt","nya"],["gammal","gammalt","gamla"],["smutsig","smutsigt","smutsiga"],["blöt","blött","blöta"]];
const AP7=[["glad","glatt","glada"],["ärlig","ärligt","ärliga"],["upprörd","upprört","upprörda"],["besviken","besviket","besvikna"],["snäll","snällt","snälla"],["arg","argt","arga"],["nervös","nervöst","nervösa"]];
const AKH7=[t3("En-ord: adjektivet får ingen ändelse.","En-word: the adjective gets no ending.","اسم من نوع en: لا تأخذ الصفة أي نهاية."),t3("Ett-ord: adjektivet får -t.","Ett-word: the adjective gets -t.","اسم من نوع ett: تأخذ الصفة ‎-t."),t3("Plural: adjektivet får -a.","Plural: the adjective gets -a.","الجمع: تأخذ الصفة ‎-a."),t3("Efter den, det och de får adjektivet alltid -a.","After den, det and de the adjective always gets -a.","بعد den وdet وde تأخذ الصفة دائمًا ‎-a.")];
const PE=[pic(`<rect x="120" y="212" width="170" height="16" fill="#b98757"/><rect x="132" y="228" width="12" height="60" fill="#8d6440"/><rect x="266" y="228" width="12" height="60" fill="#8d6440"/>${[0,1,2].map(i=>`<rect x="${156+i*30}" y="${148+(i%2)*6}" width="18" height="30" rx="3" fill="${["#1d2433","#7b5ea7","#c6cfdc"][i]}"/>`).join("")}<rect x="140" y="166" width="130" height="48" rx="4" fill="#4d7fe0"/><rect x="236" y="112" width="26" height="44" rx="4" fill="none" stroke="#d63b2f" stroke-width="3" stroke-dasharray="6 5"/><text x="249" y="142" font-size="22" font-weight="700" text-anchor="middle" fill="#d63b2f">?</text>${kid(65,130,"#d35f8d","#7a3b1e",.9)}<text x="65" y="80" font-size="44" font-weight="700" text-anchor="middle" fill="#d63b2f">!</text>`,"#f6efe2"),
 pic(`<rect y="232" width="300" height="68" fill="#c9a77c"/>${kid(80,122,"#e98a5a","#d9b25a",.95)}<path d="M100 150 L158 136" stroke="#e98a5a" stroke-width="10" stroke-linecap="round"/>${sad7(222,122,"#2a7d9c","#3b2a1e",.95)}<path d="M202 84 l-8 -14 M222 78 v-16 M242 84 l8 -14" stroke="#d63b2f" stroke-width="4" stroke-linecap="round"/>`,"#f6efe2"),
 pic(`<rect x="20" y="28" width="260" height="96" rx="4" fill="#2f4a3a"/><text x="150" y="88" font-family="Caveat,cursive" font-size="34" text-anchor="middle" fill="#fff">Lugn – vi letar!</text>${kid(150,150,"#4f8a5b","#c9a24a",.95)}<path d="M172 172 L196 136" stroke="#4f8a5b" stroke-width="10" stroke-linecap="round"/>`,"#f6efe2"),
 pic(`<rect y="200" width="300" height="100" fill="#c9a77c"/><rect x="30" y="140" width="200" height="14" fill="#8d6440"/><rect x="45" y="154" width="10" height="56" fill="#6b4b2f"/><rect x="205" y="154" width="10" height="56" fill="#6b4b2f"/><path d="M122 236 l14 -6 l6 10 l-12 6z" fill="#f2c94c" stroke="#b8860b"/><circle cx="134" cy="232" r="34" fill="#fff" fill-opacity=".35" stroke="#33415c" stroke-width="7"/><path d="M158 256 l36 30" stroke="#33415c" stroke-width="12" stroke-linecap="round"/>${kid(255,105,"#d35f8d","#7a3b1e",.8)}`,"#f6efe2"),
 pic(`<circle cx="85" cy="95" r="58" fill="#fff" stroke="#33415c" stroke-width="6"/>${[...Array(12)].map((_,i)=>{const a=i*Math.PI/6;return`<path d="M${85+Math.sin(a)*48} ${95-Math.cos(a)*48} L${85+Math.sin(a)*54} ${95-Math.cos(a)*54}" stroke="#33415c" stroke-width="3"/>`}).join("")}<path d="M85 95 L82 62" stroke="#1d2433" stroke-width="6" stroke-linecap="round"/><path d="M85 95 L80 47" stroke="#1d2433" stroke-width="4" stroke-linecap="round"/><text x="85" y="185" font-size="26" font-weight="700" text-anchor="middle" fill="#1d2433">11.59</text><rect x="165" y="150" width="96" height="114" rx="24" fill="#4f9a5a"/><rect x="180" y="200" width="66" height="44" rx="8" fill="#3d7d47"/><path d="M188 152 q25 -38 50 0" stroke="#3d7d47" stroke-width="8" fill="none"/><text x="190" y="118" font-size="32" fill="#1f4fb0">♪</text><text x="232" y="98" font-size="36" fill="#1f4fb0">♫</text><path d="M272 170 q12 18 0 36 M284 160 q20 28 0 56" stroke="#1f4fb0" stroke-width="3" fill="none" stroke-linecap="round"/>`,"#f6efe2"),
 pic(`<rect y="232" width="300" height="68" fill="#c9a77c"/>${kid(70,125,"#e98a5a","#d9b25a",.9)}<rect x="94" y="136" width="22" height="36" rx="4" fill="#f2c94c"/><rect x="98" y="140" width="14" height="28" rx="2" fill="#d63b2f"/>${kid(160,125,"#d35f8d","#7a3b1e",.9)}${kid(240,125,"#2a7d9c","#3b2a1e",.9)}<text x="70" y="70" font-family="Caveat,cursive" font-size="32" font-weight="700" text-anchor="middle" fill="#1d2433">Förlåt …</text>`,"#f6efe2")];
const U5={id:"sv7e",year:7,ord:5,title:t3("Mobilen som försvann","The phone that disappeared","الهاتف الذي اختفى"),storyTitle:"Mobilen som försvann",
 icon:`<svg viewBox="0 0 320 180"><rect width="320" height="180" fill="#f6efe2"/><rect x="96" y="40" width="54" height="96" rx="9" fill="#f2c94c"/><rect x="104" y="48" width="38" height="80" rx="5" fill="#d63b2f"/><text x="123" y="102" font-size="36" font-weight="700" text-anchor="middle" fill="#fff">?</text><circle cx="200" cy="96" r="40" fill="#fff" fill-opacity=".4" stroke="#33415c" stroke-width="8"/><path d="M228 124 l34 30" stroke="#33415c" stroke-width="13" stroke-linecap="round"/></svg>`,
 pic:pic(""),words:["misstanka","ledtrad","bevis","skylla","arlig","avsloja","gomma","upprord"],terms:["kongruens","bojning","adjektiv"],
 story:[
  {text:["Under lektionerna låg alla mobiler i en blå låda på Lenas kateder. När det ringde ut, gick eleverna i 7B fram för att hämta sina telefoner.","Sara letade och letade. Den röda mobilen med det gula skalet fanns inte i lådan. ”Min mobil är borta!” sa hon. Hela klassen blev tyst. Vem skulle vilja gömma någon annans mobil?"],
   pic:PE[0],
   say:t3("En mysteriehistoria! Läs noga – små detaljer kan bli viktiga.","A mystery story! Read carefully – small details can become important.","قصة لغز! اقرأ بانتباه، فالتفاصيل الصغيرة قد تصبح مهمّة.")},
  {text:["”Amir satt närmast lådan”, sa Elias snabbt. ”Och han gick fram först.” Några klasskamrater vände sig om och tittade på Amir.","”Varför skulle jag ta den?” sa Amir. Han var upprörd, och rösten darrade. ”Man kan inte skylla på någon bara för att han sitter nära.”"],
   pic:PE[1],
   say:t3("Elias skyller på Amir. Har han något bevis?","Elias blames Amir. Does he have any proof?","إلياس يُلقي اللوم على أمير. هل لديه أي دليل؟")},
  {text:["Lena höjde handen. ”Ingen ska misstänka någon förrän vi vet mer”, sa hon lugnt. ”Nu letar vi tillsammans, försiktigt och utan att bråka.”","Sara trodde inte att Amir hade gjort det. Han var hennes lagkamrat, och han hade vågat skjuta den sista straffen i finalen. Han var ärlig, det visste hon."],
   pic:PE[2],
   say:t3("Vad vill Lena att klassen ska göra? Och vad tror Sara om Amir?","What does Lena want the class to do? And what does Sara think about Amir?","ماذا تريد لينا أن يفعل الصف؟ وماذا تظنّ سارة بأمير؟")},
  {text:["Hon började leta efter ledtrådar. Under en bänk längst bak låg en liten gul bit av plast. Den kom från hennes skal!","Bänken stod vid fönstret, långt från Amirs plats. Där brukade Elias sitta. Men en plastbit var inget bevis. Sara behövde något mer."],
   pic:PE[3],
   say:t3("Sara hittar en ledtråd. Varför är det viktigt var bänken står?","Sara finds a clue. Why does it matter where the bench is?","سارة تجد قرينة. لماذا يهمّ مكان المقعد؟")},
  {text:["Då kom hon på en sak. Varje dag klockan tolv ringde hennes larm, så att hon kom ihåg att äta före träningen. Hon tittade på klockan: 11.59.","”Var tysta en stund!” sa hon. Alla väntade. Plötsligt hördes en glad melodi – inifrån Elias gröna ryggsäck."],
   pic:PE[4],
   say:t3("Klockan är en minut i tolv. Vad tror du händer klockan tolv?","It is one minute to twelve. What do you think happens at twelve?","الساعة الثانية عشرة إلا دقيقة. ماذا تتوقّع أن يحدث عند الثانية عشرة؟")},
  {text:["Elias blev röd i ansiktet. Larmet hade avslöjat honom. Långsamt tog han fram mobilen ur ryggsäcken.","”Förlåt”, sa han tyst. ”Jag ville bara gömma den en stund, som ett skämt. Men sedan blev alla så arga, och då vågade jag inte säga något.”"],
   pic:PE[5],
   say:t3("Larmet avslöjar Elias. Varför sa han ingenting först?","The alarm gives Elias away. Why didn't he say anything at first?","المنبّه يكشف إلياس. لماذا لم يقل شيئًا في البداية؟")},
  {text:["Lena bad Elias att säga förlåt till Amir också. ”Det är bra att du är ärlig nu”, sa hon. ”Men man skyller aldrig på en klasskamrat.”","Amir var lättad. Sara gav honom en high five. ”Du är en riktig detektiv”, sa han. ”Nej”, skrattade hon. ”Jag har bara ett väldigt högt larm.”"],
   pic:PE[5],
   say:t3("Hur slutar historien? Vad lär sig klassen?","How does the story end? What does the class learn?","كيف تنتهي القصة؟ وماذا يتعلّم الصف؟")}],
 wordsSay:t3("Nya ord för en mysteriehistoria. Tryck på dem och lär dig vad de betyder.","New words for a mystery story. Tap them and learn what they mean.","كلمات جديدة لقصة لغز. اضغط عليها وتعلّم معانيها."),
 grammar:[
  {draw:()=>[A.wipe(),A.tx(L(t3("Adjektivet ändrar form","The adjective changes form","الصفة تتغيّر صيغتها")),400,58,38,"b"),...boxes([["en",null],["röd","b","en-ord: röd"],["mobil",null]],165,44),...boxes([["ett",null],["rött","o","ett-ord: + t"],["skal",null]],295,44),...boxes([["två",null],["röda","g","plural: + a"],["mobiler",null]],425,44)],
   say:t3("Adjektivet passar ihop med substantivet. En-ord: en röd mobil. Ett-ord: ett rött skal, med -t. Plural: röda mobiler, med -a.","The adjective matches the noun. En-word: en röd mobil. Ett-word: ett rött skal, with -t. Plural: röda mobiler, with -a.","الصفة تتطابق مع الاسم. اسم en: ‏en röd mobil. اسم ett: ‏ett rött skal مع ‎-t. الجمع: röda mobiler مع ‎-a.")},
  {draw:()=>[A.wipe(),A.tx(L(t3("den / det / de + adjektiv med -a","den / det / de + adjective with -a","den / det / de + صفة تنتهي بـ ‎-a")),400,58,34,"b"),...boxes([["den","b"],["röda","g","+ a"],["mobilen",null]],165,44),...boxes([["det","o"],["gula","g","+ a"],["skalet",null]],295,44),...boxes([["Elias",null],["gröna","g","+ a"],["ryggsäck",null]],425,44)],
   say:t3("I bestämd form får adjektivet alltid -a: den röda mobilen, det gula skalet. Efter ett namn med genitiv också: Elias gröna ryggsäck.","In the definite form the adjective always gets -a: den röda mobilen, det gula skalet. Also after a possessive name: Elias gröna ryggsäck.","في صيغة المعرفة تأخذ الصفة دائمًا ‎-a: ‏den röda mobilen، ‏det gula skalet. وكذلك بعد اسم المالك: Elias gröna ryggsäck.")},
  {draw:()=>[A.wipe(),A.tx(L(t3("Tre språk","Three languages","ثلاث لغات")),400,58,38,"b"),A.tx("ett rött skal · röda mobiler",400,150,40,"g"),A.tx("a red case · red phones",400,250,36,"k"),qt(L(t3("engelska: red ändras aldrig","English: red never changes","الإنجليزية: red لا تتغيّر أبدًا")),400,292,24,"k"),
    A.tx("هاتف أحمر · حقيبة حمراء",400,380,40,"o"),qt(L(t3("arabiska: adjektivet efter, men det ändras också","Arabic: the adjective after, but it changes too","العربية: الصفة بعد الاسم، لكنها تتغيّر أيضًا")),400,428,24,"o")],
   say:t3("På engelska ändras adjektivet aldrig. På arabiska ändras det, som på svenska, men det står efter substantivet. På svenska står det före.","In English the adjective never changes. In Arabic it changes, like in Swedish, but it comes after the noun. In Swedish it comes before.","في الإنجليزية لا تتغيّر الصفة أبدًا. في العربية تتغيّر كما في السويدية، لكنها تأتي بعد الاسم: هاتف أحمر، حقيبة حمراء. أمّا في السويدية فتأتي قبل الاسم.")}],
 read:[
  {q:"Var låg mobilerna under lektionerna?",o:["I en blå låda på Lenas kateder","I elevernas väskor","I Lenas jackficka"],why:"Del 1: i en blå låda på Lenas kateder."},
  {q:"Hur såg Saras mobil ut?",o:["Den var röd och hade ett gult skal.","Den var svart och hade ett rött skal.","Den var blå och hade inget skal."],why:"Del 1: Den röda mobilen med det gula skalet."},
  {q:"Vad menar Lena med ”Ingen ska misstänka någon förrän vi vet mer”?",o:["Man ska inte tro att någon är skyldig utan att veta mer.","Alla ska gå hem nu.","Hon vet redan vem som tog mobilen."],why:"Del 3: Först måste man veta mer."},
  {q:"Varför trodde Sara på Amir?",o:["Hon kände honom och visste att han var ärlig.","Hon hade sett vem som tog mobilen.","Lena sa att Amir var oskyldig."],why:"Del 3: Han var ärlig, det visste hon."},
  {q:"Vilken ledtråd hittade Sara under bänken?",o:["En gul bit plast från hennes skal","En nyckel","En lapp med Elias namn"],why:"Del 4: en liten gul bit av plast."},
  {q:"Hur avslöjades Elias?",o:["Mobilens larm ringde i hans ryggsäck.","Lena såg honom på en film.","Amir såg när han tog mobilen."],why:"Del 5: en glad melodi inifrån Elias gröna ryggsäck."},
  {q:"Varför skyllde Elias på Amir, tror du?",o:["Han ville inte själv bli misstänkt.","Han trodde verkligen att Amir tog den.","Han ville hjälpa Sara att leta."],why:"Elias hade gömt mobilen. Han skyllde på någon annan för att ingen skulle misstänka honom."},
  {q:"Vad menar Sara med ”Jag har bara ett väldigt högt larm”?",o:["Det var larmet som löste mysteriet, inte hon.","Hon vill köpa ett nytt larm.","Hon är arg på Amir."],why:"Hon skämtar: hon tycker inte att hon är någon detektiv."},
  {q:"Hur kände sig Amir i slutet?",o:["Lättad","Upprörd","Besviken"],why:"Del 7: Amir var lättad."}],
 gram(lv,write){const people=Math.random()<.45,n=pick(people?NP7:NT7),a=pick(people?AP7:AT7),[art,sg,def,pl,dpl]=n;
  const k=lv===0?pick([art==="en"?0:1,2]):pick([art==="en"?0:1,2,3,3]),pre=k===0||k===1?art:k===2?"två":art==="en"?"den":"det",noun=k<2?sg:k===2?pl:def;
  /* definite plural sometimes: de + -a + nouns */
  const dp=k===3&&Math.random()<.35,pre2=dp?"de":pre,noun2=dp?dpl:noun,right=k===0?a[0]:k===1?a[1]:a[2],ph=`${pre2} ____ ${noun2}`,done=`${pre2} ${right} ${noun2}`,h=AKH7[Math.min(k,3)];
  const head=[A.wipe(),A.tx(L(t3("Skriv adjektivet i rätt form","Write the adjective in the right form","اكتب الصفة بالصيغة الصحيحة")),400,80,34,"b"),A.tx(ph,400,220,56,"k"),A.tx(`(${a[0]})`,400,320,40,"o")];
  if(write||lv===2)return{kind:"text",ans:[right],show:right,q:head,sol:[A.tx(done,400,420,44,"g")],hint:{say:h,draw:[]}};
  const opts=shuffle([...a]);
  return{kind:"choice",opts,ans:opts.indexOf(right),show:right,q:[head[0],A.tx(L(t3("Välj rätt form av adjektivet","Choose the right form of the adjective","اختر الصيغة الصحيحة للصفة")),400,80,34,"b"),head[2],head[3]],sol:[A.tx(done,400,420,44,"g")],hint:{say:h,draw:[]}}},
 help:[{say:t3("en röd mobil · ett rött skal · röda mobiler · den röda mobilen","en röd mobil (en-word) · ett rött skal (ett-word, +t) · röda mobiler (plural, +a) · den röda mobilen (+a)","en röd mobil (اسم en) · ett rött skal (اسم ett، ‎+t) · röda mobiler (جمع، ‎+a) · den röda mobilen (‎+a)"),draw:()=>[A.tx("en röd mobil",400,130,40,"b"),A.tx("ett rött skal",400,210,40,"o"),A.tx("röda mobiler",400,290,40,"g"),A.tx("den röda mobilen",400,370,40,"g")]}]};
LESSONS.push(svUnit(U5));
}
