/* Svenska årskurs 7, units 6–8: a class debate (bindeord), a recipe with a story frame (imperativ, ordningsord)
   and an adventure in the mountains (sammansatta ord). Amir, Sara, 7B, Lena and the coach continue. */
{const {rx,boxes,pic,kid,W,sent,cap}=SVH;
const AMIR=["#2a7d9c","#3b2a1e"],SARA=["#d35f8d","#7a3b1e"];

/* ---------------- unit 6: Mobilfri skola? (bindeord) ---------------- */
W("asikt",{sv:"åsikt (en)",m:rx("åsikt(en|er|erna)?"),d:t3("Det man tycker om något.","What you think about something.","ما تراه في أمر ما."),ex:"Alla hade en åsikt om mobilerna.",tr:{en:"opinion",ar:"رأي"},syn:["uppfattning","tycke"],wrong:["fråga","regel"],gap:["Alla i klassen hade en","åsikt","om mobilerna."],gapForm:"åsikt",form:"en åsikt – åsikter"});
W("argument",{sv:"argument (ett)",m:rx("argument(et|en)?"),d:t3("Ett skäl som visar varför man tycker något.","A reason that shows why you think something.","سبب يبيّن لماذا ترى ما تراه."),ex:"Mitt första argument är enkelt.",tr:{en:"argument, reason",ar:"حُجّة"},syn:["skäl"],wrong:["känsla","rubrik"],gap:["Sara hade ett starkt","argument","för en mobilfri skola."],gapForm:"argument",form:"ett argument – argument"});
W("fordel",{sv:"fördel (en)",m:rx("fördel(en|ar|arna)?"),d:t3("Något som är bra med en sak.","Something good about a thing.","شيء جيّد في أمر ما."),ex:"En fördel är att vi pratar mer med varandra.",tr:{en:"advantage",ar:"ميزة"},syn:["plus","bra sida"],opp:["nackdel"],wrong:["regel","fråga"],gap:["En stor","fördel","med mobilfri skola är att vi pratar mer."],gapForm:"fördel",form:"en fördel – fördelar"});
W("nackdel",{sv:"nackdel (en)",m:rx("nackdel(en|ar|arna)?"),d:t3("Något som är dåligt med en sak.","Something bad about a thing.","شيء سيّئ في أمر ما."),ex:"Det finns också en stor nackdel.",tr:{en:"disadvantage",ar:"عَيب، سلبيّة"},syn:["minus","dålig sida"],opp:["fördel"],wrong:["fråga","regel"],gap:["En","nackdel","med mobiler är att de stör på lektionen."],gapForm:"nackdel",form:"en nackdel – nackdelar"});
W("pasta",{sv:"påstå",m:rx("påst(å|år|od|ått)"),d:t3("Säga att något är sant, utan att visa att det är så.","Say that something is true, without showing that it is.","أن تقول إن شيئًا صحيح دون أن تُثبت ذلك."),ex:"Ni kan påstå att mobilen bara stör.",tr:{en:"claim",ar:"يدّعي"},syn:["hävda"],wrong:["fråga","glömma"],gap:["Man kan inte bara","påstå","något – man måste visa varför."],gapForm:"påstå",form:"påstå – påstod – har påstått"});
W("overtyga",{sv:"övertyga",m:rx("övertyga(r|de|t|nde)?"),d:t3("Få någon att tro på det man säger.","Make someone believe what you say.","أن تجعل شخصًا يقتنع بما تقول."),ex:"Hon försökte övertyga klassen.",tr:{en:"convince",ar:"يُقنِع"},syn:["få någon att tro"],wrong:["skrämma","glömma"],gap:["Amir ville","övertyga","klassen med sitt tal."],gapForm:"övertyga",form:"övertyga – övertygade – har övertygat"});
W("hallamed",{sv:"hålla med",m:rx("(håller|höll|hålla|hållit)( inte)? med"),d:t3("Tycka samma sak som någon annan.","Agree; think the same as someone else.","أن توافق شخصًا وترى ما يراه."),ex:"Jag håller inte med dig.",tr:{en:"agree",ar:"يوافق"},syn:["tycka likadant"],opp:["säga emot"],wrong:["skratta åt","springa"],gap:["Jag tycker som du. Jag","håller med","."],gapForm:"håller med",form:"hålla med – höll med – har hållit med"});
W("koncentrera",{sv:"koncentrera sig",m:rx("koncentrera(r|de|t)?( sig| mig| dig| oss| er)?"),d:t3("Tänka på bara en sak och inte låta sig störas.","Think about only one thing and not get distracted.","أن تفكّر في شيء واحد فقط ولا تنشغل بغيره."),ex:"Det är svårt att koncentrera sig när mobilen surrar.",tr:{en:"concentrate",ar:"يركّز"},syn:["fokusera"],wrong:["vila","prata"],gap:["Stäng av musiken, så att jag kan","koncentrera mig","."],gapForm:"koncentrera mig",form:"koncentrera – koncentrerade – har koncentrerat"});
W("bindeord",{sv:"bindeord",m:rx("bindeord(et|en)?"),d:t3("Ett ord som binder ihop meningar eller delar av meningar.","A word that links sentences or parts of sentences.","كلمة تربط بين الجمل أو أجزائها."),ex:"och, men, eftersom, därför, så, dessutom",tr:{en:"linking word",ar:"أداة ربط"}});
W("debatt",{sv:"debatt",m:rx("debatt(en|er)?"),d:t3("När två sidor säger sina argument om en fråga.","When two sides give their arguments about a question.","حين يعرض طرفان حججهما حول مسألة."),ex:"Vi har debatt på fredag.",tr:{en:"debate",ar:"مناظرة"}});
const LK=[["Sara vill ha en mobilfri skola","eftersom","mobilerna stör på lektionerna.",["men","dessutom"]],
 ["Mobilerna stör på lektionerna.","Därför","vill Sara låsa in dem.",["Eftersom","Men"]],
 ["Amir lyssnade noga,","men","han höll inte med.",["eftersom","därför"]],
 ["Det ringde ut,","så","alla gick till matsalen.",["eftersom","dessutom"]],
 ["Mobilen hjälper när man söker fakta.","Dessutom","kan man ringa hem om något händer.",["Eftersom","Men"]],
 ["Amir tog fram sina papper","och","började läsa sitt tal.",["eftersom","därför"]],
 ["Lena var nöjd","eftersom","alla hade lyssnat på varandra.",["därför","dessutom"]],
 ["Många elever sover för lite.","Därför","är de trötta i skolan.",["Eftersom","Men"]],
 ["Jag förstår din åsikt,","men","jag tycker annorlunda.",["därför","dessutom"]],
 ["Amir glömde mobilen hemma,","så","han kunde inte ringa mamma.",["därför","eftersom"]],
 ["Det är bra med pauser.","Dessutom","orkar man mer efteråt.",["Eftersom","Men"]],
 ["Sara var nervös","eftersom","hela klassen tittade på henne.",["dessutom","därför"]],
 ["Sara höll sitt tal","och","Amir lyssnade.",["eftersom","därför"]]];
const LKH={och:t3("”och” lägger till något: det här och det här.","”och” adds something: this and this.","«och» تضيف شيئًا: هذا وذاك."),
 men:t3("”men” visar en motsats: det här, men inte det.","”men” shows a contrast: this, but not that.","«men» تبيّن تعارضًا: هذا، لكن ليس ذاك."),
 eftersom:t3("”eftersom” berättar skälet. Fråga: varför?","”eftersom” gives the reason. Ask: why?","«eftersom» تذكر السبب. اسأل: لماذا؟"),
 därför:t3("”därför” berättar följden. Direkt efter kommer verbet.","”därför” gives the result. The verb comes right after it.","«därför» تذكر النتيجة، ويأتي الفعل بعدها مباشرة."),
 så:t3("”så” berättar följden. Efter ”så” kommer subjektet först.","”så” gives the result. After ”så” the subject comes first.","«så» تذكر النتيجة، ويأتي الفاعل بعدها أولًا."),
 dessutom:t3("”dessutom” lägger till ett argument till. Direkt efter kommer verbet.","”dessutom” adds one more argument. The verb comes right after it.","«dessutom» تضيف حجّة أخرى، ويأتي الفعل بعدها مباشرة.")};
const podium=`<rect x="100" y="196" width="100" height="84" rx="6" fill="#a8744a"/><rect x="92" y="188" width="116" height="14" rx="5" fill="#7a5233"/>`;
const phoneIc=(x,y,mark)=>`<rect x="${x}" y="${y}" width="34" height="56" rx="7" fill="#33415c"/><rect x="${x+4}" y="${y+6}" width="26" height="40" rx="3" fill="#9fd0f5"/>${mark==="no"?`<path d="M${x-8} ${y-6} L${x+42} ${y+62}" stroke="#d63b2f" stroke-width="6" stroke-linecap="round"/>`:`<path d="M${x+42} ${y+28} l8 9 l16 -20" stroke="#1e9e5a" stroke-width="6" fill="none" stroke-linecap="round"/>`}`;
const P6=[pic(`<rect x="30" y="24" width="240" height="96" rx="6" fill="#2f4a3a" stroke="#a8744a" stroke-width="5"/><text x="150" y="84" font-family="Caveat,cursive" font-size="38" fill="#fff" text-anchor="middle">Mobilfri skola?</text><rect y="250" width="300" height="50" fill="#d9c7a8"/>${kid(70,170,"#e0b43a","#1d2433",.72)}${kid(150,160,...AMIR,.78)}${kid(230,170,...SARA,.72)}<path d="M258 186 l14 -40" stroke="#f1c7a3" stroke-width="10" stroke-linecap="round"/>`),
 pic(`<rect x="18" y="26" width="120" height="96" rx="18" fill="#fff" stroke="#1d2433" stroke-width="3"/><path d="M110 120 l18 26 l-2 -28z" fill="#fff" stroke="#1d2433" stroke-width="3"/><path d="M108 119 h20" stroke="#fff" stroke-width="5"/>${phoneIc(60,44,"no")}${kid(150,120,...SARA,.9)}${podium}<rect x="214" y="40" width="70" height="44" rx="6" fill="#ffe28a"/><text x="249" y="70" font-family="Caveat,cursive" font-size="26" text-anchor="middle" fill="#1d2433">FÖR</text>`,"#fdeef3"),
 pic(`<rect x="162" y="26" width="120" height="96" rx="18" fill="#fff" stroke="#1d2433" stroke-width="3"/><path d="M190 120 l-18 26 l2 -28z" fill="#fff" stroke="#1d2433" stroke-width="3"/><path d="M172 119 h20" stroke="#fff" stroke-width="5"/>${phoneIc(176,44,"ok")}${kid(150,120,...AMIR,.9)}${podium}<rect x="16" y="40" width="80" height="44" rx="6" fill="#bfe0f5"/><text x="56" y="70" font-family="Caveat,cursive" font-size="26" text-anchor="middle" fill="#1d2433">EMOT</text>`,"#e8f4fb"),
 pic(`<rect x="30" y="24" width="240" height="120" rx="6" fill="#2f4a3a" stroke="#a8744a" stroke-width="5"/><text x="46" y="64" font-family="Caveat,cursive" font-size="28" fill="#fff">För</text><rect x="112" y="44" width="${16*7}" height="26" rx="4" fill="#ffe28a"/><text x="46" y="114" font-family="Caveat,cursive" font-size="28" fill="#fff">Emot</text><rect x="112" y="94" width="${12*7}" height="26" rx="4" fill="#9fd0f5"/><text x="${120+16*7}" y="64" font-family="Caveat,cursive" font-size="26" fill="#fff">16</text><text x="${120+12*7}" y="114" font-family="Caveat,cursive" font-size="26" fill="#fff">12</text>${kid(105,180,...SARA,.75)}${kid(195,180,...AMIR,.75)}<path d="M122 222 Q150 206 178 222" stroke="#f1c7a3" stroke-width="10" fill="none" stroke-linecap="round"/>`)];
const U6={id:"sv7f",year:7,ord:6,title:t3("Mobilfri skola?","A phone-free school?","مدرسة بلا هواتف؟"),storyTitle:"Debatten: Mobilfri skola?",
 icon:`<svg viewBox="0 0 320 180"><rect width="320" height="180" fill="#fdf6e8"/><rect x="40" y="40" width="70" height="110" rx="12" fill="#33415c"/><rect x="48" y="52" width="54" height="80" rx="5" fill="#9fd0f5"/><path d="M30 30 L120 160" stroke="#d63b2f" stroke-width="9" stroke-linecap="round"/><rect x="150" y="38" width="140" height="44" rx="14" fill="#ffe28a"/><text x="220" y="70" font-family="Caveat,cursive" font-weight="700" font-size="30" text-anchor="middle" fill="#1d2433">För?</text><rect x="150" y="100" width="140" height="44" rx="14" fill="#bfe0f5"/><text x="220" y="132" font-family="Caveat,cursive" font-weight="700" font-size="30" text-anchor="middle" fill="#1d2433">Emot?</text></svg>`,
 pic:pic(""),words:["asikt","argument","fordel","nackdel","pasta","overtyga","hallamed","koncentrera"],terms:["bindeord","debatt"],
 story:[
  {text:["I måndags skrev Lena en fråga på tavlan: ”Ska vår skola bli mobilfri?” Hela 7B började prata samtidigt. Alla hade en åsikt.", "”På fredag har vi debatt”, sa Lena. ”Sara talar för förslaget och Amir talar emot. Ni andra röstar efteråt.” Amir blev genast nervös, eftersom han aldrig hade hållit ett tal förut."],
   pic:P6[0],
   say:t3("Nu blir det debatt i 7B. Läs om frågan som Lena skriver på tavlan.","Now there's a debate in 7B. Read about the question Lena writes on the board.","الآن ستُقام مناظرة في صف 7B. اقرأ عن السؤال الذي تكتبه لينا على السبورة.")},
  {text:["På fredagen ställde sig Sara framför klassen. ”Jag tycker att mobilerna ska låsas in på morgonen”, började hon. ”Mitt första argument är enkelt: det är svårt att koncentrera sig när mobilen surrar i fickan.", "Man tittar på den hela tiden, även när läraren pratar. Därför missar man viktiga saker på lektionerna.”"],
   pic:P6[1],
   say:t3("Sara talar för en mobilfri skola. Vilket är hennes första argument?","Sara speaks for a phone-free school. What is her first argument?","سارة تتحدّث تأييدًا لمدرسة بلا هواتف. ما حجّتها الأولى؟")},
  {text:["”Det finns en fördel till”, fortsatte Sara. ”Utan mobiler pratar vi mer med varandra på rasterna. I dag sitter många i korridoren och tittar ner i skärmen.", "Dessutom blir det mindre bråk i chattarna. Det märkte vi alla förra månaden.” Några i klassen nickade. Sara log och satte sig."],
   pic:P6[1],
   say:t3("Ordet ”dessutom” betyder att Sara lägger till ett argument till.","The word ”dessutom” means Sara adds one more argument.","كلمة «dessutom» تعني أن سارة تضيف حجّة أخرى.")},
  {text:["Sedan var det Amirs tur. Han tog ett djupt andetag. ”Sara har bra argument, men jag håller inte med”, sa han. ”Mobilen är inte bara ett problem. Den är också ett verktyg.", "Vi använder den för att söka fakta, kolla schemat och räkna i matte. Om vi låser in mobilerna, förlorar vi allt det.”"],
   pic:P6[2],
   say:t3("Amir talar emot. Hur börjar han sitt tal? Han säger något snällt om Sara först.","Amir speaks against. How does he start his speech? He says something kind about Sara first.","أمير يتحدّث معارضًا. كيف يبدأ كلمته؟ يقول شيئًا لطيفًا عن سارة أولًا.")},
  {text:["”Det finns också en stor nackdel med förslaget”, fortsatte Amir. ”Många av oss åker buss hem eller har träning efter skolan. Om något händer, måste vi kunna ringa hem.", "Min mamma blir orolig om hon inte når mig. Ni kan påstå att mobilen bara stör, men för oss är den också en trygghet.”"],
   pic:P6[2],
   say:t3("Vilken nackdel ser Amir? Tänk på bussen och träningen.","What disadvantage does Amir see? Think about the bus and practice.","ما السلبيّة التي يراها أمير؟ فكّر في الحافلة والتدريب.")},
  {text:["Efter talen fick klassen ställa frågor. ”Kan man inte bara stänga av mobilen under lektionerna?” frågade Ella. ”Jo, det är ett bra förslag”, sa Amir. Sara skrattade. ”Då håller du ju med mig lite!”", "Lena förklarade att ett bra argument har ett skäl och gärna ett exempel. ”Båda två försökte övertyga er med skäl, inte bara med känslor”, sa hon."],
   pic:P6[0],
   say:t3("Varför säger Sara att Amir håller med henne lite? Fundera på det.","Why does Sara say Amir agrees with her a little? Think about it.","لماذا تقول سارة إن أمير يوافقها قليلًا؟ فكّر في ذلك.")},
  {text:["Sedan röstade klassen. Sexton röstade för en mobilfri skola och tolv röstade emot. Sara jublade, men hon gick direkt fram till Amir. ”Ditt tal var riktigt bra”, sa hon.", "Amir hade förlorat, så han borde vara besviken. Men han var mest lättad. Han hade vågat stå framför hela klassen. ”Nästa gång övertygar jag er”, skrattade han."],
   pic:P6[3],
   say:t3("Amir förlorade omröstningen. Hur känner han sig ändå? Varför?","Amir lost the vote. How does he feel anyway? Why?","خسر أمير التصويت. كيف يشعر رغم ذلك؟ ولماذا؟")}],
 wordsSay:t3("Här är orden från debatten. Tryck på ett ord för att se vad det betyder.","Here are the words from the debate. Tap a word to see what it means.","هذه كلمات المناظرة. اضغط على كلمة لترى معناها."),
 grammar:[
  {draw:()=>{const R5=[["och","+","lägger till något","b"],["men","↔","en motsats","r"],["eftersom","←","skälet: varför?","o"],["därför / så","→","följden: vad händer då?","g"],["dessutom","++","ett argument till","b"]];
    return[A.wipe(),A.tx(L(t3("Bindeord binder ihop","Linking words join ideas","أدوات الربط تربط الأفكار")),400,64,40,"b"),...R5.flatMap(([w,s,e,c],i)=>[A.tx(w,250,140+i*72,40,c,"end"),A.tx(s,310,140+i*72,36,c),qt(e,370,140+i*72,28,"k")].map((a,j)=>j===2?Object.assign(a,{anchor:"start"}):a))]},
   say:t3("Bindeord binder ihop tankar. ”och” lägger till, ”men” visar en motsats, ”eftersom” ger skälet, ”därför” och ”så” ger följden, ”dessutom” lägger till ett argument till.","Linking words join ideas. ”och” adds, ”men” contrasts, ”eftersom” gives the reason, ”därför” and ”så” give the result, ”dessutom” adds one more argument.","أدوات الربط تربط الأفكار: «och» للإضافة، «men» للتعارض، «eftersom» للسبب، «därför» و«så» للنتيجة، «dessutom» لإضافة حجّة أخرى.")},
  {draw:()=>[A.wipe(),A.tx(L(t3("Bindeord i debatten","Linking words in the debate","أدوات الربط في المناظرة")),400,60,36,"b"),...boxes([["Det är svårt att koncentrera sig",null],["eftersom","o","skäl"]],150,30),...boxes([["mobilen surrar i fickan.","o"]],250,30),A.arrow(560,190,470,222,"o"),
    ...boxes([["Sara har bra argument,",null],["men","r","motsats"],["jag håller inte med.",null]],390,30)],
   say:t3("Sara: Det är svårt att koncentrera sig eftersom mobilen surrar. Efter ”eftersom” kommer skälet. Amir: Sara har bra argument, men jag håller inte med. ”men” visar att han tycker tvärtom.","Sara: It's hard to concentrate because the phone buzzes. After ”eftersom” comes the reason. Amir: Sara has good arguments, but I disagree. ”men” shows he thinks the opposite.","سارة: من الصعب التركيز لأن الهاتف يهتز. بعد «eftersom» يأتي السبب. أمير: لدى سارة حجج جيدة، لكني لا أوافق. «men» تبيّن أنه يرى العكس.")},
  {draw:()=>[A.wipe(),A.tx(L(t3("Ordföljd efter därför och så","Word order after därför and så","ترتيب الكلمات بعد därför و så")),400,60,36,"b"),
    ...boxes([["Därför","g","bindeord"],["missar","r","verb"],["man","b","subjekt"],["viktiga saker.",null]],170,38),
    ...boxes([["så","g","bindeord"],["man","b","subjekt"],["missar","r","verb"],["viktiga saker.",null]],320,38),
    qt("English: Therefore you miss … (subject first)",400,450,26,"k")],
   say:t3("Efter ”därför” och ”dessutom” kommer verbet direkt, som i ”I dag går Amir”. Efter ”så”, ”och” och ”men” kommer subjektet först. På engelska står subjektet först efter ”therefore”, men inte på svenska.","After ”därför” and ”dessutom” the verb comes straight away, like in ”I dag går Amir”. After ”så”, ”och” and ”men” the subject comes first. In English the subject comes first after ”therefore”, but not in Swedish.","بعد «därför» و«dessutom» يأتي الفعل مباشرة كما في «I dag går Amir». أما بعد «så» و«och» و«men» فيأتي الفاعل أولًا. وهذا قريب من العربية: «لذلك يفوّت المرء…» حيث يأتي الفعل بعد «لذلك».")}],
 read:[
  {q:"Vad skulle klassen göra på fredagen?",o:["Ha en debatt om en mobilfri skola.", "Skriva ett prov om mobiler.", "Lämna in sina mobiler till Lena."],why:"Del 1: ”På fredag har vi debatt.”"},
  {q:"Vilket var Saras första argument?",o:["Det är svårt att koncentrera sig när mobilen surrar.", "Mobiler är för dyra.", "Mobiler går lätt sönder."],why:"Del 2: Mitt första argument är enkelt …"},
  {q:"Vilken fördel såg Sara med att låsa in mobilerna?",o:["Eleverna pratar mer med varandra på rasterna.", "Lektionerna blir kortare.", "Ingen får läxor."],why:"Del 3: Utan mobiler pratar vi mer med varandra."},
  {q:"Vad använder eleverna mobilen till, enligt Amir?",o:["Söka fakta, kolla schemat och räkna.", "Bara spela spel.", "Titta på film på lektionerna."],why:"Del 4: söka fakta, kolla schemat och räkna i matte."},
  {q:"Vilken nackdel tog Amir upp?",o:["Man kan inte ringa hem om något händer.", "Mobilerna kan bli stulna.", "Skåpen är för små."],why:"Del 5: Om något händer, måste vi kunna ringa hem."},
  {q:"Varför sa Sara: ”Då håller du ju med mig lite”?",o:["Amir tyckte att man kunde stänga av mobilen på lektionerna.", "Amir ville byta sida i debatten.", "Amir röstade för en mobilfri skola."],why:"Amir tyckte att Ellas förslag var bra. Det ligger nära Saras åsikt."},
  {q:"Vad har ett bra argument, enligt Lena?",o:["Ett skäl och gärna ett exempel.", "Starka känslor.", "Många svåra ord."],why:"Del 6: ett skäl och gärna ett exempel."},
  {q:"Hur slutade omröstningen?",o:["16 röstade för och 12 emot.", "12 röstade för och 16 emot.", "Det blev lika."],why:"Del 7: Sexton för, tolv emot."},
  {q:"Varför var Amir lättad fast han förlorade?",o:["Han hade vågat hålla ett tal inför klassen.", "Han ville egentligen ha en mobilfri skola.", "Lena gav honom ett pris."],why:"Del 7: Han hade vågat stå framför hela klassen."}],
 gram(lv,write){const [pre,w,post,wr]=pick(LK),done=`${pre} ${w} ${post}`,gq=`${pre} ____ ${post}`,hint={say:LKH[w.toLowerCase()],draw:[]};
  if(write||lv===2)return{kind:"text",ans:[w],show:w,q:[A.wipe(),A.tx(L(t3("Skriv ett bindeord som passar","Write a linking word that fits","اكتب أداة ربط مناسبة")),400,70,34,"b"),...svLines(gq,180,38),qt("och · men · eftersom · därför · så · dessutom",400,350,26,"o")],sol:svLines(done,400,30,"g"),hint};
  const opts=shuffle([w,...wr]);
  return{kind:"choice",opts,ans:opts.indexOf(w),show:w,q:[A.wipe(),A.tx(L(t3("Vilket bindeord passar?","Which linking word fits?","أي أداة ربط تناسب؟")),400,70,34,"b"),...svLines(gq,190,38)],sol:svLines(done,390,30,"g"),
   hint:{say:t3("Läs hela meningen. Behövs ett skäl, en motsats, en följd eller ett argument till?","Read the whole sentence. Does it need a reason, a contrast, a result or one more argument?","اقرأ الجملة كلّها. هل تحتاج سببًا أم تعارضًا أم نتيجة أم حجّة إضافية؟"),draw:[]}}},
 help:[{say:t3("eftersom = skälet. därför = följden, och sedan kommer verbet: Därför missar man …","eftersom = the reason. därför = the result, and then the verb comes: Därför missar man …","eftersom = السبب. därför = النتيجة، ثم يأتي الفعل: Därför missar man …"),draw:()=>boxes([["Därför","g","1"],["missar","r","2"],["man","b",""]],250,48)}]};
LESSONS.push(svUnit(U6));

/* ---------------- unit 7: Mormors kanelbullar (imperativ och ordningsord) ---------------- */
W("ingrediens",{sv:"ingrediens (en)",m:rx("ingrediens(en|er|erna)?"),d:t3("En sak som man behöver för att laga mat eller baka.","A thing you need to cook or bake.","شيء تحتاجه للطبخ أو الخَبز."),ex:"Ta fram alla ingredienser först.",tr:{en:"ingredient",ar:"مُكوِّن"},syn:["råvara"],wrong:["verktyg","ugn"],gap:["Mjöl och jäst är viktiga","ingredienser","i bullar."],gapForm:"ingredienser",form:"en ingrediens – ingredienser"});
W("deg",{sv:"deg (en)",m:rx("deg(en|ar|arna)?"),d:t3("Mjöl blandat med vätska, som man bakar bröd eller bullar av.","Flour mixed with liquid, used to bake bread or buns.","دقيق مخلوط بسائل نخبز منه الخبز أو الكعك."),ex:"Degen ska vara mjuk och blank.",tr:{en:"dough",ar:"عجين"},wrong:["sås","soppa"],gap:["Knåda","degen","i tio minuter."],gapForm:"degen",form:"en deg – degar"});
W("blanda",{sv:"blanda",m:rx("bland(a|ar|ade|at)"),d:t3("Röra ihop olika saker.","Stir different things together.","أن تخلط أشياء مختلفة معًا."),ex:"Blanda mjöl och socker i en skål.",tr:{en:"mix",ar:"يخلط"},syn:["röra ihop"],wrong:["skölja","frysa"],gap:["Först ska du","blanda","mjöl och socker."],gapForm:"blanda",form:"blanda – blandade – har blandat"});
W("knada",{sv:"knåda",m:rx("knåd(a|ar|ade|at)"),d:t3("Trycka och vika en deg om och om igen med händerna.","Press and fold dough again and again with your hands.","أن تضغط العجين وتطويه مرارًا بيديك."),ex:"Knåda degen i tio minuter.",tr:{en:"knead",ar:"يعجن"},syn:["arbeta degen"],wrong:["koka","skölja"],gap:["Sara fick","knåda","degen tills armarna värkte."],gapForm:"knåda",form:"knåda – knådade – har knådat"});
W("jasa",{sv:"jäsa",m:rx("jäs(a|er|te)"),d:t3("När en deg växer och blir luftig av jästen.","When dough rises and gets airy because of the yeast.","عندما يكبر العجين ويصبح هشًّا بفعل الخميرة."),ex:"Låt degen jäsa i 30 minuter.",tr:{en:"rise (of dough)",ar:"يختمر"},syn:["växa","höja sig"],wrong:["frysa","smälta"],gap:["Låt degen","jäsa","under en bakduk."],gapForm:"jäsa",form:"jäsa – jäste – har jäst"});
W("gradda",{sv:"grädda",m:rx("grädd(a|ar|ade|at)"),d:t3("Baka något i ugnen.","Bake something in the oven.","أن تخبز شيئًا في الفرن."),ex:"Grädda bullarna i åtta minuter.",tr:{en:"bake",ar:"يَخبِز"},syn:["baka i ugnen"],wrong:["frysa","diska"],gap:["Till sist ska du","grädda","bullarna i ugnen."],gapForm:"grädda",form:"grädda – gräddade – har gräddat"});
W("mjuk",{sv:"mjuk",m:rx("mjuk(t|a|are)?"),d:t3("Inte hård. Den ger efter när man trycker.","Not hard. It gives way when you press.","ليس صلبًا؛ يلين عندما تضغط عليه."),ex:"Degen ska vara mjuk och blank.",tr:{en:"soft",ar:"طريّ"},syn:["len"],opp:["hård"],wrong:["kall","sur"],gap:["Knåda tills degen är","mjuk","och blank."],gapForm:"mjuk",form:"mjuk – mjukt – mjuka"});
W("doft",{sv:"doft (en)",m:rx("doft(en|er|ade|ar)?"),d:t3("En god lukt.","A nice smell.","رائحة طيّبة."),ex:"En underbar doft spred sig i huset.",tr:{en:"scent, smell",ar:"رائحة زكيّة"},syn:["lukt","arom"],opp:["stank"],wrong:["ljud","färg"],gap:["Hela huset fylldes av en underbar","doft","av kanel."],gapForm:"doft",form:"en doft – dofter"});
W("imperativ",{sv:"imperativ",m:rx("imperativ(et|en)?"),d:t3("Verbets uppmaningsform. Man säger åt någon att göra något.","The verb's command form. You tell someone to do something.","صيغة الأمر للفعل: تطلب من أحد أن يفعل شيئًا."),ex:"Häll i mjölken! Blanda!",tr:{en:"imperative",ar:"فعل الأمر"}});
W("recept",{sv:"recept",m:rx("recept(et|en)?"),d:t3("En text som steg för steg visar hur man lagar mat eller bakar.","A text that shows step by step how to cook or bake.","نصّ يبيّن خطوة بخطوة كيف تطبخ أو تخبز."),ex:"Mormors recept på kanelbullar.",tr:{en:"recipe",ar:"وصفة"}});
const IM=[["hälla","häll","häller","hällde","{V} mjölken i en kastrull."],["värma","värm","värmer","värmde","{V} mjölken tills den är fingervarm."],["smälta","smält","smälter","smälte","{V} smöret i kastrullen."],
 ["blanda","blanda","blandar","blandade","{V} mjöl, socker och salt i en skål."],["knåda","knåda","knådar","knådade","{V} degen i tio minuter."],["låta","låt","låter","lät","{V} degen jäsa under en bakduk."],
 ["dela","dela","delar","delade","{V} degen i två bitar."],["rulla","rulla","rullar","rullade","{V} ihop degen till en lång rulle."],["strö","strö","strör","strödde","{V} kanel och socker över degen."],
 ["lägga","lägg","lägger","lade","{V} bullarna i formar på en plåt."],["pensla","pensla","penslar","penslade","{V} bullarna med uppvispat ägg."],["grädda","grädda","gräddar","gräddade","{V} bullarna mitt i ugnen."],
 ["tvätta","tvätta","tvättar","tvättade","{V} händerna innan du börjar."],["mäta","mät","mäter","mätte","{V} upp mjölet med ett decilitermått."],["sätta","sätt","sätter","satte","{V} på ugnen på 225 grader."],["ta","ta","tar","tog","{V} ut bullarna när de är gyllenbruna."]];
const STEPS=["Smält smöret.","Värm mjölken.","Rör ut jästen.","Blanda i mjölet.","Knåda degen.","Låt degen jäsa.","Kavla ut degen.","Strö över kanel.","Rulla ihop och skär.","Grädda bullarna."];
const bun=(x,y,r=16)=>`<circle cx="${x}" cy="${y}" r="${r}" fill="#c98a4b"/><path d="M${x} ${y} m-${r*.55} 0 a${r*.55} ${r*.55} 0 1 1 ${r*.55} ${r*.55} a${r*.3} ${r*.3} 0 1 1 0 -${r*.6}" stroke="#8a5a2b" stroke-width="3" fill="none"/><circle cx="${x-r*.4}" cy="${y-r*.5}" r="2" fill="#fff"/><circle cx="${x+r*.3}" cy="${y-r*.6}" r="2" fill="#fff"/>`;
const MORMOR=["#9b6bb0","#d9d9d9"];
const P7=[pic(`<rect x="40" y="30" width="220" height="120" rx="10" fill="#fff" stroke="#e07b00" stroke-width="5"/><text x="150" y="80" font-family="Caveat,cursive" font-weight="700" font-size="40" text-anchor="middle" fill="#e07b00">FIKA</text><text x="150" y="122" font-family="Caveat,cursive" font-size="26" text-anchor="middle" fill="#1d2433">till cupen i Danmark</text><rect x="190" y="190" width="70" height="80" rx="10" fill="#cfe9f5" stroke="#5aa0d8" stroke-width="3"/>${[0,1,2].map(i=>`<circle cx="${210+i*15}" cy="${255-i*12}" r="9" fill="#f2c94c" stroke="#b7902a" stroke-width="2"/>`).join("")}<circle cx="80" cy="235" r="34" fill="#fff" stroke="#1d2433" stroke-width="4"/><path d="M80 214l18 13-7 21h-22l-7-21z" fill="#1d2433"/>`,"#fdf3e4"),
 pic(`<rect y="200" width="300" height="100" fill="#d9b48a"/>${kid(70,110,...MORMOR,.9)}<path d="M150 200 q40 40 80 0z" fill="#e8eef5" stroke="#5b6884" stroke-width="3"/><rect x="236" y="140" width="40" height="60" rx="4" fill="#fff" stroke="#5b6884" stroke-width="3"/><text x="256" y="176" font-size="14" text-anchor="middle" fill="#1d2433">MJÖL</text><rect x="120" y="150" width="26" height="50" rx="3" fill="#5aa0d8"/><rect x="120" y="150" width="26" height="12" fill="#fff"/><rect x="160" y="30" width="120" height="80" rx="6" fill="#fffdf2" stroke="#b98757" stroke-width="3"/><text x="220" y="56" font-family="Caveat,cursive" font-size="20" text-anchor="middle" fill="#1d2433">Kanelbullar</text>${[0,1,2].map(i=>`<path d="M176 ${72+i*12}h88" stroke="#b9c2d0" stroke-width="3"/>`).join("")}`,"#fdf3e4"),
 pic(`<rect y="200" width="300" height="100" fill="#d9b48a"/><rect x="40" y="186" width="220" height="22" rx="6" fill="#e8c99a"/>${kid(110,90,...SARA,.85)}${kid(210,96,...AMIR,.8)}<ellipse cx="150" cy="182" rx="56" ry="20" fill="#f5e6c8" stroke="#c9ad7a" stroke-width="3"/><path d="M96 150 Q120 176 132 178M204 150 Q180 176 168 178" stroke="#f1c7a3" stroke-width="11" fill="none" stroke-linecap="round"/>${[0,1,2,3,4].map(i=>`<circle cx="${60+i*45}" cy="${240+(i%2)*14}" r="3" fill="#fff"/>`).join("")}`,"#fdf3e4"),
 pic(`<rect x="40" y="130" width="220" height="140" rx="10" fill="#5b6884"/><rect x="60" y="160" width="180" height="90" rx="6" fill="#f2a64a" opacity=".55"/><rect x="50" y="110" width="200" height="16" rx="5" fill="#9aa8c4"/><rect x="60" y="98" width="180" height="12" rx="4" fill="#9aa8c4"/>${[0,1,2,3].map(i=>bun(85+i*44,84,15)).join("")}${[0,1,2].map(i=>`<path d="M${105+i*45} 60 q-8 -10 0 -18 q8 -8 0 -16" stroke="#c6cfdc" stroke-width="3" fill="none" stroke-linecap="round"/>`).join("")}`,"#fdf3e4"),
 pic(`<rect width="300" height="300" fill="#e9eef5"/>${[0,1,2,3,4,5].map(i=>`<rect x="${4+i*50}" y="30" width="44" height="130" fill="${["#5aa0d8","#e98a5a","#7cc08a"][i%3]}" stroke="#33415c" stroke-width="2"/>`).join("")}${kid(100,130,...SARA,.75)}${kid(200,130,...AMIR,.75)}<rect x="30" y="214" width="240" height="18" rx="4" fill="#b98757"/><rect x="44" y="232" width="10" height="60" fill="#8d6440"/><rect x="246" y="232" width="10" height="60" fill="#8d6440"/>${[0,1,2,3,4].map(i=>bun(70+i*40,204,14)).join("")}`)];
const U7={id:"sv7g",year:7,ord:7,title:t3("Mormors kanelbullar","Grandma's cinnamon buns","كعكات القرفة من صنع الجدّة"),storyTitle:"Mormors kanelbullar",
 icon:`<svg viewBox="0 0 320 180"><rect width="320" height="180" fill="#fdf3e4"/><ellipse cx="160" cy="130" rx="120" ry="26" fill="#fff" stroke="#c6cfdc" stroke-width="3"/>${bun(110,112,26)}${bun(170,108,28)}${bun(228,114,24)}${[0,1,2].map(i=>`<path d="M${120+i*50} 70 q-10 -12 0 -24 q10 -10 0 -22" stroke="#c6cfdc" stroke-width="4" fill="none" stroke-linecap="round"/>`).join("")}</svg>`,
 pic:pic(""),words:["ingrediens","deg","blanda","knada","jasa","gradda","mjuk","doft"],terms:["imperativ","recept"],
 story:[
  {text:["Fotbollslaget ville åka på en cup i Danmark, men resan var dyr. ”Vi måste samla in pengar”, sa tränaren. ”Har någon en idé?”", "”Vi kan sälja fika i skolan!” sa Sara. ”Min mormor bakar världens bästa kanelbullar. Man känner doften redan i trappan.” Alla höll med. På lördagen cyklade Sara och Amir hem till mormor Inga."],
   pic:P7[0],
   say:t3("Laget behöver pengar. Vad är Saras idé?","The team needs money. What is Sara's idea?","يحتاج الفريق إلى المال. ما فكرة سارة؟")},
  {text:["Mormor tog fram ett gammalt kort med ett recept. ”Läs högt, Amir”, sa hon. ”Först tar vi fram alla ingredienser.”", "Amir läste: ”Kanelbullar, ungefär 30 stycken. Du behöver 50 gram jäst, 100 gram smör, 3 dl mjölk, 1 dl socker, en nypa salt och ungefär 8 dl vetemjöl. Till fyllningen: smör, socker och kanel.”"],
   pic:P7[1],
   say:t3("Ett recept börjar ofta med en lista över allt man behöver.","A recipe often starts with a list of everything you need.","غالبًا ما تبدأ الوصفة بقائمة بكل ما تحتاجه.")},
  {text:["”1. Smält smöret i en kastrull. Häll i mjölken och värm försiktigt tills det är fingervarmt. 2. Smula jästen i en stor skål. Häll över mjölken och rör tills jästen löser sig.”", "”Inte för varmt”, sa mormor. ”Då dör jästen, och sedan jäser degen inte.” Amir stack ner ett finger i mjölken. Den var lagom."],
   pic:P7[1],
   say:t3("Smält! Häll! Värm! Verben står först och säger vad du ska göra. Det heter imperativ.","Melt! Pour! Warm! The verbs come first and tell you what to do. That is called the imperative.","ذوّب! اسكب! سخّن! الأفعال تأتي أولًا وتقول لك ماذا تفعل. هذه صيغة الأمر.")},
  {text:["”3. Blanda i socker, salt och nästan allt mjöl. 4. Knåda degen i tio minuter, tills den är mjuk och blank.”", "Sara knådade tills armarna värkte. ”Det här är ju träning”, stönade hon. Mormor skrattade. ”Koncentrera dig nu, så blir bullarna fina.”"],
   pic:P7[2],
   say:t3("Varför säger Sara att det är träning? Tänk på hur det känns i armarna.","Why does Sara say it's a workout? Think about how her arms feel.","لماذا تقول سارة إنه تمرين؟ فكّر في شعور ذراعيها.")},
  {text:["”5. Låt degen jäsa under en bakduk i 30 minuter.” Medan degen jäste, spelade de kort vid köksbordet. Efter det var den dubbelt så stor.", "”6. Kavla ut degen till en stor platta. Bred på smör och strö över socker och kanel. 7. Rulla ihop plattan och skär den i bitar.” Amir märkte en fördel med att baka: hela köket blev varmt och gott."],
   pic:P7[2],
   say:t3("Först, sedan, efter det, till sist. Sådana ord visar ordningen i ett recept.","First, then, after that, finally. Words like these show the order in a recipe.","أولًا، ثم، بعد ذلك، وأخيرًا. هذه الكلمات تبيّن ترتيب الخطوات في الوصفة.")},
  {text:["”8. Lägg bitarna i formar på en plåt och låt dem jäsa igen. Pensla med ägg. 9. Grädda mitt i ugnen på 225 grader i 5–8 minuter.”", "Till sist tog mormor ut plåten. En underbar doft spred sig i hela huset. ”Smaka försiktigt, de är heta”, sa hon."],
   pic:P7[3],
   say:t3("Vad är det sista steget i receptet? Hitta orden ”till sist”.","What is the last step in the recipe? Find the words ”till sist”.","ما الخطوة الأخيرة في الوصفة؟ ابحث عن «till sist».")},
  {text:["På måndagen sålde de bullarna i korridoren. Doften lockade elever från hela skolan, och efter tjugo minuter var allt slut.", "”Det behövdes inga argument”, skrattade Amir och räknade pengarna. ”Doften övertygade alla.” Sara var stolt. ”Nu kan du mormors hemlighet”, sa hon. ”Ha tålamod och låt degen jäsa.”"],
   pic:P7[4],
   say:t3("Varför tog bullarna slut så fort? Läs vad Amir säger.","Why were the buns gone so fast? Read what Amir says.","لماذا نفدت الكعكات بسرعة؟ اقرأ ما يقوله أمير.")}],
 wordsSay:t3("Här är bakorden. Tryck på ett ord för att se vad det betyder.","Here are the baking words. Tap a word to see what it means.","هذه كلمات الخَبز. اضغط على كلمة لترى معناها."),
 grammar:[
  {draw:()=>[A.wipe(),A.tx(L(t3("Imperativ: gör så här!","Imperative: do this!","صيغة الأمر: افعل هكذا!")),400,64,40,"b"),
    ...[[["Smält","r"],["smöret.",null]],[["Häll","r"],["i mjölken.",null]],[["Blanda","r"],["i mjölet.",null]],[["Knåda","r"],["degen.",null]]].flatMap((row,i)=>boxes(row,150+i*72,36)),
    qt(L(t3("Verbet först – inget subjekt","Verb first – no subject","الفعل أولًا – بلا فاعل")),400,456,28,"g")],
   say:t3("I ett recept står verbet först. Man säger inte ”du”. Det heter imperativ. Engelska gör likadant: Melt the butter. Arabiska har en egen form: ذوّب الزبدة.","In a recipe the verb comes first. You don't say ”du”. It is called the imperative. English does the same: Melt the butter. Arabic has its own form: ذوّب الزبدة.","في الوصفة يأتي الفعل أولًا دون «du». هذه صيغة الأمر. والإنجليزية مثلها: Melt the butter. وللعربية صيغة أمر خاصة: ذوّب الزبدة.")},
  {draw:()=>{const C=[140,310,490,660],G1=[["blandar","Blanda!"],["knådar","Knåda!"],["gräddar","Grädda!"]],G2=[["häller","Häll!"],["smälter","Smält!"],["lägger","Lägg!"]];
    return[A.wipe(),A.tx(L(t3("Från presens till imperativ","From present tense to imperative","من المضارع إلى الأمر")),400,60,36,"b"),
     qt("presens",C[0],120,26,"k"),qt("imperativ",C[1],120,26,"r"),qt("presens",C[2],120,26,"k"),qt("imperativ",C[3],120,26,"r"),
     ...G1.flatMap(([a,b],j)=>[A.tx(a,C[0],190+j*70,36,"b"),A.tx(b,C[1],190+j*70,36,"r")]),...G2.flatMap(([a,b],j)=>[A.tx(a,C[2],190+j*70,36,"o"),A.tx(b,C[3],190+j*70,36,"r")]),
     A.p(R.line(400,100,400,380,.3),"k",2),qt("-ar: ta bort -r",C[0]+85,430,28,"b"),qt("-er: ta bort -er",C[2]+85,430,28,"o")]},
   say:t3("Tänk på presens. Slutar verbet på -ar, tar du bort -r: blandar – Blanda! Slutar det på -er, tar du bort -er: häller – Häll!","Think of the present tense. If the verb ends in -ar, remove -r: blandar – Blanda! If it ends in -er, remove -er: häller – Häll!","فكّر في المضارع: إذا انتهى الفعل بـ ‎-ar احذف ‎-r: blandar ← Blanda! وإذا انتهى بـ ‎-er احذف ‎-er: häller ← Häll!")},
  {draw:()=>{const X=[120,320,500,680],y=170;return[A.wipe(),A.tx(L(t3("Ordningsord","Order words","كلمات الترتيب")),400,60,38,"b"),A.arrow(50,y,770,y,"k"),
    ...[["Först","värm mjölken"],["Sedan","knåda degen"],["Efter det","låt den jäsa"],["Till sist","grädda"]].flatMap(([o,s],i)=>[A.p(R.line(X[i],y-12,X[i],y+12,.2),"o",5),A.tx(o,X[i],y-28,34,"o"),qt(s,X[i],y+46,24,"k")]),
    ...boxes([["Sedan","o","1"],["knådar","r","2: verb"],["du","b","subjekt"],["degen.",null]],370,38)]},
   say:t3("Först, sedan, efter det och till sist visar ordningen. Börjar meningen med ett ordningsord, står verbet på plats 2: Sedan knådar du degen.","Först, sedan, efter det and till sist show the order. If a sentence starts with an order word, the verb is in place 2: Sedan knådar du degen.","«Först» و«sedan» و«efter det» و«till sist» تبيّن الترتيب. وإذا بدأت الجملة بإحداها يأتي الفعل في المكان الثاني: Sedan knådar du degen.")}],
 read:[
  {q:"Varför behövde laget pengar?",o:["De ville åka på en cup i Danmark.", "De behövde nya bollar.", "Tränaren skulle sluta."],why:"Del 1: en cup i Danmark, men resan var dyr."},
  {q:"Vems recept bakade de efter?",o:["Saras mormor Ingas", "Amirs mammas", "Lenas"],why:"Del 1–2: mormor Inga tog fram receptet."},
  {q:"Vad händer om mjölken är för varm?",o:["Jästen dör och degen jäser inte.", "Bullarna blir för söta.", "Smöret smälter inte."],why:"Del 3: Då dör jästen."},
  {q:"Hur länge ska man knåda degen?",o:["I tio minuter", "I trettio minuter", "I fem minuter"],why:"Del 4: Knåda degen i tio minuter."},
  {q:"Vad gjorde de medan degen jäste?",o:["De spelade kort.", "De gick ut och sprang.", "De diskade."],why:"Del 5: spelade de kort vid köksbordet."},
  {q:"”Det här är ju träning”, säger Sara. Vad menar hon?",o:["Det var tungt för armarna att knåda.", "Hon ville hellre spela fotboll.", "Hon tyckte att receptet var lätt."],why:"Del 4: Hon knådade tills armarna värkte."},
  {q:"Vad gör man till sist enligt receptet?",o:["Gräddar bullarna i ugnen.", "Blandar mjöl och socker.", "Smälter smöret."],why:"Del 6: Grädda mitt i ugnen."},
  {q:"Varför var bullarna slut efter tjugo minuter?",o:["Den goda doften lockade många som ville köpa.", "Mormor åt upp dem.", "De hade bara bakat fem bullar."],why:"Del 7: Doften lockade elever från hela skolan."},
  {q:"Hur varm ska ugnen vara?",o:["225 grader", "175 grader", "250 grader"],why:"Del 6: på 225 grader."}],
 gram(lv,write){
  if(!write&&lv===1&&Math.random()<.35){const idx=shuffle([...STEPS.keys()]).slice(0,3),first=Math.random()<.5,a=first?Math.min(...idx):Math.max(...idx),opts=shuffle(idx.map(i=>STEPS[i]));
   return{kind:"choice",opts,ans:opts.indexOf(STEPS[a]),show:STEPS[a],q:[A.wipe(),A.tx(L(first?t3("Vilket steg kommer först?","Which step comes first?","أي خطوة تأتي أولًا؟"):t3("Vilket steg kommer till sist?","Which step comes last?","أي خطوة تأتي أخيرًا؟")),400,110,38,"b"),qt(L(t3("Tänk på mormors recept.","Think of Grandma's recipe.","فكّر في وصفة الجدّة.")),400,190,28,"k")],
    sol:[A.tx(STEPS[a],400,400,38,"g")],hint:{say:t3("Man smälter och blandar först. Man gräddar till sist.","You melt and mix first. You bake last.","نذوّب ونخلط أولًا، ونخبز في النهاية."),draw:[]}}}
  const [inf,imp,pres,past,fr]=pick(IM),q=fr.replace("{V}","____"),done=fr.replace("{V}",cap(imp)),cut=imp===pres.slice(0,-1)?"-r":"-er";
  const hint={say:t3(`Presens är ”${pres}”. Ta bort ${cut}.`,`The present tense is ”${pres}”. Remove ${cut}.`,`المضارع هو «${pres}». احذف ${cut}.`),draw:[]};
  const head=[A.wipe(),A.tx(L(t3("Skriv verbet i imperativ","Write the verb in the imperative","اكتب الفعل بصيغة الأمر")),400,70,34,"b"),...svLines(q,200,40),A.tx(`(${inf})`,400,320,36,"o")];
  if(write||lv===2)return{kind:"text",ans:[imp],show:cap(imp),q:head,sol:[A.tx(done,400,420,36,"g")],hint};
  const opts=shuffle((imp===inf?[imp,pres,past]:[imp,inf,pres]).map(cap));
  return{kind:"choice",opts,ans:opts.indexOf(cap(imp)),show:cap(imp),q:head.slice(0,-1).concat([A.tx(L(t3("Välj imperativ","Choose the imperative","اختر صيغة الأمر")),400,320,30,"k")]),sol:[A.tx(done,400,420,36,"g")],hint}},
 help:[{say:t3("Imperativ: verbet först. blandar – Blanda! häller – Häll!","Imperative: verb first. blandar – Blanda! häller – Häll!","الأمر: الفعل أولًا. blandar ← Blanda! häller ← Häll!"),draw:()=>[A.tx("blandar → Blanda!",400,200,46,"b"),A.tx("häller → Häll!",400,300,46,"o")]}]};
LESSONS.push(svUnit(U7));

/* ---------------- unit 8: Vilse i fjällen (sammansatta ord) ---------------- */
W("fjall",{sv:"fjäll (ett)",m:rx("fjäll(et|en|ens)?"),d:t3("Ett högt berg i norra Sverige, ofta utan träd på toppen.","A high mountain in northern Sweden, often with no trees on top.","جبل عالٍ في شمال السويد، غالبًا بلا أشجار في قمّته."),ex:"Klassen åkte till fjällen.",tr:{en:"mountain, fell",ar:"جبل"},syn:["berg"],opp:["dal"],wrong:["sjö","skog"],gap:["Vi vandrade upp på","fjället","och tittade ut."],gapForm:"fjället",form:"ett fjäll – fjäll"});
W("stuga",{sv:"stuga (en)",m:rx("stug(a|an|or|orna)"),d:t3("Ett litet hus, ofta på landet eller i fjällen.","A small house, often in the countryside or mountains.","بيت صغير، غالبًا في الريف أو في الجبال."),ex:"Stugan låg vid en sjö.",tr:{en:"cabin, cottage",ar:"كوخ"},syn:["litet hus"],wrong:["skola","affär"],gap:["Klassen bodde i en","stuga","vid en sjö."],gapForm:"stuga",form:"en stuga – stugor"});
W("utsikt",{sv:"utsikt (en)",m:rx("utsikt(en|er)?"),d:t3("Det man ser när man tittar ut, långt bort.","What you see when you look out, far away.","ما تراه عندما تنظر إلى البعيد."),ex:"Från toppen var utsikten fantastisk.",tr:{en:"view",ar:"منظر"},syn:["vy"],wrong:["väg","karta"],gap:["Från fönstret hade vi en fin","utsikt","över bergen."],gapForm:"utsikt",form:"en utsikt – utsikter"});
W("packning",{sv:"packning (en)",m:rx("packning(en|ar)?"),d:t3("Det man har packat med sig, till exempel i en ryggsäck.","What you have packed, for example in a backpack.","ما حزمته معك، مثلًا في حقيبة الظهر."),ex:"Lena kontrollerade allas packning.",tr:{en:"gear, luggage",ar:"الأمتعة"},syn:["bagage"],wrong:["mat","karta"],gap:["Har du regnjackan i din","packning","?"],gapForm:"packning",form:"en packning – packningar"});
W("dimma",{sv:"dimma (en)",m:rx("dimm(a|an|or)"),d:t3("Moln nära marken, så att man inte ser långt.","Cloud near the ground, so you can't see far.","سحاب قريب من الأرض فلا ترى بعيدًا."),ex:"En grå dimma kom rullande.",tr:{en:"fog, mist",ar:"ضباب"},syn:["tjocka"],wrong:["regn","vind"],gap:["Vi såg bara några meter framåt i","dimman","."],gapForm:"dimman",form:"en dimma – dimmor"});
W("vilse",{sv:"gå vilse",m:rx("vilse"),d:t3("Inte hitta vägen och inte veta var man är.","Not find the way and not know where you are.","ألّا تجد الطريق ولا تعرف أين أنت."),ex:"Vi har gått vilse!",tr:{en:"get lost",ar:"يضلّ الطريق"},syn:["komma bort"],opp:["hitta rätt"],wrong:["somna","springa"],gap:["Utan karta är det lätt att gå","vilse","i skogen."],gapForm:"vilse",form:"gå vilse – gick vilse – har gått vilse"});
W("kompass",{sv:"kompass (en)",m:rx("kompass(en|er)?"),d:t3("Ett verktyg med en nål som alltid pekar mot norr.","A tool with a needle that always points north.","أداة لها إبرة تشير دائمًا إلى الشمال."),ex:"Sara tog fram en kompass.",tr:{en:"compass",ar:"بوصلة"},wrong:["klocka","karta"],gap:["Nålen på en","kompass","pekar mot norr."],gapForm:"kompass",form:"en kompass – kompasser"});
W("modig",{sv:"modig",m:rx("modig(t|a|are)?"),d:t3("Som vågar göra något fast det är farligt eller svårt.","Daring to do something even if it is dangerous or hard.","من يجرؤ على فعل شيء رغم خطورته أو صعوبته."),ex:"Ni var modiga.",tr:{en:"brave",ar:"شجاع"},syn:["djärv","tapper"],opp:["feg","rädd"],wrong:["trött","arg"],gap:["Det var","modigt","att gå först i mörkret."],gapForm:"modigt",form:"modig – modigt – modiga"});
W("sammansattord",{sv:"sammansatt ord",m:rx("sammansatt(a)? ord(et|en)?"),d:t3("Ett ord som är byggt av två eller fler ord.","A word built from two or more words.","كلمة مبنيّة من كلمتين أو أكثر."),ex:"fjäll + stuga = fjällstuga",tr:{en:"compound word",ar:"كلمة مركّبة"}});
W("forled",{sv:"förled",m:rx("förled(et|en)?"),d:t3("Första delen i ett sammansatt ord.","The first part of a compound word.","الجزء الأول من الكلمة المركّبة."),ex:"fjäll i fjällstuga",tr:{en:"first part (of a compound)",ar:"الجزء الأول"}});
W("efterled",{sv:"efterled",m:rx("efterled(et|en)?"),d:t3("Sista delen i ett sammansatt ord. Den säger vad det är.","The last part of a compound word. It says what the thing is.","الجزء الأخير من الكلمة المركّبة، وهو يحدّد ما هو الشيء."),ex:"stuga i fjällstuga",tr:{en:"last part, head word",ar:"الجزء الأخير"}});
W("fogs",{sv:"fog-s",m:rx("fog-s"),d:t3("Ett s som ibland binder ihop orden i ett sammansatt ord.","An s that sometimes joins the parts of a compound word.","حرف s يربط أحيانًا بين جزأي الكلمة المركّبة."),ex:"fotboll + s + lag = fotbollslag",tr:{en:"linking s",ar:"حرف s الرابط"}});
/* [förled, efterled, compound, en/ett, note: s = fog-s, a = förleden tappar -a] */
const CP=[["fjäll","stuga","fjällstuga","en"],["regn","jacka","regnjacka","en"],["vatten","flaska","vattenflaska","en"],["rygg","säck","ryggsäck","en"],["läger","skola","lägerskola","en"],
 ["snö","storm","snöstorm","en"],["kanel","bulle","kanelbulle","en"],["klass","kamrat","klasskamrat","en"],["fotboll","match","fotbollsmatch","en","s"],["dag","tur","dagstur","en","s"],
 ["sol","nedgång","solnedgång","en"],["fjäll","topp","fjälltopp","en"],["ficka","lampa","ficklampa","en","a"],["skola","gård","skolgård","en","a"],["hand","duk","handduk","en"],
 ["kök","bord","köksbord","ett","s"],["sommar","lov","sommarlov","ett"],["vissla","pipa","visselpipa","en","a"]];
const CPH={s:t3("Här behövs ett s i fogen, mellan orden.","Here you need an s in the joint, between the parts.","هنا نحتاج حرف s بين الجزأين."),a:t3("Förleden tappar sitt -a (eller ändras lite).","The first part drops its -a (or changes a little).","الجزء الأول يفقد حرف ‎-a (أو يتغيّر قليلًا)."),
 x:t3("Skriv ihop orden till ett ord, utan mellanslag.","Write the parts together as one word, with no space.","اكتب الجزأين كلمة واحدة بلا مسافة.")};
const mtn=(op=1)=>`<g opacity="${op}"><path d="M-10 230 L80 90 L150 200 L210 110 L310 230Z" fill="#8aa0b8"/><path d="M80 90 L58 124 L72 120 L84 130 L98 118Z M210 110 L192 138 L206 134 L216 142 L228 136Z" fill="#fff"/></g>`;
const cabin=(x,y,s=1)=>`<g transform="translate(${x} ${y}) scale(${s})"><rect x="-26" y="-20" width="52" height="34" fill="#c0392b"/><path d="M-32 -18 L0 -42 L32 -18Z" fill="#5b4636"/><rect x="-6" y="-2" width="12" height="16" fill="#fff"/><rect x="-20" y="-12" width="10" height="9" fill="#ffe28a"/></g>`;
const P8=[pic(`<circle cx="250" cy="50" r="22" fill="#ffd34d"/>${mtn()}<rect y="225" width="300" height="75" fill="#7cb46b"/><ellipse cx="200" cy="262" rx="80" ry="18" fill="#5aa0d8"/>${cabin(80,240,1.1)}`,"#cfe8fb"),
 pic(`<circle cx="60" cy="50" r="24" fill="#ffd34d"/><path d="M-10 300 L125 132 L175 132 L310 300Z" fill="#8aa0b8"/><path d="M125 132 L175 132 L190 150 L170 146 L150 158 L130 146 L110 150Z" fill="#fff"/>${kid(132,76,...AMIR,.5)}${kid(170,76,...SARA,.5)}<path d="M146 102 l-8 -24M184 102 l8 -24" stroke="#f1c7a3" stroke-width="6" stroke-linecap="round"/><path d="M20 260 L60 220 L100 260Z M200 270 L250 215 L300 270Z" fill="#a9bccf"/>`,"#cfe8fb"),
 pic(`${mtn(.45)}<rect y="225" width="300" height="75" fill="#b9c7b3"/>${kid(120,150,...AMIR,.7)}${kid(185,150,...SARA,.7)}${[60,120,180,240].map((y,i)=>`<rect x="${i%2?-40:-10}" y="${y}" width="360" height="34" rx="17" fill="#fff" opacity=".7"/>`).join("")}`,"#d6dde5"),
 pic(`<rect x="30" y="60" width="240" height="190" rx="6" fill="#f3e6c4" stroke="#c9ad7a" stroke-width="3"/><path d="M50 200 Q100 150 140 170 T250 110" stroke="#5aa0d8" stroke-width="5" fill="none"/><path d="M60 100 Q120 120 160 90" stroke="#a9bccf" stroke-width="4" fill="none" stroke-dasharray="8 6"/>${cabin(230,214,.6)}<circle cx="120" cy="170" r="50" fill="#fff" stroke="#33415c" stroke-width="6"/><path d="M120 128 L130 170 L120 212 L110 170Z" fill="#c6cfdc"/><path d="M120 128 L130 170 L110 170Z" fill="#d63b2f"/><circle cx="120" cy="170" r="4" fill="#33415c"/><text x="120" y="112" font-family="Caveat,cursive" font-weight="700" font-size="22" text-anchor="middle" fill="#1d2433">N</text>`,"#dbe8d0"),
 pic(`${[[40,40],[90,25],[160,50],[230,30],[270,70],[120,80]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="2.5" fill="#fff"/>`).join("")}<rect y="230" width="300" height="70" fill="#3d4a33"/>${kid(70,150,...AMIR,.75)}${kid(230,150,...SARA,.75)}<path d="M120 250 L150 200 L180 250Z" fill="#f2a64a"/><path d="M135 250 L150 222 L165 250Z" fill="#ffe28a"/><path d="M115 254h70" stroke="#8d6440" stroke-width="8" stroke-linecap="round"/>`,"#24304d")];
const U8={id:"sv7h",year:7,ord:8,title:t3("Vilse i fjällen","Lost in the mountains","تائهان في الجبال"),storyTitle:"Vilse i fjällen",
 icon:`<svg viewBox="0 0 320 180"><rect width="320" height="180" fill="#cfe8fb"/><path d="M-10 160 L90 40 L160 130 L220 60 L330 160Z" fill="#8aa0b8"/><path d="M90 40 L72 64 L86 60 L96 70 L106 58Z M220 60 L204 82 L216 78 L226 86 L236 80Z" fill="#fff"/><rect y="150" width="320" height="30" fill="#7cb46b"/>${[70,105].map((y,i)=>`<rect x="${i?40:-20}" y="${y}" width="300" height="22" rx="11" fill="#fff" opacity=".65"/>`).join("")}<circle cx="270" cy="128" r="26" fill="#fff" stroke="#33415c" stroke-width="4"/><path d="M270 106 L276 128 L264 128Z" fill="#d63b2f"/></svg>`,
 pic:pic(""),words:["fjall","stuga","utsikt","packning","dimma","vilse","kompass","modig"],terms:["sammansattord","forled","efterled","fogs"],
 story:[
  {text:["I september åkte 7B på lägerskola i fjällen. Klassen bodde i en stor stuga vid en sjö, och från fönstret hade man en fantastisk utsikt över bergen.", "Första morgonen kontrollerade Lena allas packning. ”Regnjacka, vattenflaska, matsäck och en extra tröja”, läste hon från listan. Amir hade packat noga. Ingenting fattades."],
   pic:P8[0],
   say:t3("En ny resa! Lägg märke till långa ord som ”regnjacka” och ”vattenflaska”. Vi tittar på dem sedan.","A new trip! Notice long words like ”regnjacka” and ”vattenflaska”. We'll look at them later.","رحلة جديدة! لاحظ الكلمات الطويلة مثل «regnjacka» و«vattenflaska». سننظر فيها لاحقًا.")},
  {text:["Klassen skulle vandra upp på ett fjäll och tillbaka. Tränaren från fotbollslaget var med som ledare. ”Håll ihop och följ ledarna”, sa han. ”Vädret kan ändras snabbt här uppe.”", "De gick i flera timmar. Benen var trötta, men utsikten från toppen fick alla att jubla. Sjöar, dalar och snöfläckar glittrade i solen."],
   pic:P8[1],
   say:t3("Tränaren varnar för vädret. Kom ihåg det när du läser vidare.","The coach warns about the weather. Remember that as you read on.","المدرب يحذّر من الطقس. تذكّر ذلك وأنت تتابع القراءة.")},
  {text:["På vägen ner stannade Amir och Sara för att fotografera en ren. När de tittade upp igen, kom en grå dimma rullande nerför fjället.", "Snart såg de bara några meter framåt. Resten av klassen var borta. ”Hallå!” ropade Sara. Inget svar. ”Vi har gått vilse”, sa Amir tyst."],
   pic:P8[2],
   say:t3("Vad händer när dimman kommer? Hur tror du att de känner sig?","What happens when the fog comes? How do you think they feel?","ماذا يحدث عندما يأتي الضباب؟ كيف تظن أنهما يشعران؟")},
  {text:["Amir kände hur han blev nervös. Hjärtat slog hårt. Men Sara satte sig på en sten och tog av sig ryggsäcken. ”Vi måste koncentrera oss”, sa hon. ”Panik hjälper inte.”", "Hon letade i sin packning och tog fram en kompass och en karta. ”Lena sa att alla skulle ha med sig en. Jag trodde aldrig att vi skulle behöva den.”"],
   pic:P8[3],
   say:t3("Sara är lugn fast det är farligt. Vad gör hon först?","Sara is calm even though it's dangerous. What does she do first?","سارة هادئة رغم الخطر. ماذا تفعل أولًا؟")},
  {text:["De bredde ut kartan på stenen. Stugan låg vid sjön, rakt söderut. ”Nålen pekar alltid mot norr”, förklarade Sara. ”Då ska vi gå åt motsatt håll.”", "Amir höll med. De gick långsamt och försiktigt, sten för sten. Varje gång de var osäkra, stannade de och tittade på kompassen igen."],
   pic:P8[3],
   say:t3("Hur hjälper kompassen dem att hitta rätt?","How does the compass help them find the way?","كيف تساعدهما البوصلة على إيجاد الطريق؟")},
  {text:["Efter en timme hörde de ett ljud genom dimman. Någon blåste i en visselpipa! ”Amir! Sara!” Det var tränaren.", "Han sprang fram och kramade dem. ”Vi har letat överallt”, sa han. ”Hur hittade ni hit?” Sara höll upp kompassen. ”Med den här.”"],
   pic:P8[2],
   say:t3("Vem hittar dem? Hur märks det att han har varit orolig?","Who finds them? How can you tell he has been worried?","من يجدهما؟ وكيف نعرف أنه كان قلقًا؟")},
  {text:["På kvällen satt hela klassen runt lägerelden utanför fjällstugan. Amir och Sara var utmattade men lättade. Lena berättade för alla hur de hade klarat sig.", "”Ni var modiga”, sa hon. ”Men ni var också kloka. Ni tappade inte huvudet, och ni använde kompassen rätt.” Amir log. Nästa gång skulle han ha en egen kompass i packningen."],
   pic:P8[4],
   say:t3("Lena säger att de var modiga och kloka. Vad är skillnaden?","Lena says they were brave and wise. What's the difference?","تقول لينا إنهما كانا شجاعين وحكيمين. ما الفرق؟")}],
 wordsSay:t3("Här är fjällorden. Tryck på ett ord för att se vad det betyder.","Here are the mountain words. Tap a word to see what it means.","هذه كلمات الجبال. اضغط على كلمة لترى معناها."),
 grammar:[
  {draw:()=>[A.wipe(),A.tx(L(t3("Sammansatta ord","Compound words","الكلمات المركّبة")),400,64,40,"b"),
    A.hl(470,130,250,70),A.tx("fjäll",150,180,54,"b"),A.tx("+",235,180,54),A.tx("stuga",320,180,54,"g"),A.tx("=",420,180,54),A.tx("fjäll",590,180,54,"b","end"),A.tx("stuga",590,180,54,"g","start"),
    qt("förled",150,232,26,"b"),qt("efterled",320,232,26,"g"),
    A.tx(L(t3("En fjällstuga är en stuga.","A fjällstuga is a stuga.","fjällstuga هي stuga.")),400,330,40,"k"),qt(L(t3("Efterleden säger vad det är.","The last part says what it is.","الجزء الأخير يقول ما هو الشيء.")),400,390,30,"g"),
    qt("ett fjäll + en stuga → en fjällstuga",400,450,28,"o")],
   say:t3("Svenska bygger ofta nya ord av två ord: fjäll + stuga = fjällstuga. Den sista delen, efterleden, säger vad det är. Den bestämmer också en eller ett: en stuga, alltså en fjällstuga.","Swedish often builds new words from two words: fjäll + stuga = fjällstuga. The last part says what it is. It also decides en or ett: en stuga, so en fjällstuga.","تبني السويدية كثيرًا كلمات جديدة من كلمتين: fjäll + stuga = fjällstuga. الجزء الأخير يحدّد ما هو الشيء، ويحدّد أيضًا en أو ett: en stuga، إذن en fjällstuga.")},
  {draw:()=>{const rows=[["regn","jacka"],["vatten","flaska"],["rygg","säck"],["läger","skola"],["snö","fläck"]];
    return[A.wipe(),A.tx(L(t3("Ord från berättelsen","Words from the story","كلمات من القصة")),400,60,36,"b"),...rows.flatMap(([a,b],i)=>[A.tx(`${a} + ${b}`,250,135+i*72,36,"k"),A.tx("→",400,135+i*72,36,"k"),A.tx(a,560,135+i*72,40,"b","end"),A.tx(b,560,135+i*72,40,"g","start")])]},
   say:t3("Titta: regnjacka, vattenflaska, ryggsäck, lägerskola, snöfläck. Förleden är blå, efterleden är grön. En regnjacka är en jacka, inte ett regn!","Look: regnjacka, vattenflaska, ryggsäck, lägerskola, snöfläck. The first part is blue, the last part green. A regnjacka is a jacket, not rain!","انظر: regnjacka، vattenflaska، ryggsäck، lägerskola، snöfläck. الجزء الأول أزرق والأخير أخضر. regnjacka سترة وليست مطرًا!")},
  {draw:()=>[A.wipe(),A.tx(L(t3("Fog-s och skriv ihop!","Linking s, and write it as one word!","حرف s الرابط، واكتبها كلمة واحدة!")),400,60,36,"b"),
    A.tx("fotboll + s + lag",400,140,40,"k"),A.tx("fotboll",420,210,46,"b","end"),A.tx("s",420,210,46,"r","start"),A.tx("lag",434,210,46,"g","start"),
    A.tx("✗  en fjäll stuga",400,310,40,"r"),A.tx("✓  en fjällstuga",400,380,40,"g"),A.p(R.line(300,300,560,300,.3),"r",3),
    qt("English: a mountain cabin (two words)",400,450,26,"k")],
   say:t3("Ibland kommer ett s mellan de två orden: fotbollslag. Och skriv alltid ihop! ”En fjäll stuga” är fel. På engelska skriver man ofta två ord. På arabiska kommer huvudordet först: كوخ الجبل. På svenska kommer det sist: fjällstuga.","Sometimes an s comes between the two words: fotbollslag. And always write it as one word! ”En fjäll stuga” is wrong. English often writes two words. In Arabic the main word comes first: كوخ الجبل. In Swedish it comes last: fjällstuga.","أحيانًا يأتي حرف s بين الكلمتين: fotbollslag. واكتبها دائمًا كلمة واحدة! «en fjäll stuga» خطأ. في الإنجليزية تُكتب غالبًا كلمتين. وفي العربية تأتي الكلمة الأساسية أولًا: كوخ الجبل، أما في السويدية فتأتي أخيرًا: fjällstuga.")}],
 read:[
  {q:"Var bodde klassen på lägerskolan?",o:["I en stor stuga vid en sjö.", "I tält på toppen av ett fjäll.", "På ett hotell i stan."],why:"Del 1: i en stor stuga vid en sjö."},
  {q:"Vad kontrollerade Lena första morgonen?",o:["Allas packning", "Allas mobiler", "Kartan till toppen"],why:"Del 1: Lena kontrollerade allas packning."},
  {q:"Varför stannade Amir och Sara på vägen ner?",o:["För att fotografera en ren.", "För att äta matsäck.", "För att Amir hade ont i foten."],why:"Del 3: för att fotografera en ren."},
  {q:"Varför gick de vilse?",o:["Dimman kom och de såg inte klassen längre.", "De gick åt fel håll med flit.", "Kartan blåste bort."],why:"Del 3: en grå dimma … resten av klassen var borta."},
  {q:"Vad gjorde Sara när de hade gått vilse?",o:["Hon satte sig och tog fram kompass och karta.", "Hon började springa.", "Hon ringde sin mamma."],why:"Del 4: Hon tog fram en kompass och en karta."},
  {q:"Åt vilket håll låg stugan?",o:["Söderut", "Norrut", "Österut"],why:"Del 5: rakt söderut."},
  {q:"Vad hörde de genom dimman?",o:["En visselpipa", "En helikopter", "En hund"],why:"Del 6: Någon blåste i en visselpipa."},
  {q:"Varför sa tränaren att vädret kan ändras snabbt?",o:["Han ville att alla skulle hålla ihop och vara beredda.", "Han ville att klassen skulle gå hem.", "Han trodde att det skulle bli varmt."],why:"Del 2: Håll ihop … vädret kan ändras snabbt."},
  {q:"Lena säger att de var kloka. Vad menar hon?",o:["De var lugna och gjorde rätt saker.", "De hade bäst betyg i klassen.", "De sprang snabbast."],why:"Del 7: Ni tappade inte huvudet och använde kompassen rätt."}],
 gram(lv,write){const [a,b,c,art,note]=pick(CP),hint={say:CPH[note||"x"],draw:[]};
  const head=t=>[A.wipe(),A.tx(L(t),400,80,34,"b")];
  if(write||lv===2)return{kind:"text",ans:[c],show:c,q:[...head(t3("Skriv ihop till ett ord","Write it as one word","اكتبها كلمة واحدة")),A.tx(`${a} + ${b} = ?`,400,230,56,"k")],sol:[A.tx(`${art} ${c}`,400,400,44,"g")],hint};
  if(lv===1&&Math.random()<.5){const other=pick(CP.filter(x=>x[1]!==b&&x[0]!==b&&x[1]!==a)),opts=shuffle([b,a,other[1]]);
   return{kind:"choice",opts,ans:opts.indexOf(b),show:b,q:[...head(t3("Vad är det? Titta på efterleden.","What is it? Look at the last part.","ما هو؟ انظر إلى الجزء الأخير.")),A.tx(`${cap(art)} ${c} är en sorts …`,400,230,50,"k")],
    sol:[A.tx(`${c} = ${a} + ${b}`,400,400,40,"g")],hint:{say:t3("Efterleden, den sista delen, säger vad det är.","The last part says what it is.","الجزء الأخير يقول ما هو الشيء."),draw:[]}}}
  const opts=shuffle([c,`${a} ${b}`,b+a]);
  return{kind:"choice",opts,ans:opts.indexOf(c),show:c,q:[...head(t3("Vilket ord är rätt skrivet?","Which word is written correctly?","أي كلمة مكتوبة بشكل صحيح؟")),A.tx(`${a} + ${b}`,400,230,56,"k")],sol:[A.tx(`${art} ${c}`,400,400,44,"g")],hint}},
 help:[{say:t3("Förled + efterled = ett ord. Efterleden säger vad det är: en fjällstuga är en stuga.","First part + last part = one word. The last part says what it is: a fjällstuga is a stuga.","الجزء الأول + الجزء الأخير = كلمة واحدة. الجزء الأخير يقول ما هو الشيء: fjällstuga هي stuga."),draw:()=>[A.tx("fjäll + stuga",400,200,50,"k"),A.tx("fjäll",400,300,56,"b","end"),A.tx("stuga",400,300,56,"g","start")]}]};
LESSONS.push(svUnit(U8));
}
