/* Svenska årskurs 7, units 9–10: Värmeböljan (a news text; prefix and suffix) and Den nya grannen (a story; synonyms and nuance). */
{const {rx,boxes,pic,kid,W,sent,cap}=SVH;

/* ---------------- unit 9: Värmeböljan (prefix och suffix) ---------------- */
W("svtemp",{sv:"temperatur (en)",m:rx("temperatur(en|er|erna)?"),d:t3("Hur varmt eller kallt något är. Den mäts i grader.","How warm or cold something is. It is measured in degrees.","مقدار حرارة الشيء أو برودته، وتُقاس بالدرجات."),ex:"Temperaturen var 32 grader.",tr:{en:"temperature",ar:"درجة الحرارة"},syn:["värmegrad"],wrong:["väder","vind"],gap:["I går var","temperaturen","32 grader i Stockholm."],gapForm:"temperaturen",form:"en temperatur – temperaturer"});
W("torka",{sv:"torka (en)",m:rx("(torkan?|torkor(na)?)"),d:t3("När det inte regnar på länge och marken blir torr.","When it doesn't rain for a long time and the ground gets dry.","عندما لا تمطر لمدة طويلة وتجفّ الأرض."),ex:"Torkan förstörde skörden.",tr:{en:"drought",ar:"جفاف"},syn:["torrperiod"],wrong:["storm","dimma"],gap:["Efter sex veckor utan regn blev det","torka","på åkrarna."],gapForm:"torka",form:"en torka – torkor"});
W("klimat",{sv:"klimat (ett)",m:rx("klimat(et)?"),d:t3("Hur vädret brukar vara på en plats under många år.","What the weather is usually like in a place over many years.","كيف يكون الطقس عادةً في مكان ما على مدى سنوات كثيرة."),ex:"Jordens klimat blir varmare.",tr:{en:"climate",ar:"مناخ"},gap:["Jordens","klimat","blir varmare och varmare."],gapForm:"klimat",form:"ett klimat – klimat"});
W("forskare",{sv:"forskare (en)",m:rx("forskar(e|en|na)"),d:t3("En person som undersöker saker för att få ny kunskap.","A person who studies things to find new knowledge.","شخص يدرس الأشياء ليصل إلى معرفة جديدة."),ex:"Forskaren studerar klimatet.",tr:{en:"researcher, scientist",ar:"باحث، عالِم"},syn:["vetenskapsman"],wrong:["bonde","reporter"],gap:["En","forskare","undersöker hur klimatet förändras."],gapForm:"forskare",form:"en forskare – forskare"});
W("varna",{sv:"varna",m:rx("(varna|varnar|varnade|varnat)"),d:t3("Säga till någon att något farligt kan hända.","Tell someone that something dangerous may happen.","أن تقول لشخص إن شيئًا خطيرًا قد يحدث."),ex:"Myndigheterna varnar för värmen.",tr:{en:"warn",ar:"يحذّر"},syn:["varsko"],wrong:["lova","fråga"],gap:["Myndigheterna","varnar","för den höga värmen."],gapForm:"varnar",form:"varna – varnade – har varnat"});
W("orsak",{sv:"orsak (en)",m:rx("orsak(en|er|erna)?"),d:t3("Det som gör att något händer.","What makes something happen.","ما يجعل شيئًا يحدث."),ex:"Vad är orsaken till värmen?",tr:{en:"cause, reason",ar:"سبب"},syn:["anledning","skäl"],opp:["följd"],wrong:["regel","början"],gap:["En värmebölja kan ha flera","orsaker","."],gapForm:"orsaker",form:"en orsak – orsaker"});
W("foljd",{sv:"följd (en)",m:rx("följd(en|er|erna)?"),d:t3("Det som händer på grund av något annat.","What happens because of something else.","ما يحدث بسبب شيء آخر."),ex:"Torkan är en följd av värmen.",tr:{en:"consequence, result",ar:"نتيجة، عاقبة"},syn:["konsekvens","resultat"],opp:["orsak"],wrong:["början","fråga"],gap:["Torkan är en","följd","av att det inte regnar."],gapForm:"följd",form:"en följd – följder"});
W("minska",{sv:"minska",m:rx("(minska|minskar|minskade|minskat)"),d:t3("Bli mindre, eller göra något mindre.","Become smaller, or make something smaller.","أن يصبح الشيء أقل، أو أن تجعله أقل."),ex:"Vi måste minska utsläppen.",tr:{en:"reduce, decrease",ar:"يقلّل، يقلّ"},syn:["sänka","dra ner på"],opp:["öka"],wrong:["måla","glömma"],gap:["Vi kan","minska","utsläppen om vi cyklar mer."],gapForm:"minska",form:"minska – minskade – har minskat"});
W("svprefix",{sv:"prefix",m:rx("prefix(et|en)?"),d:t3("En liten del som sätts först i ett ord och ändrar betydelsen.","A small part put at the start of a word that changes its meaning.","جزء صغير يوضع في أول الكلمة فيغيّر معناها."),ex:"o + vanlig = ovanlig",tr:{en:"prefix",ar:"سابقة"}});
W("svsuffix",{sv:"suffix",m:rx("suffix(et|en)?"),d:t3("En liten del som sätts sist i ett ord och gör ett nytt ord.","A small part put at the end of a word that makes a new word.","جزء صغير يوضع في آخر الكلمة فيصنع كلمة جديدة."),ex:"forska + are = forskare",tr:{en:"suffix",ar:"لاحقة"}});
W("ordstam",{sv:"ordstam",m:rx("ordstam(men)?"),d:t3("Ordets kärna, den del som inte ändras.","The core of the word, the part that does not change.","أصل الكلمة، الجزء الذي لا يتغيّر."),ex:"forsk- i forska, forskare, forskning",tr:{en:"word stem",ar:"جذر الكلمة"}});
/* derived words: [base, prefix/suffix, new word, meaning, sentence] (o- and -lig make adjectives, the others nouns) */
const AFF=[["vanlig","o-","ovanlig","inte vanlig","En värmebölja i maj är ____ i Sverige."],["säker","o-","osäker","inte säker","Forskarna är ____ på hur varm sommaren blir."],
 ["möjlig","o-","omöjlig","inte möjlig","Det var nästan ____ att sova i värmen."],["lycklig","o-","olycklig","inte lycklig","Bonden var ____ när regnet aldrig kom."],
 ["säker","-het","säkerhet","det att vara säker","För din egen ____ ska du dricka mycket vatten."],["ny","-het","nyhet","något nytt som man berättar om","Värmen var dagens största ____ i tidningen."],
 ["ärlig","-het","ärlighet","det att vara ärlig","Lena tycker att ____ är viktigare än höga betyg."],
 ["varna","-ning","varning","det att man varnar","SMHI gav en ____ för höga temperaturer."],["minska","-ning","minskning","det att något blir mindre","Forskarna vill se en ____ av utsläppen."],
 ["öka","-ning","ökning","det att något blir större","Det blev en stor ____ av besökare på stranden."],["ändra","-ning","ändring","det att något blir annorlunda","Lena gjorde en ____ i schemat."],
 ["forska","-are","forskare","en som forskar","En ____ undersöker hur klimatet förändras."],["läsa","-are","läsare","en som läser","Många ____ skrev brev till tidningen."],
 ["simma","-are","simmare","en som simmar","En snabb ____ simmade ut till bryggan."],["spela","-are","spelare","en som spelar","Varje ____ i laget fick en flaska vatten."],
 ["fara","-lig","farlig","full av fara","Värmen kan vara ____ för gamla människor."],["dag","-lig","daglig","som händer varje dag","Tidningen hade en ____ rapport om vädret."],
 ["vän","-lig","vänlig","snäll, som en vän","Den nya grannen var ____ mot alla."],["år","-lig","årlig","som händer varje år","Midsommar är en ____ händelse."]];
const AFFS=["o-","-het","-ning","-are","-lig"],ADJ=a=>a==="o-"||a==="-lig";
const sumOf=([base,aff])=>aff==="o-"?`o + ${base}`:`${base} + ${aff.slice(1)}`;
const sky=(s="#ffe08a")=>`<circle cx="240" cy="62" r="34" fill="${s}"/>${[0,1,2,3,4,5,6,7].map(i=>{const a=i*Math.PI/4;return`<path d="M${240+Math.cos(a)*42} ${62+Math.sin(a)*42}L${240+Math.cos(a)*54} ${62+Math.sin(a)*54}" stroke="#f2b330" stroke-width="5" stroke-linecap="round"/>`}).join("")}`;
const thermo=(x,y,t)=>`<rect x="${x-9}" y="${y}" width="18" height="110" rx="9" fill="#fff" stroke="#33415c" stroke-width="3"/><rect x="${x-4}" y="${y+18}" width="8" height="84" fill="#d63b2f"/><circle cx="${x}" cy="${y+112}" r="15" fill="#d63b2f" stroke="#33415c" stroke-width="3"/><text x="${x+18}" y="${y+28}" font-size="22" font-weight="700" fill="#d63b2f">${t}°</text>`;
const PI=[pic(`<rect x="30" y="40" width="150" height="120" rx="6" fill="#bfe0f5" stroke="#33415c" stroke-width="4"/><path d="M105 40v120M30 100h150" stroke="#33415c" stroke-width="4"/><circle cx="148" cy="72" r="20" fill="#ffd34d"/>${thermo(230,40,31)}<rect y="230" width="300" height="70" fill="#d9c3a0"/>${kid(90,190,"#2a7d9c","#3b2a1e",.75)}${kid(200,200,"#d35f8d","#7a3b1e",.7)}`,"#fff3e0"),
 pic(`${sky()}<rect x="40" y="110" width="220" height="160" rx="6" fill="#fff" stroke="#33415c" stroke-width="3"/><rect x="56" y="124" width="188" height="34" fill="#d63b2f"/><text x="150" y="149" font-size="20" font-weight="700" fill="#fff" text-anchor="middle">VÄRMEBÖLJA!</text>${[0,1,2,3,4].map(i=>`<rect x="56" y="${172+i*18}" width="${i%2?110:120}" height="8" rx="3" fill="#c6cfdc"/>`).join("")}${thermo(212,166,32).replace(/height="110"/,'height="60"').replace(/height="84"/,'height="40"').replace(/cy="278"/,'cy="228"')}`,"#fff3e0"),
 pic(`${sky()}<rect y="170" width="300" height="130" fill="#d8b878"/><path d="M20 210l40 10 20 30M120 190l-10 40 40 20M200 200l30 30-10 40M250 180l20 40" stroke="#8d6440" stroke-width="3" fill="none"/>${[50,130,210].map(x=>`<path d="M${x} 170v-40" stroke="#9a8a3a" stroke-width="4"/><path d="M${x} 140q-18 6-20 26M${x} 132q16 4 20 24" stroke="#b5a24a" stroke-width="4" fill="none"/>`).join("")}`,"#fde9c8"),
 pic(`<rect x="30" y="40" width="240" height="150" rx="8" fill="#fff" stroke="#33415c" stroke-width="3"/><path d="M50 170h200M50 170v-115" stroke="#33415c" stroke-width="3"/><path d="M55 160l30-8 30 4 30-14 30-6 30-22 30-40" stroke="#d63b2f" stroke-width="5" fill="none" stroke-linejoin="round"/><circle cx="255" cy="70" r="7" fill="#d63b2f"/>${kid(150,215,"#ffffff","#2b2b2b",.65)}<rect x="125" y="226" width="50" height="40" rx="8" fill="#eef4fb" stroke="#33415c" stroke-width="2"/><circle cx="60" cy="245" r="28" fill="#5aa0d8"/><path d="M42 236q10-10 20 0t16 6M48 258q10-6 22 2" stroke="#7cc08a" stroke-width="6" fill="none" stroke-linecap="round"/>`,"#eef4fb"),
 pic(`${sky()}<path d="M40 90l50-80 50 80z" fill="#ffd34d" stroke="#d63b2f" stroke-width="7" stroke-linejoin="round"/><text x="90" y="80" font-size="44" font-weight="700" fill="#1d2433" text-anchor="middle">!</text><rect y="230" width="300" height="70" fill="#9fcf8f"/><rect x="190" y="130" width="16" height="110" fill="#8d6440"/><circle cx="198" cy="120" r="56" fill="#5fae5a"/>${kid(150,170,"#7cc08a","#5b4636",.7)}<rect x="230" y="200" width="22" height="40" rx="6" fill="#bfe0f5" stroke="#2257c9" stroke-width="3"/><rect x="235" y="192" width="12" height="10" fill="#2257c9"/>`,"#fff3e0"),
 pic(`<rect y="220" width="300" height="80" fill="#c6cfdc"/><path d="M0 250h300" stroke="#fff" stroke-width="5" stroke-dasharray="20 16"/><circle cx="90" cy="200" r="34" fill="none" stroke="#1d2433" stroke-width="6"/><circle cx="210" cy="200" r="34" fill="none" stroke="#1d2433" stroke-width="6"/><path d="M90 200l40-50h60l20 50M130 150l-10-20h-20M190 150l-6-24h22" stroke="#2a7d9c" stroke-width="7" fill="none" stroke-linejoin="round" stroke-linecap="round"/><rect x="200" y="40" width="12" height="80" fill="#8d6440"/><circle cx="206" cy="40" r="40" fill="#7cc08a"/><text x="70" y="90" font-size="46" font-weight="700" fill="#1e9e5a">CO₂ ↓</text>`,"#e7f6ec"),
 pic(`<rect x="30" y="30" width="240" height="110" rx="6" fill="#2f4a3a"/><path d="M150 45v80" stroke="#fff" stroke-width="3"/><text x="90" y="70" font-family="Caveat,cursive" font-size="28" fill="#ffd34d" text-anchor="middle">orsak</text><text x="210" y="70" font-family="Caveat,cursive" font-size="28" fill="#7cc08a" text-anchor="middle">följd</text><path d="M60 95h60M60 115h50M180 95h60M180 115h40" stroke="#fff" stroke-width="3"/>${kid(90,180,"#2a7d9c","#3b2a1e",.8)}${kid(210,180,"#d35f8d","#7a3b1e",.8)}<path d="M185 175l-16-34" stroke="#f1c7a3" stroke-width="10" stroke-linecap="round"/>`,"#fff3e0")];
const U9={id:"sv7i",year:7,ord:9,title:t3("Värmeböljan","The heatwave","موجة الحر"),storyTitle:"Värmebölja slår rekord",
 icon:`<svg viewBox="0 0 320 180"><rect width="320" height="180" fill="#fff3e0"/><circle cx="250" cy="56" r="30" fill="#ffd34d"/>${[0,1,2,3,4,5,6,7].map(i=>{const a=i*Math.PI/4;return`<path d="M${250+Math.cos(a)*38} ${56+Math.sin(a)*38}L${250+Math.cos(a)*50} ${56+Math.sin(a)*50}" stroke="#f2b330" stroke-width="5" stroke-linecap="round"/>`}).join("")}<rect y="130" width="320" height="50" fill="#d8b878"/><path d="M30 150l30 8 16 18M150 140l-8 30M220 150l26 20" stroke="#8d6440" stroke-width="3" fill="none"/><rect x="60" y="30" width="20" height="96" rx="10" fill="#fff" stroke="#33415c" stroke-width="3"/><rect x="66" y="46" width="8" height="70" fill="#d63b2f"/><circle cx="70" cy="126" r="15" fill="#d63b2f" stroke="#33415c" stroke-width="3"/><text x="160" y="100" font-family="Caveat,cursive" font-weight="700" font-size="48" fill="#d63b2f" text-anchor="middle">32°</text></svg>`,
 pic:pic(""),words:["svtemp","torka","klimat","forskare","varna","orsak","foljd","minska"],terms:["svprefix","svsuffix","ordstam"],
 story:[
  {text:["Det var bara slutet av maj, men temperaturen i klassrummet var redan 31 grader. Fönstren stod öppna, och ingen i 7B orkade tänka på matte.", "Tränaren hade skickat ett sms: Ingen träning i dag, det är för varmt. ”Skönt”, suckade Amir. ”Jag var utmattad redan efter lunchen.” Då delade Lena ut en artikel ur tidningen. ”Vi läser den tillsammans”, sa hon."],
   pic:PI[0],
   say:t3("Nu läser vi en nyhetsartikel. En nyhet berättar om något som har hänt, med fakta och siffror.","Now we read a news article. News tells about something that has happened, with facts and numbers.","الآن نقرأ مقالًا إخباريًا. الخبر يحكي عن شيء حدث، بالحقائق والأرقام.")},
  {text:["Rubriken var stor och röd: VÄRMEBÖLJA – NYTT REKORD I MAJ.", "I går mätte SMHI en temperatur på 32 grader i Stockholm. Så varmt har det aldrig varit så tidigt på året. Värmen ska fortsätta hela veckan, och många invånare har märkt att det är svårt att sova på nätterna."],
   pic:PI[1],
   say:t3("En nyhet börjar med det viktigaste: vad, var och när. Hitta de tre sakerna här.","A news text starts with the most important things: what, where and when. Find those three here.","يبدأ الخبر بأهم شيء: ماذا وأين ومتى. ابحث عن هذه الأشياء الثلاثة هنا.")},
  {text:["Värmen har också gett torka i stora delar av landet. Det har knappt regnat sedan april. På åkrarna i Skåne är jorden hård och sprucken.", "”Om det inte regnar snart förlorar vi halva skörden”, säger bonden Karin Ek. Risken för bränder är hög, och det är förbjudet att grilla i skogen."],
   pic:PI[2],
   say:t3("Torka betyder att det inte regnar på länge. Vad händer med åkrarna?","Drought means it doesn't rain for a long time. What happens to the fields?","الجفاف يعني أنها لا تمطر لمدة طويلة. ماذا يحدث للحقول؟")},
  {text:["Varför blir det så här? En värmebölja kan ha flera orsaker. Ett högtryck har stått stilla över Sverige i två veckor och stängt ute regnet.", "Men forskare ser också ett mönster. ”Jordens klimat blir varmare, och då blir värmeböljor vanligare och längre”, säger forskaren Ali Hassan. ”Det är en följd av att vi släpper ut för mycket koldioxid.”"],
   pic:PI[3],
   say:t3("Orsak är det som gör att något händer. Följd är det som händer sedan. Vilka orsaker står det om?","A cause makes something happen. A consequence is what happens next. Which causes does the text mention?","السبب هو ما يجعل الشيء يحدث، والنتيجة هي ما يحدث بعده. ما الأسباب المذكورة في النص؟")},
  {text:["Myndigheterna varnar nu för värmen. Den kan vara farlig, särskilt för små barn, gamla och sjuka.", "Råden är enkla: drick mycket vatten, håll dig i skuggan mitt på dagen och var försiktig med hård träning. Den som känner sig yr eller ovanligt trött ska vila direkt."],
   pic:PI[4],
   say:t3("Ovanligt betyder inte vanligt. Bokstaven o först gör ordet till sin motsats. Det tittar vi på sedan.","Ovanligt means not usual. The letter o at the start turns the word into its opposite. We'll look at that later.","«ovanligt» تعني غير عادي. الحرف o في البداية يقلب معنى الكلمة. سنرى ذلك لاحقًا.")},
  {text:["Kan vi göra något? Forskarna säger att det är avgörande att minska utsläppen de närmaste åren.", "Det betyder färre bilresor, mer cykling och buss, och att vi slösar mindre energi. ”Varje liten minskning räknas”, säger Ali Hassan. ”Men det måste hända både hemma, i skolan och i politiken.”"],
   pic:PI[5],
   say:t3("Vad kan man göra för att minska utsläppen? Räkna upp tre saker från texten.","What can people do to reduce emissions? List three things from the text.","ماذا يمكن أن نفعل لتقليل الانبعاثات؟ اذكر ثلاثة أشياء من النص.")},
  {text:["Det blev tyst i klassen. Sedan räckte Sara upp handen. ”Vi kan ju cykla till träningen i stället för att åka bil”, sa hon. ”Det är en liten sak, men ändå.”", "Lena log. ”Bra! Läs texten en gång till. Vilka orsaker och vilka följder står det om?” Amir ritade två kolumner i sitt block och började skriva."],
   pic:PI[6],
   say:t3("Gör som Amir: tänk på en orsak och en följd från texten.","Do as Amir does: think of one cause and one consequence from the text.","افعل مثل أمير: فكّر في سبب ونتيجة من النص.")}],
 wordsSay:t3("Här är de nya orden. Många av dem är vanliga i nyheter och faktatexter. Tryck på dem!","Here are the new words. Many of them are common in news and factual texts. Tap them!","هذه هي الكلمات الجديدة. كثير منها شائع في الأخبار والنصوص العلمية. اضغط عليها!"),
 grammar:[
  {draw:()=>[A.wipe(),A.tx(L(t3("Nya ord av gamla","New words from old ones","كلمات جديدة من كلمات قديمة")),400,60,38,"b"),...boxes([["o","r","prefix"],["vanlig","b","ordstam"]],170,48),A.tx("= ovanlig  (inte vanlig)",400,268,34,"g"),
    ...boxes([["forsk","b","ordstam"],["are","o","suffix"]],370,48),A.tx("= forskare  (en som forskar)",400,466,34,"g")],
   say:t3("Ett prefix sätts först i ordet, ett suffix sist. Då får man ett nytt ord. I texten: ovanligt trött och forskare.","A prefix goes at the start of a word, a suffix at the end. Then you get a new word. In the text: ovanligt trött and forskare.","السابقة توضع في أول الكلمة، واللاحقة في آخرها، فنحصل على كلمة جديدة. في النص: ovanligt trött وforskare.")},
  {draw:()=>{const C=[130,390,650],rows=[["-are","forska → forskare","person","o"],["-ning","varna → varning","substantiv","b"],["-het","säker → säkerhet","substantiv","g"],["-lig","fara → farlig","adjektiv","r"]];
    return[A.wipe(),...[t3("suffix","suffix","اللاحقة"),t3("exempel","example","مثال"),t3("ger","makes","تصنع")].map((h,i)=>qt(L(h),C[i],80,26,"k")),A.p(R.line(60,100,740,100,.3),"k",2),
     ...rows.flatMap(([s,e,k,c],j)=>[A.tx(s,C[0],170+j*85,44,c),A.tx(e,C[1],170+j*85,34,"k"),A.tx(k,C[2],170+j*85,32,c)])]},
   say:t3("Med -are blir ett verb en person: forska – forskare. Med -ning och -het blir det ett substantiv: varna – varning. Med -lig blir det ett adjektiv: fara – farlig.","With -are a verb becomes a person: forska – forskare. With -ning and -het you get a noun: varna – varning. With -lig you get an adjective: fara – farlig.","مع ‎-are يصبح الفعل شخصًا: forska – forskare. ومع ‎-ning و‎-het نحصل على اسم: varna – varning. ومع ‎-lig نحصل على صفة: fara – farlig.")},
  {draw:()=>[A.wipe(),A.tx(L(t3("o- betyder ”inte”","o- means ”not”","o- تعني «غير»")),400,70,40,"r"),...[["vanlig","ovanlig"],["säker","osäker"],["möjlig","omöjlig"]].flatMap(([a,b],j)=>[A.tx(a,250,170+j*80,40,"b"),A.arrow(330,160+j*80,420,160+j*80,"k"),A.tx(b,550,170+j*80,42,"r")]),
    A.tx("un-usual · un-sure · im-possible",400,440,30,"k"),A.hl(150,404,500,52)],
   say:t3("Bokstaven o först betyder inte: osäker är inte säker. På engelska säger man un- eller im-. På arabiska säger man غير före ordet, men på svenska sitter o- ihop med ordet.","The letter o at the start means not: osäker is not sure. In English you use un- or im-. In Arabic you put غير before the word, but in Swedish o- is joined to the word.","الحرف o في البداية يعني «غير»: osäker تعني غير متأكد. بالإنجليزية نستخدم un- أو im-. وبالعربية نقول «غير» قبل الكلمة، أما بالسويدية فإن o- تلتصق بالكلمة نفسها.")}],
 read:[
  {q:"Hur varmt var det i Stockholm i går, enligt artikeln?",o:["32 grader","31 grader","23 grader"],why:"Del 2: en temperatur på 32 grader i Stockholm."},
  {q:"Varför blev det ingen träning för Amir och Sara?",o:["Det var för varmt.","Tränaren var sjuk.","Det regnade för mycket."],why:"Del 1: Ingen träning i dag, det är för varmt."},
  {q:"Varför är bönderna i Skåne oroliga?",o:["Torkan kan förstöra skörden.","Det regnar för mycket.","De får inte grilla."],why:"Del 3: Om det inte regnar snart förlorar vi halva skörden."},
  {q:"Vilken orsak till värmeböljan står det om först?",o:["Ett högtryck som har stått stilla","Bränder i skogen","För många bilar i Skåne"],why:"Del 4: Ett högtryck har stått stilla i två veckor."},
  {q:"Varför blir värmeböljor vanligare, enligt forskaren?",o:["Jordens klimat blir varmare.","Det finns fler bönder.","Solen har kommit närmare jorden."],why:"Del 4: Jordens klimat blir varmare."},
  {q:"För vilka är värmen särskilt farlig?",o:["Små barn, gamla och sjuka","Bönder och forskare","Fotbollsspelare"],why:"Del 5: särskilt för små barn, gamla och sjuka."},
  {q:"Vad säger forskarna att det är avgörande att göra?",o:["Minska utsläppen","Bygga fler badhus","Sluta läsa nyheter"],why:"Del 6: avgörande att minska utsläppen."},
  {q:"Varför är det förbjudet att grilla i skogen, tror du?",o:["Allt är så torrt att det lätt kan börja brinna.","Det är för varmt att äta.","Bönderna vill ha lugn och ro."],why:"Del 3: Risken för bränder är hög, eftersom det är så torrt."},
  {q:"Vad menar Sara med ”Det är en liten sak, men ändå”?",o:["Att cykla hjälper lite, och det är bättre än inget.","Att det inte spelar någon roll vad man gör.","Att träningen är för kort."],why:"Hon vet att en cykeltur inte räcker, men varje minskning räknas."}],
 gram(lv,write){const r=pick(AFF),[base,aff,word,mean,frame]=r,isAff=a=>a===aff;
  const sol=[A.tx(`${base} → ${word}`,400,400,40,"g"),...svLines(frame.replace("____",word),450,28,"g",44)];
  if(write||lv===2)return{kind:"text",ans:[word],show:word,q:[A.wipe(),A.tx(L(t3("Gör ett nytt ord. Skriv det.","Make a new word. Write it.","كوّن كلمة جديدة واكتبها.")),400,70,34,"b"),A.tx(sumOf(r),400,170,56,"o"),A.tx(`(${mean})`,400,250,32,"k")],
   sol,hint:{say:aff==="o-"?t3("Sätt o först, ihop med ordet.","Put o first, joined to the word.","ضع o في البداية ملتصقة بالكلمة."):t3("Sätt "+aff.slice(1)+" sist. Om verbet slutar på -a försvinner a:et: forska → forskare.","Put "+aff.slice(1)+" at the end. If the verb ends in -a, the a disappears: forska → forskare.","ضع "+aff.slice(1)+" في النهاية. إذا انتهى الفعل بـ ‎-a يسقط حرف a: forska → forskare."),draw:[]}};
  if(lv===1&&Math.random()<.35){const opts=shuffle([aff,...shuffle(AFFS.filter(a=>!isAff(a))).slice(0,2)]);
   return{kind:"choice",opts,ans:opts.indexOf(aff),show:aff,q:[A.wipe(),A.tx(L(t3("Vilket prefix eller suffix har ordet?","Which prefix or suffix does the word have?","ما السابقة أو اللاحقة في هذه الكلمة؟")),400,80,32,"b"),A.tx(word,400,210,64,"o"),A.tx(`(${mean})`,400,290,30,"k")],
    sol:[A.tx(`${base} → ${word}`,400,420,40,"g")],hint:{say:t3("Leta efter ordet "+base+" inne i "+word+". Vad är kvar?","Look for the word "+base+" inside "+word+". What is left?","ابحث عن الكلمة "+base+" داخل "+word+". ما الذي يبقى؟"),draw:[]}}}
  if(lv===1){const others=shuffle(AFF.filter(x=>ADJ(x[1])!==ADJ(aff))).slice(0,2).map(x=>x[2]),opts=shuffle([word,...others]);
   return{kind:"choice",opts,ans:opts.indexOf(word),show:word,q:[A.wipe(),A.tx(L(t3("Vilket ord passar i luckan?","Which word fits the gap?","أي كلمة تناسب الفراغ؟")),400,70,34,"b"),...svLines(frame,200,38)],
    sol,hint:{say:ADJ(aff)?t3("Luckan behöver ett adjektiv, ett ord som beskriver.","The gap needs an adjective, a describing word.","الفراغ يحتاج إلى صفة، كلمة تصف."):t3("Luckan behöver ett substantiv, en sak eller en person.","The gap needs a noun, a thing or a person.","الفراغ يحتاج إلى اسم، شيء أو شخص."),draw:[]}}}
  const others=shuffle(AFF.filter(x=>x[0]!==base&&x[2]!==word)).slice(0,2).map(x=>x[2]),opts=shuffle([word,...others]);
  return{kind:"choice",opts,ans:opts.indexOf(word),show:word,q:[A.wipe(),A.tx(L(t3("Vilket ord betyder:","Which word means:","أي كلمة تعني:")),400,90,34,"b"),A.tx(`”${mean}”`,400,200,46,"o")],
   sol,hint:{say:t3("o- betyder inte, -are är en person, -lig beskriver, -ning och -het är saker.","o- means not, -are is a person, -lig describes, -ning and -het are things.","o- تعني غير، و‎-are شخص، و‎-lig تصف، و‎-ning و‎-het أشياء."),draw:[]}}},
 help:[{say:t3("Prefix först, suffix sist: o + vanlig = ovanlig, forska + are = forskare.","Prefix first, suffix last: o + vanlig = ovanlig, forska + are = forskare.","السابقة في الأول واللاحقة في الآخر: o + vanlig = ovanlig وforska + are = forskare."),draw:()=>[A.tx("o + vanlig = ovanlig",400,180,46,"r"),A.tx("forska + are = forskare",400,300,46,"o")]}]};
LESSONS.push(svUnit(U9));

/* ---------------- unit 10: Den nya grannen (synonymer och nyanser) ---------------- */
W("granne",{sv:"granne (en)",m:rx("grann(e|en|ar|arna)"),d:t3("En som bor nära dig, till exempel i samma hus.","Someone who lives near you, for example in the same building.","شخص يسكن قريبًا منك، مثلًا في المبنى نفسه."),ex:"Vår nya granne heter Mira.",tr:{en:"neighbour",ar:"جار"},syn:["den som bor bredvid"],wrong:["lärare","tränare"],gap:["Vi fick en ny","granne","i lägenheten bredvid."],gapForm:"granne",form:"en granne – grannar"});
W("blyg",{sv:"blyg",m:rx("blyg(t|a)?"),d:t3("Lite rädd för att prata med människor man inte känner.","A little afraid of talking to people you don't know.","يخاف قليلًا من الكلام مع أشخاص لا يعرفهم."),ex:"Mira var blyg första dagen.",tr:{en:"shy",ar:"خجول"},syn:["tillbakadragen"],opp:["pratsam"],wrong:["arg","hungrig"],gap:["Hon var för","blyg","för att säga något."],gapForm:"blyg",form:"blyg – blygt – blyga"});
W("viska",{sv:"viska",m:rx("(viska|viskar|viskade|viskat)"),d:t3("Prata mycket tyst.","Speak very quietly.","أن تتكلم بصوت منخفض جدًا."),ex:"”Mira”, viskade hon.",tr:{en:"whisper",ar:"يهمس"},syn:["tala tyst"],opp:["skrika"],wrong:["springa","sova"],gap:["På biblioteket måste man","viska","."],gapForm:"viska",form:"viska – viskade – har viskat"});
W("rusa",{sv:"rusa",m:rx("(rusa|rusar|rusade|rusat)"),d:t3("Springa mycket fort, ofta plötsligt.","Run very fast, often suddenly.","أن تجري بسرعة كبيرة، غالبًا فجأة."),ex:"De rusade ut i trappan.",tr:{en:"rush, dash",ar:"يندفع مسرعًا"},syn:["springa fort"],opp:["gå långsamt"],wrong:["sitta","sova"],gap:["När larmet gick började alla","rusa","mot dörren."],gapForm:"rusa",form:"rusa – rusade – har rusat"});
W("smyga",{sv:"smyga",m:rx("(smyga|smyger|smög|smugit)"),d:t3("Gå tyst och försiktigt så att ingen märker en.","Walk quietly and carefully so that nobody notices you.","أن تمشي بهدوء وحذر حتى لا يلاحظك أحد."),ex:"Amir smög ut på balkongen.",tr:{en:"sneak, creep",ar:"يتسلّل"},syn:["tassa"],opp:["klampa"],wrong:["skrika","äta"],gap:["Katten","smög","försiktigt mot fågeln."],gapForm:"smög",form:"smyga – smög – har smugit"});
W("ensam",{sv:"ensam",m:rx("ensam(t|ma)?"),d:t3("Utan andra människor, eller utan vänner.","Without other people, or without friends.","من دون أشخاص آخرين، أو من دون أصدقاء."),ex:"Mira satt ensam på balkongen.",tr:{en:"alone, lonely",ar:"وحيد"},syn:["för sig själv"],opp:["tillsammans"],wrong:["trött","rik"],gap:["Hon satt","ensam","på balkongen och spelade."],gapForm:"ensam",form:"ensam – ensamt – ensamma"});
W("nyfiken",{sv:"nyfiken",m:rx("nyfik(en|et|na)"),d:t3("Vill gärna veta eller se något.","Really wants to know or see something.","يرغب كثيرًا في أن يعرف أو يرى شيئًا."),ex:"Amir var nyfiken på grannen.",tr:{en:"curious",ar:"فضولي"},syn:["intresserad"],opp:["ointresserad"],wrong:["lat","ledsen"],gap:["Amir var","nyfiken","på vem som skulle flytta in."],gapForm:"nyfiken",form:"nyfiken – nyfiket – nyfikna"});
W("lita",{sv:"lita på",m:rx("(lita|litar|litade|litat) på"),d:t3("Vara säker på att någon är ärlig och vill hjälpa dig.","Be sure that someone is honest and wants to help you.","أن تكون متأكدًا أن شخصًا صادق ويريد مساعدتك."),ex:"Du kan lita på oss.",tr:{en:"trust",ar:"يثق بـ"},syn:["tro på"],opp:["misstro"],wrong:["vänta på","titta på"],gap:["Du kan","lita på","oss."],gapForm:"lita på",form:"lita – litade – har litat"});
W("svsynonym",{sv:"synonym",m:rx("synonym(en|er|erna)?"),d:t3("Ett ord som betyder ungefär samma sak som ett annat ord.","A word that means about the same as another word.","كلمة تعني تقريبًا ما تعنيه كلمة أخرى."),ex:"rusa ≈ springa fort",tr:{en:"synonym",ar:"مرادف"}});
W("svnyans",{sv:"nyans",m:rx("nyans(en|er|erna)?"),d:t3("En liten skillnad i betydelse eller känsla.","A small difference in meaning or feeling.","فرق صغير في المعنى أو الإحساس."),ex:"viska – säga – skrika",tr:{en:"nuance, shade of meaning",ar:"فرق دقيق في المعنى"}});
/* the right verb for the situation: [sentence, right (past), wrong, wrong, infinitive, meaning] */
const NU=[["Lillasyster sov, så Amir ____ : ”God natt.”","viskade","skrek","ropade","viska","säga mycket tyst"],
 ["Sara stod på andra sidan gården och ____ : ”Kom hit!”","ropade","viskade","mumlade","ropa","säga högt så att någon långt bort hör"],
 ["Mira blev rädd och ____ högt när katten försvann.","skrek","viskade","mumlade","skrika","ropa mycket högt, ofta av rädsla"],
 ["Han ____ tyst och otydligt, så ingen förstod.","mumlade","ropade","skrek","mumla","säga något tyst och otydligt"],
 ["Publiken ____ av glädje när bollen gick in.","jublade","viskade","mumlade","jubla","ropa och skrika av glädje"],
 ["Amir ____ förbi den sovande hunden.","smög","rusade","sprang","smyga","gå tyst och försiktigt"],
 ["Bussen skulle gå om en minut, så Sara ____ till hållplatsen.","rusade","smög","promenerade","rusa","springa mycket fort"],
 ["Det var söndag, och de ____ lugnt längs vattnet.","promenerade","rusade","smög","promenera","gå långsamt för att det är skönt"],
 ["Brandlarmet tjöt, och alla ____ ut på skolgården.","rusade","smög","promenerade","rusa","springa mycket fort"],
 ["Amir ville inte väcka mamma, så han ____ in i köket.","smög","rusade","sprang","smyga","gå tyst och försiktigt"],
 ["Mira ____ snabbt ut genom gardinen för att se vem det var.","kikade","stirrade","rusade","kika","titta snabbt och lite i smyg"],
 ["Amir ____ på mattetalet i tio minuter utan att förstå.","stirrade","kikade","smög","stirra","titta länge utan att titta bort"]];
const PJ=[pic(`<rect x="20" y="40" width="160" height="210" fill="#e9b98f" stroke="#33415c" stroke-width="3"/>${[0,1,2].map(r=>[0,1].map(c=>`<rect x="${40+c*80}" y="${60+r*55}" width="40" height="34" fill="#bfe0f5" stroke="#33415c" stroke-width="2"/>`).join("")).join("")}<rect x="85" y="210" width="30" height="40" fill="#7a4b2a"/><rect x="170" y="150" width="110" height="80" rx="6" fill="#fff" stroke="#33415c" stroke-width="3"/><rect x="250" y="170" width="40" height="60" rx="4" fill="#5aa0d8" stroke="#33415c" stroke-width="3"/><circle cx="200" cy="236" r="14" fill="#33415c"/><circle cx="265" cy="236" r="14" fill="#33415c"/><rect y="250" width="300" height="50" fill="#c6cfdc"/>${kid(140,170,"#7c5cc4","#e0b43a",.62)}<rect x="160" y="210" width="16" height="44" rx="7" fill="#1d2433"/>`,"#eef4fb"),
 pic(`<rect x="0" y="0" width="300" height="300" fill="#e9eef5"/><rect x="30" y="60" width="80" height="170" fill="#7a4b2a" stroke="#33415c" stroke-width="3"/><circle cx="96" cy="150" r="5" fill="#ffd34d"/><rect x="190" y="60" width="80" height="170" fill="#7a4b2a" stroke="#33415c" stroke-width="3"/><circle cx="204" cy="150" r="5" fill="#ffd34d"/><rect y="230" width="300" height="70" fill="#c6cfdc"/>${kid(150,150,"#2a7d9c","#3b2a1e",.75)}${kid(232,160,"#7c5cc4","#e0b43a",.62)}<path d="M206 108q-10-30 26-30q30 0 24 22q-4 16-30 12z" fill="#fff" stroke="#33415c" stroke-width="2"/><text x="232" y="104" font-size="16" fill="#7d8aa5" text-anchor="middle">hej…</text>`),
 pic(`<rect width="300" height="300" rx="18" fill="#1f2b4d"/><circle cx="240" cy="60" r="26" fill="#fff6c9"/>${[[40,40],[110,70],[180,30],[60,110]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="2.5" fill="#fff"/>`).join("")}<rect x="0" y="200" width="300" height="100" fill="#4a5578"/><path d="M0 200h300" stroke="#c6cfdc" stroke-width="6"/>${[0,1,2,3,4,5,6,7,8,9].map(i=>`<path d="M${15+i*30} 200v40" stroke="#c6cfdc" stroke-width="4"/>`).join("")}${kid(110,120,"#7c5cc4","#e0b43a",.75)}<path d="M126 150l40-30" stroke="#8d6440" stroke-width="6" stroke-linecap="round"/><path d="M118 132l50 40" stroke="#ffd34d" stroke-width="2"/><text x="190" y="120" font-size="26" fill="#ffd34d">♪</text><text x="220" y="150" font-size="22" fill="#ffd34d">♫</text>`,"#1f2b4d"),
 pic(`<rect x="40" y="170" width="220" height="60" rx="16" fill="#e98a5a"/><rect x="30" y="150" width="30" height="80" rx="12" fill="#d47447"/><rect x="240" y="150" width="30" height="80" rx="12" fill="#d47447"/>${kid(110,120,"#2a7d9c","#3b2a1e",.8)}${kid(190,120,"#d35f8d","#7a3b1e",.8)}<text x="150" y="70" font-size="36" text-anchor="middle">💭</text>`,"#fdf0e6"),
 pic(`<rect width="300" height="300" rx="18" fill="#e9eef5"/>${[0,1,2,3,4,5].map(i=>`<rect x="${i*50}" y="${80+i*36}" width="${300-i*50}" height="36" fill="${i%2?"#c6cfdc":"#d5dde8"}" stroke="#9aa8c4"/>`).join("")}<g transform="translate(200 170)"><ellipse cx="0" cy="0" rx="26" ry="14" fill="#8a8f99"/><circle cx="-24" cy="-10" r="12" fill="#8a8f99"/><path d="M-32 -18l4-10 4 8M-20 -20l4-8 2 8" fill="#8a8f99"/><path d="M24 -2q20-10 18-26" stroke="#8a8f99" stroke-width="6" fill="none" stroke-linecap="round"/><path d="M-50 -8h-24M-50 4h-30" stroke="#33415c" stroke-width="3" stroke-linecap="round"/></g>${kid(40,17,"#7c5cc4","#e0b43a",.55)}`),
 pic(`<rect y="200" width="300" height="100" fill="#9fcf8f"/><rect x="120" y="150" width="160" height="60" rx="18" fill="#d63b2f"/><rect x="150" y="120" width="100" height="40" rx="12" fill="#e65a4c"/><circle cx="160" cy="215" r="18" fill="#33415c"/><circle cx="250" cy="215" r="18" fill="#33415c"/><circle cx="205" cy="222" r="8" fill="#8a8f99"/><circle cx="200" cy="224" r="2" fill="#ffd34d"/><circle cx="210" cy="224" r="2" fill="#ffd34d"/>${kid(60,160,"#2a7d9c","#3b2a1e",.6)}<text x="210" y="105" font-size="18" fill="#33415c" text-anchor="middle">mjau</text>`,"#e7f6ec"),
 pic(`<rect y="220" width="300" height="80" fill="#9fcf8f"/>${kid(70,130,"#2a7d9c","#3b2a1e",.75)}${kid(150,140,"#7c5cc4","#e0b43a",.7)}${kid(230,130,"#d35f8d","#7a3b1e",.75)}<g transform="translate(150 196)"><ellipse cx="0" cy="0" rx="18" ry="11" fill="#8a8f99"/><circle cx="-14" cy="-10" r="9" fill="#8a8f99"/></g><path d="M150 62c-14-22-46-8-24 16l24 20 24-20c22-24-10-38-24-16z" fill="#d35f8d"/>`,"#fff8e7")];
const U10={id:"sv7j",year:7,ord:10,title:t3("Den nya grannen","The new neighbour","الجارة الجديدة"),storyTitle:"Den nya grannen",
 icon:`<svg viewBox="0 0 320 180"><rect width="320" height="180" fill="#eef4fb"/><rect x="40" y="20" width="130" height="160" fill="#e9b98f" stroke="#33415c" stroke-width="3"/>${[0,1].map(r=>[0,1].map(c=>`<rect x="${58+c*62}" y="${38+r*50}" width="34" height="30" fill="#bfe0f5" stroke="#33415c" stroke-width="2"/>`).join("")).join("")}<rect x="92" y="140" width="26" height="40" fill="#7a4b2a"/><rect x="190" y="90" width="100" height="70" rx="6" fill="#fff" stroke="#33415c" stroke-width="3"/><circle cx="215" cy="164" r="12" fill="#33415c"/><circle cx="270" cy="164" r="12" fill="#33415c"/><text x="240" y="70" font-family="Caveat,cursive" font-weight="700" font-size="34" fill="#1f4fb0" text-anchor="middle">hej…</text></svg>`,
 pic:pic(""),words:["granne","blyg","viska","rusa","smyga","ensam","nyfiken","lita"],terms:["svsynonym","svnyans"],
 story:[
  {text:["En lördag morgon stod en flyttbil utanför Amirs hus. Två män bar in soffor och lådor i lägenheten bredvid. Amir stod i fönstret och tittade. Han var nyfiken: vem skulle bo där?", "Bakom bilen stod en tjej i hans ålder med en fiollåda i handen. Hon tittade ner i marken hela tiden. ”Vi har fått en ny granne”, sa mamma. ”Gå ut och säg hej!”"],
   pic:PJ[0],
   say:t3("En ny berättelse. Vem tror du att den nya grannen är?","A new story. Who do you think the new neighbour is?","قصة جديدة. من تظن أن الجار الجديد؟")},
  {text:["Amir gick ut i trapphuset. ”Hej, jag heter Amir. Jag bor där”, sa han och pekade på sin dörr.", "Tjejen blev röd i ansiktet. ”Mira”, viskade hon, så tyst att han nästan inte hörde. Sedan gick hon snabbt in och stängde dörren. ”Hon är nog bara blyg”, sa mamma senare. ”Kommer du ihåg hur nervös du var första dagen i skolan?”"],
   pic:PJ[1],
   say:t3("Mira viskar. Hon säger inte bara, hon viskar. Vad visar det om henne?","Mira whispers. She doesn't just say it, she whispers. What does that show about her?","ميرا تهمس. هي لا تقول فقط، بل تهمس. ماذا يُظهر ذلك عنها؟")},
  {text:["Under veckan såg Amir henne nästan aldrig. Men varje kväll hördes fiolmusik genom väggen. Den var vacker men lite sorgsen.", "En kväll satt Mira ensam på balkongen och spelade. Amir smög ut på sin egen balkong för att inte störa henne. Han lyssnade tills det blev mörkt."],
   pic:PJ[2],
   say:t3("Amir smög ut. Varför går han inte bara ut, tror du?","Amir sneaked out. Why doesn't he just walk out, do you think?","تسلّل أمير إلى الخارج. لماذا لم يخرج بشكل عادي في رأيك؟")},
  {text:["På söndagen kom Sara över. Amir berättade om den nya grannen. ”Hon verkar så ensam”, sa han. ”Men hon säger nästan ingenting.”", "”Det betyder väl inte att hon inte vill ha kompisar”, sa Sara. ”Det är svårt att vara ny. Du vet ju.” Amir märkte att hon hade rätt."],
   pic:PJ[3],
   say:t3("Vad menar Sara med ”Du vet ju”? Tänk på första berättelsen om Amir.","What does Sara mean by ”Du vet ju”? Think of the first story about Amir.","ماذا تقصد سارة بقولها «Du vet ju»؟ فكّر في القصة الأولى عن أمير.")},
  {text:["Plötsligt hördes ett skrik från trappan. ”Sesam! Kom tillbaka!” Det var Miras röst, men nu var den inte tyst alls.", "Amir och Sara rusade ut. Dörren till Miras lägenhet stod öppen, och en liten grå katt sprang nerför trappan. ”Han har aldrig varit ute förut”, ropade Mira. ”Han kan gå vilse!”"],
   pic:PJ[4],
   say:t3("Nu skriker och ropar Mira. Varför är rösten inte tyst längre?","Now Mira screams and shouts. Why isn't her voice quiet any more?","الآن تصرخ ميرا وتنادي. لماذا لم يعد صوتها منخفضًا؟")},
  {text:["De letade överallt: i källaren, bakom cyklarna och under buskarna på gården. Till slut hörde Sara ett svagt jamande under en bil.", "”Vi måste vara försiktiga, annars springer han igen”, viskade Amir. De smög närmare. Mira lade sig på marken och pratade lugnt med katten. Långsamt kom han fram, och hon kunde lyfta upp honom."],
   pic:PJ[5],
   say:t3("Barnen rusar inte nu, de smyger. Varför?","The children don't rush now, they sneak. Why?","الأطفال لا يندفعون الآن، بل يتسلّلون. لماذا؟")},
  {text:["Mira var så lättad att hon började skratta. ”Tack”, sa hon. ”Jag känner ingen här. Jag trodde inte att någon skulle hjälpa mig.”", "”Du kan lita på oss”, sa Sara. Det visade sig att Mira skulle börja i 7B efter sommaren. ”Då blir vi klasskamrater”, sa Amir. ”Och du måste spela fiol för oss någon gång.” Mira log. Den här gången tittade hon inte ner i marken."],
   pic:PJ[6],
   say:t3("”Den här gången tittade hon inte ner i marken.” Vad betyder det om hur Mira känner sig nu?","”This time she didn't look down at the ground.” What does that tell you about how Mira feels now?","«هذه المرة لم تنظر إلى الأرض». ماذا يعني ذلك عن شعور ميرا الآن؟")}],
 wordsSay:t3("Nya ord! Flera av dem handlar om hur man säger något eller hur man rör sig. Tryck på dem.","New words! Several of them are about how you say something or how you move. Tap them.","كلمات جديدة! بعضها عن طريقة الكلام أو طريقة الحركة. اضغط عليها."),
 grammar:[
  {draw:()=>{const X=[120,260,400,540,680],W5=[["viska",30,"b"],["mumla",34,"b"],["säga",40,"k"],["ropa",46,"o"],["skrika",54,"r"]];
    return[A.wipe(),A.tx(L(t3("Att säga: tyst eller högt?","Saying: quiet or loud?","الكلام: بصوت منخفض أم عالٍ؟")),400,64,38,"b"),A.arrow(70,300,740,300,"k"),qt(L(t3("tyst","quiet","منخفض")),90,340,26,"b"),qt(L(t3("högt","loud","عالٍ")),720,340,26,"r"),
     ...W5.flatMap(([w,s,c],i)=>[A.tx(w,X[i],250-i*14,s,c),A.p(R.line(X[i],290,X[i],310,.2),c,4)]),A.tx("”Mira”, viskade hon.",400,430,36,"b")]},
   say:t3("Viska, säga, ropa och skrika betyder alla att man säger något. Men nyanserna är olika: viska är tyst, skrika är mycket högt.","Viska, säga, ropa and skrika all mean saying something. But the nuance differs: viska is quiet, skrika is very loud.","viska وsäga وropa وskrika كلها تعني أن تقول شيئًا، لكن الفرق الدقيق مختلف: viska بصوت منخفض، وskrika بصوت عالٍ جدًا.")},
  {draw:()=>{const X=[120,260,400,540,680],W5=[["smyga",36,"g"],["promenera",30,"g"],["gå",42,"k"],["springa",36,"o"],["rusa",52,"r"]];
    return[A.wipe(),A.tx(L(t3("Att röra sig: långsamt eller fort?","Moving: slow or fast?","الحركة: ببطء أم بسرعة؟")),400,64,38,"b"),A.arrow(70,300,740,300,"k"),qt(L(t3("långsamt","slow","ببطء")),100,340,26,"g"),qt(L(t3("fort","fast","بسرعة")),720,340,26,"r"),
     ...W5.flatMap(([w,s,c],i)=>[A.tx(w,X[i],250-i*14,s,c),A.p(R.line(X[i],290,X[i],310,.2),c,4)]),A.tx("Amir smög ut.",230,430,36,"g"),A.tx("De rusade ut.",580,430,36,"r")]},
   say:t3("Smyga är att gå tyst och försiktigt. Rusa är att springa mycket fort. Amir smög ut för att inte störa. Sara och Amir rusade ut när Mira skrek.","Smyga is walking quietly and carefully. Rusa is running very fast. Amir sneaked out so as not to disturb. Sara and Amir rushed out when Mira screamed.","smyga تعني المشي بهدوء وحذر، وrusa تعني الجري بسرعة كبيرة. تسلّل أمير حتى لا يزعجها، واندفع أمير وسارة عندما صرخت ميرا.")},
  {draw:()=>[A.wipe(),...boxes([["Amir","b"],["smög","g","tyst, försiktigt"],["ut",null]],140,46),...boxes([["Amir","b"],["rusade","r","snabbt, plötsligt"],["ut",null]],290,46),
    A.tx("kika  ·  titta  ·  stirra",400,430,40,"o"),qt(L(t3("snabbt  →  länge","quick  →  long","سريعًا  ←  طويلًا")),400,474,26,"o")],
   say:t3("Samma mening, men ett annat verb ger en helt annan bild. Välj ordet som visar exakt vad som händer. Kika är att titta snabbt, stirra är att titta länge.","The same sentence, but another verb gives a completely different picture. Choose the word that shows exactly what happens. Kika is a quick look, stirra is a long stare.","الجملة نفسها، لكن فعلًا آخر يعطي صورة مختلفة تمامًا. اختر الكلمة التي تُظهر بالضبط ما يحدث. kika نظرة سريعة، وstirra تحديق طويل.")}],
 read:[
  {q:"Vad såg Amir utanför huset på lördagen?",o:["En flyttbil","En polisbil","En brandbil"],why:"Del 1: en flyttbil utanför Amirs hus."},
  {q:"Vad hade Mira i handen när hon kom?",o:["En fiollåda","En katt","En fotboll"],why:"Del 1: en fiollåda i handen."},
  {q:"Varför viskade Mira sitt namn, tror du?",o:["Hon var blyg och osäker.","Hon hade ont i halsen.","Hon ville inte att mamma skulle höra."],why:"Del 2: Hon blev röd och tittade ner. Hon var blyg."},
  {q:"Varför smög Amir ut på balkongen?",o:["Han ville inte störa Mira.","Han skulle gömma sig för mamma.","Han var rädd för mörkret."],why:"Del 3: för att inte störa henne."},
  {q:"Vad menar Sara med ”Du vet ju”?",o:["Amir har själv varit ny och vet hur det känns.","Amir känner Mira sedan förut.","Amir har spelat fiol."],why:"Amir var själv ny i klassen och nervös första dagen."},
  {q:"Vem var Sesam?",o:["Miras katt","Miras bror","Amirs hund"],why:"Del 5: en liten grå katt sprang nerför trappan."},
  {q:"Var hittade de katten?",o:["Under en bil","I källaren","Bakom cyklarna"],why:"Del 6: ett svagt jamande under en bil."},
  {q:"Varför var Mira så lättad?",o:["Katten var hittad.","Skolan var slut.","Amir spelade fiol."],why:"Del 7: hon kunde lyfta upp katten."},
  {q:"Hur vet vi att Mira känner sig tryggare i slutet?",o:["Hon log och tittade inte ner i marken.","Hon sprang in och stängde dörren.","Hon viskade sitt namn."],why:"Del 7: Den här gången tittade hon inte ner i marken."}],
 gram(lv,write){const [frame,right,w1,w2,inf,mean]=pick(NU);
  const sol=svLines(frame.replace("____",right),410,32,"g",40);
  if(write||lv===2)return{kind:"text",ans:[right],show:right,q:[A.wipe(),A.tx(L(t3("Skriv verbet som passar, i preteritum","Write the verb that fits, in the past tense","اكتب الفعل المناسب بصيغة الماضي")),400,64,30,"b"),...svLines(frame,170,36),A.tx(`(${mean})`,400,320,30,"o")],
   sol,hint:{say:t3("Verbet är "+inf+". Skriv det i preteritum.","The verb is "+inf+". Write it in the past tense.","الفعل هو "+inf+". اكتبه بصيغة الماضي."),draw:[]}};
  if(lv===0){const others=shuffle(NU.filter(r=>r[4]!==inf)).map(r=>r[4]).filter((x,i,a)=>a.indexOf(x)===i).slice(0,2),opts=shuffle([inf,...others]);
   return{kind:"choice",opts,ans:opts.indexOf(inf),show:inf,q:[A.wipe(),A.tx(L(t3("Vilket verb betyder:","Which verb means:","أي فعل يعني:")),400,90,34,"b"),...svLines(`”${mean}”`,200,40,"o",32)],
    sol:[A.tx(`${inf} = ${mean}`,400,420,30,"g")],hint:{say:t3("Tänk: hur tyst, hur högt eller hur fort?","Think: how quiet, how loud or how fast?","فكّر: بأي هدوء، بأي صوت، أو بأي سرعة؟"),draw:[]}}}
  const opts=shuffle([right,w1,w2]);
  return{kind:"choice",opts,ans:opts.indexOf(right),show:right,q:[A.wipe(),A.tx(L(t3("Vilket verb passar bäst?","Which verb fits best?","أي فعل هو الأنسب؟")),400,70,34,"b"),...svLines(frame,200,38)],
   sol,hint:{say:t3("Verben betyder nästan samma sak. Läs resten av meningen: vilken nyans passar?","The verbs mean almost the same. Read the rest of the sentence: which nuance fits?","الأفعال متقاربة في المعنى. اقرأ بقية الجملة: أي فرق دقيق هو المناسب؟"),draw:[]}}},
 help:[{say:t3("Viska är tyst, skrika är högt. Smyga är tyst och försiktigt, rusa är mycket fort.","Viska is quiet, skrika is loud. Smyga is quiet and careful, rusa is very fast.","viska بصوت منخفض، وskrika بصوت عالٍ. smyga بهدوء وحذر، وrusa بسرعة كبيرة."),draw:()=>[A.tx("viska → säga → skrika",400,180,44,"b"),A.tx("smyga → gå → rusa",400,300,44,"r")]}]};
LESSONS.push(svUnit(U10));
}
