/* core words used across many lessons (other terms-*.js files add each year's words) */
{const B="(?<![a-zåäö])",E="(?![a-zåäö])";
TERM("tiondel",{sv:"tiondel / tiondelar",m:new RegExp(B+"tiondel(ar|en|arna)?"+E,"i"),d:t3("Första siffran efter decimaltecknet. 1 tiondel = 0,1","The first digit after the decimal point. 1 tenth = 0.1","أول رقم بعد الفاصلة العشرية. عُشر واحد = 0,1"),ex:"0,3 = 3 tiondelar",tr:{en:"tenths",ar:"أعشار"}});
TERM("hundradel",{sv:"hundradel / hundradelar",m:new RegExp(B+"hundradel(ar|en|arna)?"+E,"i"),d:t3("Andra siffran efter decimaltecknet. 1 hundradel = 0,01","The second digit after the decimal point. 1 hundredth = 0.01","الرقم الثاني بعد الفاصلة. جزء من مئة = 0,01"),ex:"0,07 = 7 hundradelar",tr:{en:"hundredths",ar:"أجزاء من مئة"}});
TERM("avrunda",{sv:"avrunda",m:new RegExp(B+"avrunda(r|t|s|ning|ningen)?"+E,"i"),d:t3("Byta ut ett tal mot ett enklare tal som ligger nära.","Swap a number for a simpler number close to it.","استبدال عدد بعدد أبسط قريب منه."),ex:"3,87 ≈ 3,9",tr:{en:"round",ar:"قرّب"}});
TERM("decimal",{sv:"decimal",m:new RegExp(B+"decimal(er|en|erna|tal|tecken|tecknet)?"+E,"i"),d:t3("En siffra efter decimaltecknet (kommat).","A digit after the decimal point (comma).","رقم بعد الفاصلة العشرية."),ex:"4,25 har två decimaler",tr:{en:"decimal",ar:"منزلة عشرية"}});
TERM("heltal",{sv:"heltal",m:new RegExp(B+"heltal(et|en)?"+E,"i"),d:t3("Ett tal utan decimaler, t.ex. −2, 0, 7.","A number without decimals, e.g. −2, 0, 7.","عدد بلا كسور، مثل ‎−2 و 0 و 7."),ex:"7,6 ≈ 8 (närmaste heltal)",tr:{en:"whole number / integer",ar:"عدد صحيح"}});
TERM("tiotal",{sv:"tiotal",m:new RegExp(B+"tiotal(et|en)?"+E,"i"),d:t3("Tior. Avrunda till tiotal = till 10, 20, 30 …","Tens. Round to tens = to 10, 20, 30 …","العشرات. التقريب لأقرب عشرة: 10، 20، 30 …"),ex:"47 ≈ 50",tr:{en:"tens",ar:"عشرات"}});
TERM("hundratal",{sv:"hundratal",m:new RegExp(B+"hundratal(et|en)?"+E,"i"),d:t3("Hundror. Avrunda till hundratal = till 100, 200 …","Hundreds. Round to hundreds = to 100, 200 …","المئات. التقريب لأقرب مئة: 100، 200 …"),ex:"362 ≈ 400",tr:{en:"hundreds",ar:"مئات"}});
TERM("vardesiffra",{sv:"värdesiffra",m:new RegExp(B+"värdesiffr(a|or|an|orna)"+E,"i"),d:t3("Siffrorna som räknas från första siffran som inte är 0.","The digits that count, from the first digit that isn't 0.","الأرقام المهمة، تبدأ من أول رقم ليس صفرًا."),ex:"0,0461 ≈ 0,046 (2 värdesiffror)",tr:{en:"significant figure",ar:"رقم معنوي"}});
TERM("overslag",{sv:"överslag",m:new RegExp(B+"överslag(et|sräkning)?"+E,"i"),d:t3("En snabb ungefärlig uträkning med avrundade tal.","A quick rough calculation with rounded numbers.","حساب تقريبي سريع بأعداد مقرّبة."),ex:"48 · 21 ≈ 50 · 20 = 1000",tr:{en:"estimate",ar:"تقدير"}});
TERM("ungefar",{sv:"ungefär (≈)",m:new RegExp(B+"ungefär"+E,"i"),d:t3("Nästan, inte exakt. Tecknet ≈ betyder ungefär lika med.","Almost, not exact. The sign ≈ means approximately equal.","تقريبًا، ليس بالضبط. الرمز ≈ يعني يساوي تقريبًا."),ex:"9,8 ≈ 10",tr:{en:"about",ar:"تقريبًا"}});
}
WORDS.round7=["avrunda","tiondel","hundradel","decimal","heltal","tiotal","vardesiffra","overslag"];
