// generated by tools/fix-imports.mjs
export declare const SVH: any;
export declare const SVU: any;
export declare const svMount: any;
export declare const svWire: any;
export declare const svMark: any;
export declare const svPage: any;
export declare const svWordsPage: any;
export declare const svUnit: any;
export declare const svQ: any;
export declare const svLines: any;
export declare const svGen: any;
export declare const SVK: any;
