import {A,L,LESSONS,R,pick,qt,shuffle,t3} from "../legacy/core.js";
import {SVH,svLines,svUnit} from "./sv-0engine.js";
/* Svenska årskurs 7, units 11–12: Talangshowen (pronomen) and Sista dagen (prepositioner för plats och tid, a diary looking back on the year). */
{const {rx,boxes,pic,kid,W,sent,cap}=SVH;

/* ---------------- unit 11: Talangshowen (pronomen: jag/mig/min, han/honom/hans, sin eller hans) ---------------- */
W("scen",{sv:"scen (en)",m:rx("scen(en|er|erna)?"),d:t3("Platsen där man uppträder, ofta lite högre än publiken.","The place where you perform, often a bit higher than the audience.","المكان الذي يُقدَّم فيه العرض، وغالبًا يكون أعلى قليلًا من الجمهور."),ex:"De gick ut på scenen.",tr:{en:"stage",ar:"خشبة المسرح"},syn:["estrad"],wrong:["kök","korridor"],gap:["Sara och Amir gick ut på","scenen","och ljuset var starkt."],gapForm:"scenen",form:"en scen – scener"});
W("publik",{sv:"publik (en)",m:rx("publik(en|er)?"),d:t3("Människorna som tittar och lyssnar på en show eller en match.","The people who watch and listen to a show or a match.","الناس الذين يشاهدون ويستمعون إلى عرض أو مباراة."),ex:"Publiken började jubla.",tr:{en:"audience",ar:"الجمهور"},syn:["åskådare"],wrong:["artister","lärare"],gap:["Sara tittade ut över","publiken","och glömde texten."],gapForm:"publiken",form:"en publik – publiker"});
W("repetera",{sv:"repetera",m:rx("repetera(r|de|t)?"),d:t3("Öva på något många gånger, till exempel inför en show.","Practise something many times, for example before a show.","أن تتمرّن على شيء مرات كثيرة، مثلًا قبل عرض."),ex:"Vi repeterade varje dag efter skolan.",tr:{en:"rehearse",ar:"يتمرّن (بروفة)"},syn:["öva","träna"],wrong:["glömma","sova"],gap:["De","repeterade","varje dag i musiksalen."],gapForm:"repeterade",form:"repetera – repeterade – har repeterat"});
W("rampfeber",{sv:"rampfeber (en)",m:rx("rampfeber(n)?"),d:t3("Nervositet innan man ska uppträda inför andra.","Nervousness before you perform in front of others.","التوتّر قبل أن تقدّم عرضًا أمام الآخرين."),ex:"Amir hade rampfeber kvällen före showen.",tr:{en:"stage fright",ar:"رهبة المسرح"},syn:["nervositet"],opp:["lugn"],wrong:["glädje","hunger"],gap:["Han kunde inte äta. Det kallas","rampfeber","."],gapForm:"rampfeber",form:"rampfeber – rampfebern"});
W("sjalvfortroende",{sv:"självförtroende (ett)",m:rx("självförtroende(t)?"),d:t3("Att tro på sig själv och på det man kan.","Believing in yourself and in what you can do.","أن تؤمن بنفسك وبما تستطيع فعله."),ex:"Efter showen hade Amir bättre självförtroende.",tr:{en:"self-confidence",ar:"الثقة بالنفس"},syn:["tro på sig själv"],opp:["osäkerhet"],wrong:["trötthet","ilska"],gap:["Efter showen hade han fått ett nytt","självförtroende","."],gapForm:"självförtroende",form:"ett självförtroende"});
W("uppträda",{sv:"uppträda",m:rx("uppträd(a|er|de|t)"),d:t3("Visa upp något inför publik, till exempel sjunga, dansa eller spela.","Show something in front of an audience, for example sing, dance or play.","أن تقدّم شيئًا أمام جمهور، مثل الغناء أو الرقص أو العزف."),ex:"Alla i 7B får uppträda.",tr:{en:"perform",ar:"يقدّم عرضًا"},syn:["framträda"],wrong:["gömma sig","vila"],gap:["Alla i klassen får","uppträda","på talangshowen."],gapForm:"uppträda",form:"uppträda – uppträdde – har uppträtt"});
W("imponera",{sv:"imponera (på)",m:rx("imponera(r|de|t|d|nde)?"),d:t3("Få någon att tycka att man är mycket bra.","Make someone think you are very good.","أن تجعل شخصًا يرى أنك رائع جدًا."),ex:"Ni imponerade på hela aulan.",tr:{en:"impress",ar:"يُبهِر"},syn:["göra intryck på"],wrong:["skrämma","glömma"],gap:["Lena sa: ”Ni","imponerade","på hela aulan.”"],gapForm:"imponerade",form:"imponera – imponerade – har imponerat"});
W("glomma",{sv:"glömma bort",m:rx("glöm(ma|mer|de|t)( bort)?"),d:t3("Inte komma ihåg något längre.","Not remember something any more.","ألّا تتذكّر شيئًا بعد الآن."),ex:"Sara glömde bort texten.",tr:{en:"forget",ar:"ينسى"},syn:["inte komma ihåg"],opp:["komma ihåg"],wrong:["sjunga","hitta"],gap:["Mitt i låten","glömde","Sara bort texten."],gapForm:"glömde",form:"glömma – glömde – har glömt"});
W("svpronomen",{sv:"pronomen",m:rx("pronomen(et)?"),d:t3("Ett litet ord som står i stället för ett namn eller en sak.","A small word that stands in for a name or a thing.","كلمة صغيرة تحلّ محلّ اسم أو شيء."),ex:"Sara → hon, Amir → han",tr:{en:"pronoun",ar:"ضمير"}});
W("svobjektsform",{sv:"objektsform",m:rx("objektsform(en)?"),d:t3("Pronomenets form när någon gör något mot det: mig, honom, henne, oss, dem.","The pronoun's form when something is done to it: mig, honom, henne, oss, dem.","صيغة الضمير عندما يقع عليه الفعل: mig وhonom وhenne وoss وdem."),ex:"Sara peppade honom.",tr:{en:"object form",ar:"ضمير المفعول به"}});
W("svpossessiv",{sv:"possessivt pronomen",m:rx("possessiv(a|t)?( pronomen)?"),d:t3("Ett pronomen som visar vems något är: min, hans, hennes, sin.","A pronoun that shows whose something is: min, hans, hennes, sin.","ضمير يبيّن لمن الشيء: min وhans وhennes وsin."),ex:"Amir höll sin gitarr.",tr:{en:"possessive pronoun",ar:"ضمير الملكية"}});
const PRT=[["jag","mig","min"],["du","dig","din"],["han","honom","hans"],["hon","henne","hennes"],["vi","oss","vår"],["ni","er","er"],["de","dem","deras"]];
/* [sentence, right, wrong, wrong, cue for writing, kind] kind: s subject form, o object form, p possessive, r sin/sitt/sina */
const PRQ=[["Sara frågade Amir, men först ville ____ inte.","han","honom","hans","Amir","s"],
 ["Amir hade rampfeber, så Sara peppade ____.","honom","han","hans","Amir","o"],
 ["Sara glömde texten, men Amir hjälpte ____.","henne","hon","hennes","Sara","o"],
 ["Lena sa: ”Ni imponerade verkligen på ____!”","mig","jag","min","jag","o"],
 ["”Vi har repeterat i tre veckor. ____ kan den här låten.”","Vi","Oss","Vår","vi","s"],
 ["Publiken applåderade, och Sara log mot ____.","dem","de","deras","publiken","o"],
 ["Ljuset var starkt, och ____ såg nästan ingenting.","de","dem","deras","Sara och Amir","s"],
 ["”Kan du hjälpa ____?” viskade Sara bakom scenen.","mig","jag","min","Sara själv","o"],
 ["Amir höll ____ gitarr hårt.","sin","hans","honom","Amirs egen","r"],
 ["Mamma filmade med ____ mobil.","sin","hennes","henne","mammas egen","r"],
 ["Amir ringde till ____ kusin efter showen.","sin","hans","honom","Amirs egen","r"],
 ["Föräldrarna filmade med ____ mobiler.","sina","deras","dem","föräldrarnas egna","r"],
 ["Amir lutade sig mot Sara och ____ mikrofon.","hennes","sin","henne","Saras","p"],
 ["Sara sjöng, och ____ röst var klar.","hennes","sin","henne","Saras","p"],
 ["Amir tittade på Sara. ____ ögon var stora.","Hennes","Sin","Henne","Saras","p"],
 ["Lena tackade eleverna för ____ hjälp.","deras","sin","dem","elevernas","p"],
 ["Sara lånade Amirs gitarr. Hon höll ____ gitarr försiktigt.","hans","sin","honom","Amirs","p"]];
const KG=`<g transform="rotate(-28)"><rect x="-4" y="-92" width="8" height="70" rx="2" fill="#5a3418"/><ellipse cx="0" cy="-16" rx="17" ry="16" fill="#c47a3a"/><ellipse cx="0" cy="12" rx="24" ry="22" fill="#c47a3a"/><circle cx="0" cy="-4" r="6" fill="#5a3418"/></g>`;
const guitar=(x,y,s=1)=>`<g transform="translate(${x} ${y}) scale(${s})">${KG}</g>`;
const mic=(x,y)=>`<rect x="${x-2}" y="${y}" width="4" height="90" fill="#33415c"/><rect x="${x-8}" y="${y-18}" width="16" height="22" rx="8" fill="#1d2433"/><rect x="${x-20}" y="${y+88}" width="40" height="6" rx="3" fill="#33415c"/>`;
const curtains=`<path d="M0 0 H70 Q50 150 70 300 H0Z" fill="#b8323f"/><path d="M300 0 H230 Q250 150 230 300 H300Z" fill="#b8323f"/><rect width="300" height="20" fill="#8e2230"/>`;
const PK=[pic(`<rect x="30" y="26" width="240" height="112" rx="6" fill="#2f4a3a"/><text x="150" y="76" font-family="Caveat,cursive" font-weight="700" font-size="38" fill="#fff" text-anchor="middle">TALANGSHOW!</text><text x="150" y="118" font-size="26" text-anchor="middle">🎤 🎸 💃</text>${kid(64,170,"#8a5cc2","#c98a3a",.9)}${kid(170,196,"#2a7d9c","#3b2a1e",.72)}${kid(240,196,"#d35f8d","#7a3b1e",.72)}`,"#fdf3e3"),
 pic(`<rect y="220" width="300" height="80" fill="#d9b98c"/><rect x="200" y="60" width="80" height="70" rx="4" fill="#fff" stroke="#33415c" stroke-width="3"/><path d="M212 80h56M212 96h56M212 112h40" stroke="#9aa8c4" stroke-width="3"/>${kid(95,120,"#2a7d9c","#3b2a1e",.9)}${guitar(105,205,.9)}${kid(205,150,"#d35f8d","#7a3b1e",.8)}<text x="40" y="70" font-size="30" fill="#2257c9">♪</text><text x="150" y="60" font-size="34" fill="#e07b00">♫</text>`,"#e8f3ea"),
 pic(`<rect x="170" y="30" width="100" height="90" rx="4" fill="#26345a" stroke="#fff" stroke-width="4"/><circle cx="240" cy="62" r="16" fill="#f7e7a1"/><circle cx="246" cy="56" r="14" fill="#26345a"/><text x="196" y="100" font-size="14" fill="#fff">✦</text><rect x="20" y="210" width="140" height="40" rx="8" fill="#6c7fb8"/><rect x="20" y="196" width="40" height="20" rx="6" fill="#fff"/>${kid(110,110,"#2a7d9c","#3b2a1e",.85)}${guitar(118,190,.8)}${kid(220,150,"#3f9e7a","#2b1d14",.95)}`,"#3a4670"),
 pic(`${curtains}<rect x="70" y="20" width="160" height="280" fill="#2b2b3a"/>${kid(120,130,"#2a7d9c","#3b2a1e",.85)}${guitar(128,210,.8)}${kid(190,130,"#d35f8d","#7a3b1e",.85)}<text x="214" y="118" font-size="22">💦</text>`,"#1d2433"),
 pic(`${curtains}<path d="M150 20 L60 270 H240Z" fill="#fff6c4" opacity=".75"/><rect y="262" width="300" height="38" fill="#7a4b2a"/>${kid(110,140,"#2a7d9c","#3b2a1e",.8)}${guitar(118,215,.75)}${kid(190,140,"#d35f8d","#7a3b1e",.8)}${mic(165,168)}<text x="196" y="112" font-size="26">❓</text>`,"#2b2b3a"),
 pic(`<rect y="0" width="300" height="130" fill="#7a4b2a"/>${kid(110,36,"#2a7d9c","#3b2a1e",.68)}${kid(190,36,"#d35f8d","#7a3b1e",.68)}${[0,1,2,3,4,5,6].map(i=>`<circle cx="${25+i*42}" cy="200" r="18" fill="${["#f1c7a3","#c98e63","#f1c7a3","#8d5a3b","#f1c7a3","#c98e63","#f1c7a3"][i]}"/><rect x="${9+i*42}" y="216" width="32" height="50" rx="12" fill="${["#5aa0d8","#e98a5a","#7cc08a","#8a5cc2","#e0b43a","#5aa0d8","#d35f8d"][i]}"/><path d="M${12+i*42} 214 l-10 -34 M${38+i*42} 214 l10 -34" stroke="#f1c7a3" stroke-width="7" stroke-linecap="round"/>`).join("")}${[0,1,2,3,4,5].map(i=>`<circle cx="${46+i*42}" cy="262" r="17" fill="${["#3b2a1e","#7a3b1e","#c98a3a","#3b2a1e","#2b1d14","#7a3b1e"][i]}"/>`).join("")}<text x="150" y="160" font-size="28" text-anchor="middle">👏 ❤️ 👏</text>`,"#fdf3e3"),
 pic(`<rect width="300" height="300" fill="#f6c28b"/><circle cx="150" cy="190" r="60" fill="#f39a4a"/><rect y="200" width="300" height="100" fill="#8aa86b"/><path d="M110 300 L140 200 H160 L190 300Z" fill="#d9c7a4"/>${kid(110,150,"#2a7d9c","#3b2a1e",.75)}${guitar(80,232,.65)}${kid(190,150,"#d35f8d","#7a3b1e",.75)}<text x="150" y="70" font-size="34" text-anchor="middle">⭐</text>`,"#f6c28b")];
const U11={id:"sv7k",year:7,ord:11,title:t3("Talangshowen","The talent show","عرض المواهب"),storyTitle:"Talangshowen",
 icon:`<svg viewBox="0 0 320 180"><rect width="320" height="180" fill="#2b2b3a"/><path d="M0 0 H70 Q52 90 70 180 H0Z" fill="#b8323f"/><path d="M320 0 H250 Q268 90 250 180 H320Z" fill="#b8323f"/><path d="M160 0 L90 170 H230Z" fill="#fff6c4" opacity=".7"/><rect y="160" width="320" height="20" fill="#7a4b2a"/><rect x="158" y="80" width="4" height="80" fill="#33415c"/><rect x="152" y="64" width="16" height="22" rx="8" fill="#1d2433"/><text x="110" y="60" font-size="30" fill="#e0b43a">♪</text><text x="200" y="50" font-size="30" fill="#e0b43a">♫</text></svg>`,
 pic:pic(""),words:["scen","publik","repetera","rampfeber","sjalvfortroende","uppträda","imponera","glomma"],terms:["svpronomen","svobjektsform","svpossessiv"],
 story:[
  {text:["En måndag i maj skrev Lena på tavlan: TALANGSHOW OM TRE VECKOR! ”Alla i 7B får uppträda om de vill”, sa hon.","Sara vände sig mot Amir. ”Vi gör en låt tillsammans! Jag sjunger, och du spelar gitarr.” Amir skakade på huvudet. ”Ingen har hört mig spela förut.”"],
   pic:PK[0],
   say:t3("En ny berättelse! Vad tror du att Amir och Sara ska göra på talangshowen?","A new story! What do you think Amir and Sara will do at the talent show?","قصة جديدة! ماذا تظن أن أمير وسارة سيفعلان في عرض المواهب؟")},
  {text:["Men Sara gav sig inte. Hon visste att han spelade varje kväll i sitt rum, för hans mamma hade berättat det. Till slut sa han ja.","Sedan repeterade de varje dag efter skolan i musiksalen. Sara skrev texten och Amir hittade ackorden. En dag lät tränaren dem till och med gå tidigare från fotbollsträningen."],
   pic:PK[1],
   say:t3("Att repetera betyder att öva många gånger. Vem skriver texten och vem hittar ackorden?","'Repetera' means to practise many times. Who writes the words and who finds the chords?","«repetera» تعني أن تتمرّن مرات كثيرة. من يكتب كلمات الأغنية ومن يجد الأكوردات؟")},
  {text:["Kvällen före showen var Amir nervös. Han kunde inte äta, och han spelade låten om och om igen. ”Det kallas rampfeber”, sa mamma och log. ”Alla som ska uppträda känner så.”","”Men tänk om jag spelar fel?” frågade han. ”Då spelar du bara vidare”, sa hon. ”Publiken märker nästan aldrig små fel.”"],
   pic:PK[2],
   say:t3("Rampfeber är nervositet före en show. Vad är mammas råd?","Stage fright is nervousness before a show. What is Mum's advice?","رهبة المسرح هي التوتّر قبل العرض. ما نصيحة الأم؟")},
  {text:["På fredagen var aulan full av klasskamrater och föräldrar. Bakom scenen höll Amir sin gitarr hårt.","Då märkte han att Sara var blek. Hon som aldrig var rädd på planen darrade. ”Jag klarar inte det här”, viskade hon. Amir peppade henne som tränaren brukade göra: ”Vi har repeterat i tre veckor. Vi klarar det.”"],
   pic:PK[3],
   say:t3("Nu är det Sara som är rädd. Varför är det överraskande?","Now it is Sara who is scared. Why is that surprising?","الآن سارة هي الخائفة. لماذا هذا مفاجئ؟")},
  {text:["Lena sa deras namn i mikrofonen, och de gick ut på scenen. Ljuset var starkt och varmt. Amir började spela, och Sara sjöng den första versen med klar röst.","Men i andra versen hände det. Sara tittade ut över publiken och glömde bort texten. Det blev helt tyst i aulan. Hon vände sig mot Amir med stora ögon."],
   pic:PK[4],
   say:t3("Läs långsamt. Vad händer i andra versen?","Read slowly. What happens in the second verse?","اقرأ ببطء. ماذا يحدث في المقطع الثاني؟")},
  {text:["Amir slutade inte spela. Han lutade sig mot hennes mikrofon och sjöng nästa rad själv. Sara log, hittade orden igen och sjöng resten av låten med honom.","När det sista ackordet tonade ut började publiken jubla. Några ställde sig upp och applåderade. Amirs mamma filmade med sin mobil och torkade sina ögon."],
   pic:PK[5],
   say:t3("Lägg märke till orden hennes, honom och sin. De är pronomen.","Notice the words hennes, honom and sin. They are pronouns.","لاحظ الكلمات hennes وhonom وsin. إنها ضمائر.")},
  {text:["Efteråt kom Lena fram till dem. ”Ni imponerade på hela aulan”, sa hon. ”Och det bästa var hur ni hjälpte varandra.”","På vägen hem var Amir lättad och lite utmattad, men han hade fått ett nytt självförtroende. ”Nästa år kanske jag sjunger också”, sa han. Sara skrattade. ”Då ska jag påminna dig om det.”"],
   pic:PK[6],
   say:t3("Hur har Amir förändrats sedan början av berättelsen?","How has Amir changed since the start of the story?","كيف تغيّر أمير منذ بداية القصة؟")}],
 wordsSay:t3("Här är de nya orden. Tryck på dem! Orden nervös, peppa och jubla känner du redan igen.","Here are the new words. Tap them! You already know nervös, peppa and jubla.","هذه هي الكلمات الجديدة. اضغط عليها! أنت تعرف مسبقًا nervös وpeppa وjubla."),
 grammar:[
  {draw:()=>{const X=[200,420,630],C=["b","o","g"];return[A.wipe(),A.tx(L(t3("Pronomen","Pronouns","الضمائر")),400,48,38,"b"),
    ...[L(t3("gör något","does something","يفعل")),L(t3("får något gjort mot sig","has something done to it","يقع عليه الفعل")),L(t3("vems?","whose?","لمن؟"))].map((s,i)=>qt(s,X[i],100,22,C[i])),
    ...PRT.flatMap((r,j)=>r.map((s,i)=>A.tx(s,X[i],150+j*49,34,C[i]))),A.hl(90,236,640,52)]},
   say:t3("Pronomen står i stället för namn. Han gör något, honom får något gjort mot sig, och hans visar vems något är.","Pronouns stand in for names. Han does something, honom has something done to him, and hans shows whose something is.","الضمائر تحلّ محلّ الأسماء. han هو من يفعل، وhonom من يقع عليه الفعل، وhans يبيّن لمن الشيء.")},
  {draw:()=>[A.wipe(),...boxes([["Sara","b","subjekt"],["peppade",null],["Amir","o","objekt"]],150,52),A.arrow(224,228,214,318,"b"),A.arrow(576,228,564,318,"o"),
    ...boxes([["Hon","b",""],["peppade",null],["honom","o","inte: han"]],390,52)],
   say:t3("Sara peppade Amir blir: Hon peppade honom. Den som gör något heter hon. Den som får peppen heter honom, inte han.","'Sara peppade Amir' becomes: Hon peppade honom. The one doing it is hon. The one being cheered on is honom, not han.","«Sara peppade Amir» تصبح: Hon peppade honom. من يقوم بالفعل هو hon، ومن يقع عليه الفعل هو honom وليس han.")},
  {draw:()=>[A.wipe(),A.tx(L(t3("sin eller hans?","sin or hans?","sin أم hans؟")),400,50,36,"b"),
    A.tx("Amir",190,160,44,"b"),A.tx("höll",320,160,44),A.tx("sin",430,160,44,"g"),A.tx("gitarr.",570,160,44),A.arrow(430,180,200,182,"g",-45),qt(L(t3("hans egen","his own","غيتاره هو")),430,248,24,"g"),
    A.tx("Sara",190,330,44,"r"),A.tx("höll",320,330,44),A.tx("hans",440,330,44,"o"),A.tx("gitarr.",580,330,44),qt(L(t3("= Amirs gitarr","= Amir's guitar","= غيتار أمير")),440,380,24,"o"),
    A.tx(L(t3("sin pekar tillbaka på subjektet","sin points back to the subject","sin تعود إلى الفاعل")),400,450,30,"k"),A.hl(150,420,500,46)],
   say:t3("Amir höll sin gitarr: gitarren är hans egen, för sin pekar tillbaka på subjektet. Sara höll hans gitarr: hon höll Amirs gitarr. På engelska säger man his i båda meningarna, men svenskan har två ord.","Amir höll sin gitarr: the guitar is his own, because sin points back to the subject. Sara höll hans gitarr: she held Amir's guitar. English says 'his' in both, but Swedish has two words.","Amir höll sin gitarr: الغيتار له هو، لأن sin تعود إلى الفاعل. Sara höll hans gitarr: أمسكت غيتار أمير. بالعربية نقول «غيتاره» في الحالتين، أما السويدية فتفرّق بين sin وhans.")}],
 read:[
  {q:"Vad skrev Lena på tavlan?",o:["Att det skulle bli en talangshow.", "Att det skulle bli prov på fredag.", "Att fotbollsträningen var inställd."],why:"Del 1: TALANGSHOW OM TRE VECKOR!"},
  {q:"Varför ville Amir inte vara med först?",o:["Ingen hade hört honom spela förut.", "Han kunde inte spela gitarr.", "Han skulle resa bort."],why:"Del 1: ”Ingen har hört mig spela förut.”"},
  {q:"Hur visste Sara att Amir spelade gitarr?",o:["Hans mamma hade berättat det.", "Hon hade sett honom på en scen.", "Lena hade sagt det."],why:"Del 2: hans mamma hade berättat det."},
  {q:"Vad ska man göra om man spelar fel, enligt mamma?",o:["Spela vidare.", "Börja om från början.", "Gå av scenen."],why:"Del 3: ”Då spelar du bara vidare.”"},
  {q:"Varför blev Amir förvånad bakom scenen?",o:["Sara, som brukar vara modig, var rädd.", "Gitarren var trasig.", "Aulan var tom."],why:"Del 4: Hon som aldrig var rädd på planen darrade."},
  {q:"Vad hände i andra versen?",o:["Sara glömde bort texten.", "Amir tappade gitarren.", "Ljuset slocknade."],why:"Del 5: Sara glömde bort texten."},
  {q:"Hur räddade Amir låten?",o:["Han sjöng nästa rad själv.", "Han slutade spela.", "Han bad publiken sjunga."],why:"Del 6: Han sjöng nästa rad själv."},
  {q:"Varför torkade Amirs mamma sina ögon?",o:["Hon var rörd och stolt.", "Hon hade fått sand i ögat.", "Hon var arg på Amir."],why:"Man kan gråta av glädje när någon man älskar lyckas."},
  {q:"Vad menar Sara med ”Då ska jag påminna dig om det”?",o:["Hon vill att Amir gör det han nu säger.", "Hon tror att Amir glömmer allt.", "Hon vill inte sjunga mer."],why:"Amir säger att han kanske sjunger nästa år. Sara tänker se till att han gör det."}],
 gram(lv,write){const pool=lv===0?PRQ.filter(x=>x[5]==="s"||x[5]==="o"):PRQ,[f,right,w1,w2,cue,kind]=pick(pool),done=f.replace("____",right);
  const why={s:t3("Den här personen gör något: subjektsform (jag, han, hon, vi, de).","This person does something: subject form (jag, han, hon, vi, de).","هذا الشخص يقوم بالفعل: ضمير الفاعل (jag وhan وhon وvi وde)."),
   o:t3("Något görs mot den här personen: objektsform (mig, honom, henne, oss, dem).","Something is done to this person: object form (mig, honom, henne, oss, dem).","يقع الفعل على هذا الشخص: ضمير المفعول به (mig وhonom وhenne وoss وdem)."),
   r:t3("Det tillhör subjektet i samma mening: sin, sitt eller sina.","It belongs to the subject of the same sentence: sin, sitt or sina.","الشيء ملك لفاعل الجملة نفسها: sin أو sitt أو sina."),
   p:t3("Det tillhör någon annan än subjektet: hans, hennes eller deras.","It belongs to someone other than the subject: hans, hennes or deras.","الشيء ملك لشخص غير الفاعل: hans أو hennes أو deras.")}[kind];
  const head=[A.wipe(),A.tx(L(t3("Vilket pronomen passar?","Which pronoun fits?","أي ضمير يناسب؟")),400,70,34,"b"),...svLines(f,190,38)];
  if(write||lv===2)return{kind:"text",ans:[right],show:right,q:[...head,A.tx(`(${cue})`,400,330,34,"o")],sol:svLines(done,410,34,"g"),hint:{say:why,draw:[]}};
  const opts=shuffle([right,w1,w2]);
  return{kind:"choice",opts,ans:opts.indexOf(right),show:right,q:head,sol:svLines(done,400,34,"g"),hint:{say:why,draw:[]}}},
 help:[{say:t3("Gör något: han, hon. Något görs mot: honom, henne. Vems: hans, hennes. Subjektets egen: sin.","Does something: han, hon. Something done to: honom, henne. Whose: hans, hennes. The subject's own: sin.","يفعل: han وhon. يقع عليه الفعل: honom وhenne. لمن: hans وhennes. ملك الفاعل نفسه: sin."),
   draw:()=>[A.tx("han · hon",400,140,44,"b"),A.tx("honom · henne",400,230,44,"o"),A.tx("hans · hennes",400,320,44,"g"),A.tx("sin · sitt · sina",400,410,44,"g")]}]};
LESSONS.push(svUnit(U11));

/* ---------------- unit 12: Sista dagen (prepositioner: plats och tid) ---------------- */
W("minne",{sv:"minne (ett)",m:rx("minne(t|n|na)?"),d:t3("Något som man kommer ihåg från förr.","Something you remember from before.","شيء تتذكّره من الماضي."),ex:"Det är ett av mina bästa minnen.",tr:{en:"memory",ar:"ذكرى"},syn:["hågkomst"],wrong:["dröm","plan"],gap:["Det är ett av mina bästa","minnen","från hela året."],gapForm:"minnen",form:"ett minne – minnen"});
W("sakna",{sv:"sakna",m:rx("sakna(r|de|t)?"),d:t3("Vara ledsen för att någon eller något inte finns hos en.","Feel sad because someone or something is not with you.","أن تحزن لأن شخصًا أو شيئًا ليس معك."),ex:"Jag kommer att sakna er.",tr:{en:"miss",ar:"يشتاق إلى"},syn:["längta efter"],wrong:["glömma","hata"],gap:["”Jag kommer att","sakna","er”, sa Noor."],gapForm:"sakna",form:"sakna – saknade – har saknat"});
W("termin",{sv:"termin (en)",m:rx("termin(en|er|erna)?"),d:t3("En del av skolåret: hösttermin eller vårtermin.","A part of the school year: autumn term or spring term.","جزء من السنة الدراسية: الفصل الخريفي أو الربيعي."),ex:"Det var sista dagen på terminen.",tr:{en:"term, semester",ar:"فصل دراسي"},syn:["skolhalvår"],wrong:["lektion","rast"],gap:["Vi var i klassrummet för sista gången den här","terminen","."],gapForm:"terminen",form:"en termin – terminer"});
W("betyg",{sv:"betyg (ett)",m:rx("betyg(et|en)?"),d:t3("Ett omdöme från A till F om hur mycket man kan i ett ämne.","A mark from A to F for how much you know in a subject.","تقييم من A إلى F لمدى معرفتك في مادة."),ex:"Jag fick B i svenska.",tr:{en:"grade, mark",ar:"درجة (علامة)"},syn:["omdöme"],wrong:["schema","läxa"],gap:["Lena delade ut våra","betyg","."],gapForm:"betyg",form:"ett betyg – betyg"});
W("tacksam",{sv:"tacksam",m:rx("tacksam(t|ma)?"),d:t3("Glad över något som någon har gett eller gjort för en.","Glad about something someone has given you or done for you.","سعيد بشيء أعطاك إياه أحد أو فعله من أجلك."),ex:"Jag är tacksam för mina vänner.",tr:{en:"grateful",ar:"ممتنّ"},syn:["uppskattande"],opp:["otacksam"],wrong:["arg","trött"],gap:["Nu på kvällen känner jag mig","tacksam","."],gapForm:"tacksam",form:"tacksam – tacksamt – tacksamma"});
W("framtid",{sv:"framtid (en)",m:rx("framtid(en)?"),d:t3("Tiden som kommer efter nu.","The time that comes after now.","الوقت الذي يأتي بعد الآن."),ex:"Ingen vet hur framtiden blir.",tr:{en:"future",ar:"المستقبل"},syn:["tiden som kommer"],opp:["det förflutna"],wrong:["kvällen","skolan"],gap:["Ingen vet hur","framtiden","blir."],gapForm:"framtiden",form:"en framtid – framtiden"});
W("utvecklas",{sv:"utvecklas",m:rx("utveckla(s|des|ts)"),d:t3("Bli bättre, större eller klokare med tiden.","Become better, bigger or wiser over time.","أن يصبح المرء أفضل أو أكبر أو أحكم مع الوقت."),ex:"Du har utvecklats mycket i år.",tr:{en:"develop, grow",ar:"يتطوّر"},syn:["växa","bli bättre"],opp:["stå still"],wrong:["sova","försvinna"],gap:["Mamma säger att jag har","utvecklats","mycket i år."],gapForm:"utvecklats",form:"utvecklas – utvecklades – har utvecklats"});
W("farval",{sv:"ta farväl (av)",m:rx("farväl(et)?"),d:t3("Säga hej då till någon som man inte ska träffa på länge.","Say goodbye to someone you won't see for a long time.","أن تقول وداعًا لشخص لن تراه لمدة طويلة."),ex:"Vi tog farväl av Noor.",tr:{en:"say goodbye",ar:"يودّع"},syn:["säga adjö"],opp:["hälsa välkommen"],wrong:["presentera sig","fira"],gap:["Efter lunch tog vi","farväl","av Noor."],gapForm:"farväl",form:"ta farväl – tog farväl – har tagit farväl"});
W("svpreposition",{sv:"preposition",m:rx("preposition(en|er|erna)?"),d:t3("Ett litet ord som visar var eller när: i, på, vid, till, om.","A small word that shows where or when: i, på, vid, till, om.","كلمة صغيرة تبيّن أين أو متى: i وpå وvid وtill وom."),ex:"Jag sitter vid skrivbordet.",tr:{en:"preposition",ar:"حرف جر"}});
W("svtidsuttryck",{sv:"tidsuttryck",m:rx("tidsuttryck(et|en)?"),d:t3("Ord som säger när något händer.","Words that say when something happens.","كلمات تقول متى يحدث شيء."),ex:"för ett år sedan, om åtta veckor",tr:{en:"time expression",ar:"ظرف زمان"}});
/* [sentence, right, wrong, wrong, kind p(lace)/t(ime), also accepted when written (or null: choice only)] */
const PPQ=[["Amir bodde ____ Göteborg förut.","i","på","om","p",[]],
 ["Hela skolan samlades ____ gården.","på","om","för","p",[]],
 ["Sedan gick vi ____ vårt klassrum.","till","vid","om","p",["in i"]],
 ["Jag sitter ____ mitt skrivbord och skriver.","vid","om","för","p",null],
 ["Mamma står ____ fönstret och tittar ut.","vid","om","för","p",["i"]],
 ["Gitarren ligger ____ sängen.","på","om","till","p",null],
 ["Sara bor ____ samma gata som Amir.","på","i","till","p",[]],
 ["På måndag åker vi ____ Göteborg.","till","vid","på","p",[]],
 ["Noor flyttar ____ Malmö i juli.","till","vid","om","p",[]],
 ["Skolan började ____ augusti.","i","på","om","t",[]],
 ["____ morgonen sjöng vi en sommarsång.","På","Om","Till","t",["under"]],
 ["____ ett år sedan var svenska mitt sämsta ämne.","För","Om","Vid","t",[]],
 ["Åttan börjar ____ åtta veckor.","om","för","vid","t",[]],
 ["Noor flyttar till Malmö ____ juli.","i","på","vid","t",[]],
 ["Vi ska hälsa på henne ____ sommarlovet.","under","vid","för","t",["på","i"]],
 ["Talangshowen var ____ fredagen.","på","i","om","t",[]],
 ["Jag har spelat gitarr ____ tre år.","i","för","till","t",[]],
 ["Det var sista dagen ____ sjuan.","i","vid","om","t",[]]];
const desk=`<rect x="26" y="210" width="188" height="56" fill="#a7774a"/><rect x="20" y="200" width="200" height="14" rx="4" fill="#b98757"/><rect x="34" y="214" width="10" height="80" fill="#8d6440"/><rect x="196" y="214" width="10" height="80" fill="#8d6440"/>`;
const PL=[pic(`<rect x="160" y="30" width="120" height="110" rx="4" fill="#3a4c88" stroke="#fff" stroke-width="5"/><path d="M220 30v110M160 85h120" stroke="#fff" stroke-width="4"/><text x="186" y="66" font-size="16" fill="#fff">✦</text><text x="246" y="120" font-size="12" fill="#fff">✦</text>${kid(90,125,"#2a7d9c","#3b2a1e",.85)}${desk}<rect x="110" y="180" width="70" height="22" rx="3" fill="#fff" stroke="#33415c" stroke-width="2"/><path d="M145 180v22" stroke="#33415c" stroke-width="2"/><path d="M200 150 l-20 30 h40Z" fill="#e0b43a"/><rect x="198" y="178" width="4" height="22" fill="#33415c"/>`,"#fdf3e3"),
 pic(`<rect y="210" width="300" height="90" fill="#9fcf8f"/><rect x="40" y="40" width="6" height="190" fill="#c6cfdc"/><rect x="46" y="44" width="64" height="40" fill="#2f6fbf"/><rect x="46" y="58" width="64" height="12" fill="#f2c83a"/><rect x="66" y="44" width="12" height="40" fill="#f2c83a"/>${kid(150,140,"#2a7d9c","#3b2a1e",.8)}<rect x="190" y="110" width="80" height="100" rx="4" fill="#fff" stroke="#33415c" stroke-width="3"/><text x="230" y="140" font-size="16" text-anchor="middle" fill="#33415c">Betyg</text><text x="208" y="172" font-size="22" fill="#1e9e5a">A</text><text x="238" y="200" font-size="22" fill="#2257c9">B</text>`,"#e7f3fb"),
 pic(`<ellipse cx="150" cy="120" rx="130" ry="95" fill="#fff" stroke="#c6cfdc" stroke-width="4"/><circle cx="70" cy="240" r="14" fill="#fff" stroke="#c6cfdc" stroke-width="4"/><circle cx="50" cy="272" r="8" fill="#fff" stroke="#c6cfdc" stroke-width="3"/><rect x="60" y="80" width="180" height="90" rx="5" fill="#f6d8a8"/><rect x="60" y="70" width="180" height="14" fill="#c0573e"/><rect x="138" y="128" width="24" height="42" fill="#7a4b2a"/>${[0,1,2,3].map(i=>`<rect x="${76+i*42}" y="96" width="22" height="22" fill="#bfe0f5"/>`).join("")}<text x="150" y="60" font-family="Caveat,cursive" font-weight="700" font-size="28" fill="#1f4fb0" text-anchor="middle">augusti</text>`,"#eef4fb"),
 pic(`<rect x="20" y="30" width="125" height="120" rx="8" fill="#2b2b3a"/><path d="M82 30 L40 150 H124Z" fill="#fff6c4" opacity=".7"/>${guitar(84,128,.7)}<rect x="155" y="30" width="125" height="120" rx="8" fill="#cfe3ee"/><rect x="155" y="110" width="125" height="40" fill="#5fae5a"/><circle cx="218" cy="110" r="14" fill="#fff" stroke="#1d2433" stroke-width="3"/>${[0,1,2,3].map(i=>`<path d="M${170+i*28} 44l-5 12" stroke="#4d7fe0" stroke-width="3" stroke-linecap="round"/>`).join("")}<rect x="60" y="170" width="180" height="110" rx="8" fill="#fff" stroke="#33415c" stroke-width="3"/><text x="150" y="245" font-size="40" text-anchor="middle">📱</text><text x="200" y="215" font-size="22">▶</text>`,"#fdf3e3"),
 pic(`<rect y="220" width="300" height="80" fill="#9fcf8f"/>${kid(90,120,"#2a7d9c","#3b2a1e",.8)}${kid(160,120,"#e0b43a","#2b1d14",.8)}${kid(230,120,"#d35f8d","#7a3b1e",.8)}${[0,1,2].map(i=>`<circle cx="${148+i*12}" cy="${150-i%2*10}" r="9" fill="${["#e98a5a","#f2c83a","#d35f8d"][i]}"/>`).join("")}<path d="M150 160 l10 30 l10 -30" stroke="#3f9e5a" stroke-width="4" fill="none"/><rect x="40" y="36" width="220" height="50" rx="8" fill="#fff" stroke="#33415c" stroke-width="3"/><text x="150" y="70" font-family="Caveat,cursive" font-weight="700" font-size="30" fill="#d63b2f" text-anchor="middle">Lycka till, Noor!</text>`,"#e7f3fb"),
 pic(`<path d="M150 250 C40 170 60 70 150 110 C240 70 260 170 150 250Z" fill="#f4a6b8"/>${kid(110,120,"#2a7d9c","#3b2a1e",.7)}${kid(190,120,"#d35f8d","#7a3b1e",.7)}<text x="150" y="60" font-family="Caveat,cursive" font-weight="700" font-size="36" fill="#d63b2f" text-anchor="middle">Tack!</text>`,"#fdf3e3"),
 pic(`<circle cx="240" cy="60" r="32" fill="#f7c948"/>${[0,1,2,3,4,5,6,7].map(i=>{const a=i*Math.PI/4;return`<path d="M${240+42*Math.cos(a)} ${60+42*Math.sin(a)} L${240+54*Math.cos(a)} ${60+54*Math.sin(a)}" stroke="#f7c948" stroke-width="5" stroke-linecap="round"/>`}).join("")}<rect y="190" width="300" height="110" fill="#7cc08a"/><path d="M120 300 L145 190 H160 L190 300Z" fill="#d9c7a4"/>${kid(80,140,"#2a7d9c","#3b2a1e",.75)}${kid(220,140,"#d35f8d","#7a3b1e",.75)}<circle cx="150" cy="260" r="14" fill="#fff" stroke="#1d2433" stroke-width="3"/><text x="22" y="56" font-family="Caveat,cursive" font-weight="700" font-size="32" fill="#1f4fb0">Sommarlov!</text>`,"#cfeaf7")];
const U12={id:"sv7l",year:7,ord:12,title:t3("Sista dagen","The last day","اليوم الأخير"),storyTitle:"Amirs dagbok",
 icon:`<svg viewBox="0 0 320 180"><rect width="320" height="180" fill="#cfeaf7"/><circle cx="270" cy="40" r="24" fill="#f7c948"/><rect y="130" width="320" height="50" fill="#7cc08a"/><rect x="70" y="36" width="150" height="110" rx="6" fill="#2a7d9c"/><rect x="82" y="44" width="134" height="96" rx="4" fill="#fff"/><path d="M96 70h104M96 90h104M96 110h80" stroke="#9aa8c4" stroke-width="3"/><text x="149" y="62" font-family="Caveat,cursive" font-weight="700" font-size="20" fill="#1f4fb0" text-anchor="middle">Kära dagbok</text></svg>`,
 pic:pic(""),words:["minne","sakna","termin","betyg","tacksam","framtid","utvecklas","farval"],terms:["svpreposition","svtidsuttryck"],
 story:[
  {text:["Kära dagbok! Fredag den 13 juni, klockan tio på kvällen. Jag sitter vid mitt skrivbord i mitt rum. I dag var sista dagen i sjuan.","Jag vill skriva ner allt innan jag glömmer bort det. Mamma säger att ett år går fort, men att minnen stannar länge."],
   pic:PL[0],
   say:t3("Det här är en dagbok. Amir skriver om sin sista dag i sjuan. Var sitter han?","This is a diary. Amir writes about his last day in year 7. Where is he sitting?","هذه صفحة من يوميات. يكتب أمير عن يومه الأخير في الصف السابع. أين يجلس؟")},
  {text:["På morgonen samlades hela skolan på gården. Vi sjöng en sommarsång, och rektorn höll ett kort tal. Sedan gick vi till vårt klassrum för sista gången den här terminen.","Lena delade ut våra betyg. Jag var lite nervös, men jag fick A i matte och B i svenska! För ett år sedan var svenska mitt sämsta ämne."],
   pic:PL[1],
   say:t3("Betyg går från A till F. Vad fick Amir i svenska?","Grades go from A to F. What did Amir get in Swedish?","الدرجات من A إلى F. ماذا نال أمير في اللغة السويدية؟")},
  {text:["Efteråt satt jag länge och tänkte på min första dag i augusti. Jag stod utanför skolan och kände ingen. Jag hittade inte ens rätt sal i korridoren.","Sedan pekade en tjej på den tomma stolen bredvid sig. Det var Sara. Det är fortfarande ett av mina bästa minnen från hela året."],
   pic:PL[2],
   say:t3("Ett minne är något man kommer ihåg. Känner du igen det här från den första berättelsen?","A memory is something you remember. Do you recognise this from the first story?","الذكرى شيء تتذكّره. هل تعرف هذا من القصة الأولى؟")},
  {text:["Efter det kom matchen i regnet och finalen, som ingen av oss kommer att glömma. Och i maj stod jag på scenen med min gitarr, framför en publik på över hundra personer.","Mamma har sett filmen minst tjugo gånger. Hon säger att jag har utvecklats mycket i år. Jag tror att hon har rätt. Jag vågar mer nu."],
   pic:PL[3],
   say:t3("Amir tänker tillbaka på året. Vilka händelser minns han?","Amir looks back on the year. Which events does he remember?","يستعيد أمير أحداث السنة. ما الأحداث التي يتذكّرها؟")},
  {text:["Efter lunch tog vi farväl av Noor i vår klass. Hon ska flytta till Malmö med sin familj i juli. Vi gav henne blommor och ett kort som alla hade skrivit på.","”Jag kommer att sakna er”, sa Noor. Sara grät, och jag fick en klump i halsen. Vi lovade att hälsa på henne under sommarlovet."],
   pic:PL[4],
   say:t3("Att ta farväl är att säga hej då för länge. Vem tar klassen farväl av?","'Ta farväl' means saying goodbye for a long time. Who does the class say goodbye to?","«ta farväl» تعني أن تودّع شخصًا لمدة طويلة. مَن يودّع الصف؟")},
  {text:["Nu på kvällen känner jag mig tacksam. Tacksam för Sara och mina andra klasskamrater, och för tränaren som alltid peppade oss. Tacksam för Lena, som aldrig gav upp om någon.","Och tacksam för mamma, som sa att alla var nya någon gång. Hon hade rätt. I augusti var jag ny. Nu är jag en av 7B."],
   pic:PL[5],
   say:t3("Amir skriver tacksam fyra gånger. Varför tror du att han upprepar ordet?","Amir writes 'tacksam' four times. Why do you think he repeats the word?","يكتب أمير كلمة «tacksam» أربع مرات. لماذا تظن أنه يكرّرها؟")},
  {text:["Hur blir framtiden? Jag vet inte. Om åtta veckor börjar åttan, och på måndag åker vi till Göteborg och hälsar på mina kusiner.","Men en sak vet jag: i sommar ska jag spela fotboll med Sara nästan varje dag, och jag ska fortsätta med gitarren. Hej då sjuan, hej sommarlov! /Amir"],
   pic:PL[6],
   say:t3("Lägg märke till om och för … sedan. Det ena handlar om framtiden, det andra om det som har hänt.","Notice om and för … sedan. One is about the future, the other about what has happened.","لاحظ om وför … sedan. الأولى عن المستقبل، والثانية عمّا حدث في الماضي.")}],
 wordsSay:t3("Här är årets sista nya ord. Tryck på dem! I dagboken kommer många ord från hela året tillbaka.","Here are the year's last new words. Tap them! Many words from the whole year come back in the diary.","هذه آخر الكلمات الجديدة لهذه السنة. اضغط عليها! في اليوميات تعود كلمات كثيرة من السنة كلها."),
 grammar:[
  {draw:()=>{const X=[130,320,500,670];return[A.wipe(),A.tx(L(t3("Var? Prepositioner för plats","Where? Prepositions of place","أين؟ حروف جر للمكان")),400,50,34,"b"),
    A.p(R.rect(X[0]-55,150,110,100,.6),"k",3.5),A.tx("●",X[0],215,40,"r"),
    A.p(R.line(X[1]-60,240,X[1]+60,240,.4),"k",4),A.tx("●",X[1],228,40,"r"),
    A.p(R.rect(X[2]-50,150,60,100,.6),"k",3.5),A.tx("●",X[2]+40,215,40,"r"),
    A.arrow(X[3]-70,210,X[3]+20,210,"r"),A.p(R.rect(X[3]+28,170,44,80,.6),"k",3.5),
    ...[["i","i mitt rum"],["på","på gården"],["vid","vid skrivbordet"],["till","till klassrummet"]].flatMap(([p,ex],i)=>[A.tx(p,X[i],310,46,["b","o","g","r"][i]),qt(ex,X[i],352,22,["b","o","g","r"][i])]),
    A.tx("Jag sitter vid mitt skrivbord i mitt rum.",400,450,32,"k")]},
   say:t3("Prepositioner visar var något är. I: inne i något. På: ovanpå något eller på en öppen plats. Vid: bredvid. Till: dit man är på väg.","Prepositions show where something is. I: inside something. På: on top of something, or at an open place. Vid: beside. Till: where you are going.","حروف الجر تبيّن مكان الشيء. i: داخل الشيء. på: فوقه أو في مكان مفتوح. vid: بجانبه. till: إلى حيث تذهب.")},
  {draw:()=>{const y=230;return[A.wipe(),A.tx(L(t3("När? Före och efter nu","When? Before and after now","متى؟ قبل الآن وبعده")),400,50,34,"b"),A.arrow(50,y,760,y,"k"),
    ...[[150,"för ett år sedan",L(t3("förr","a year ago","قبل سنة")),"o"],[400,"i dag",L(t3("nu","now","الآن")),"b"],[650,"om åtta veckor",L(t3("senare","in eight weeks","بعد ثمانية أسابيع")),"g"]].flatMap(([x,s,t,c])=>[A.p(R.line(x,y-14,x,y+14,.2),c,5),A.tx(s,x,y-40,36,c),qt(t,x,y+48,26,c)]),
    A.tx("✗ i åtta veckor",230,400,36,"r"),A.tx("✓ om åtta veckor",570,400,36,"g"),A.hl(440,370,260,46),
    qt(L(t3("i åtta veckor = hela tiden, åtta veckor långt","i åtta veckor = for eight weeks","i åtta veckor = لمدة ثمانية أسابيع")),400,460,26,"k")]},
   say:t3("För ett år sedan betyder förr. Om åtta veckor betyder i framtiden. Säg inte i åtta veckor när du menar sedan, för i åtta veckor betyder hela tiden under åtta veckor.","För ett år sedan means a year ago. Om åtta veckor means in eight weeks. Don't say 'i åtta veckor' for 'in eight weeks': it means 'for eight weeks'.","för ett år sedan تعني «قبل سنة». om åtta veckor تعني «بعد ثمانية أسابيع». لا تقل i åtta veckor وأنت تقصد «بعد»، فهي تعني «لمدة ثمانية أسابيع».")},
  {draw:()=>[A.wipe(),A.tx(L(t3("Tidsuttryck","Time expressions","ظروف الزمان")),400,50,34,"b"),
    ...[["i","i augusti · i sommar · i dag","b"],["på","på morgonen · på fredag","o"],["om","om åtta veckor","g"],["under","under sommarlovet","r"],["för … sedan","för ett år sedan","k"]].flatMap(([p,ex,c],j)=>[A.tx(p,170,125+j*76,38,c),A.tx(ex,500,125+j*76,32,c)])],
   say:t3("Månader och årstider tar i: i augusti, i sommar. Dagar och delar av dagen tar på: på fredag, på morgonen. En tid framåt tar om, och en hel period tar under.","Months and seasons take i: i augusti, i sommar. Days and parts of the day take på: på fredag, på morgonen. A time ahead takes om, and a whole period takes under.","الأشهر والفصول تأخذ i: i augusti وi sommar. الأيام وأجزاء اليوم تأخذ på: på fredag وpå morgonen. الوقت القادم يأخذ om، والفترة الكاملة تأخذ under.")}],
 read:[
  {q:"Vad för slags text är det här?",o:["En dagbok", "En nyhetsartikel", "En instruktion"],why:"Den börjar med ”Kära dagbok!”."},
  {q:"Var sitter Amir när han skriver?",o:["Vid skrivbordet i sitt rum", "På skolgården", "I klassrummet"],why:"Del 1: Jag sitter vid mitt skrivbord i mitt rum."},
  {q:"Vilket betyg fick Amir i svenska?",o:["B", "A", "C"],why:"Del 2: B i svenska."},
  {q:"Vad var svenska för Amir för ett år sedan?",o:["Hans sämsta ämne", "Hans bästa ämne", "Ett ämne han inte hade"],why:"Del 2: svenska var mitt sämsta ämne."},
  {q:"Vilket minne är ett av Amirs bästa?",o:["När Sara pekade på stolen bredvid sig", "När han fick sina betyg", "När han åkte till Göteborg"],why:"Del 3: Det var Sara. Det är ett av mina bästa minnen."},
  {q:"Varför tog klassen farväl av Noor?",o:["Hon ska flytta till Malmö.", "Hon ska byta klass.", "Hon ska resa till Göteborg."],why:"Del 5: Hon ska flytta till Malmö."},
  {q:"Varför fick Amir en klump i halsen?",o:["Han blev ledsen när Noor skulle flytta.", "Han hade ätit för fort.", "Han var förkyld."],why:"En klump i halsen får man när man nästan börjar gråta."},
  {q:"Vad menar Amir med ”I augusti var jag ny. Nu är jag en av 7B”?",o:["Han känner att han hör till klassen nu.", "Han har bytt till en annan klass.", "Han är äldst i klassen."],why:"Han var ny och ensam i augusti. Nu känner han sig hemma i klassen."},
  {q:"När börjar åttan?",o:["Om åtta veckor", "För åtta veckor sedan", "På måndag"],why:"Del 7: Om åtta veckor börjar åttan."}],
 gram(lv,write){const wr=write||lv===2,pool=PPQ.filter(x=>(lv===0?x[4]==="p":true)&&(!wr||x[5])),[f,right,w1,w2,kind,alt]=pick(pool),done=f.replace("____",right);
  const why=kind==="p"?t3("Det handlar om plats. Inne i: i. Ovanpå eller på en plats: på. Bredvid: vid. Dit man ska: till.","It is about place. Inside: i. On top of, or at a place: på. Beside: vid. Where you are going: till.","الأمر عن المكان. داخل: i. فوق أو في مكان: på. بجانب: vid. إلى حيث تذهب: till.")
   :t3("Det handlar om tid. Månad: i. Dag eller del av dagen: på. Framåt: om. Bakåt: för … sedan. En hel period: under.","It is about time. Month: i. Day or part of the day: på. Ahead: om. Back: för … sedan. A whole period: under.","الأمر عن الزمن. الشهر: i. اليوم أو جزء منه: på. المستقبل: om. الماضي: för … sedan. فترة كاملة: under.");
  const head=[A.wipe(),A.tx(L(t3("Vilken preposition passar?","Which preposition fits?","أي حرف جر يناسب؟")),400,70,34,"b"),...svLines(f,190,38),A.tx(kind==="p"?L(t3("var?","where?","أين؟")):L(t3("när?","when?","متى؟")),400,330,34,kind==="p"?"o":"g")];
  if(wr)return{kind:"text",ans:[right,...alt],show:right,q:head,sol:svLines(done,410,34,"g"),hint:{say:why,draw:[]}};
  const opts=shuffle([right,w1,w2]);
  return{kind:"choice",opts,ans:opts.indexOf(right),show:right,q:head,sol:svLines(done,410,34,"g"),hint:{say:why,draw:[]}}},
 help:[{say:t3("Plats: i, på, vid, till. Tid: i augusti, på fredag, om åtta veckor, för ett år sedan.","Place: i, på, vid, till. Time: i augusti, på fredag, om åtta veckor (in eight weeks), för ett år sedan (a year ago).","المكان: i وpå وvid وtill. الزمان: i augusti وpå fredag وom åtta veckor (بعد ثمانية أسابيع) وför ett år sedan (قبل سنة)."),
   draw:()=>[A.tx("i · på · vid · till",400,170,46,"b"),A.tx("om åtta veckor →",400,280,40,"g"),A.tx("← för ett år sedan",400,370,40,"o")]}]};
LESSONS.push(svUnit(U12));
}
