import {TERM,WORDS,t3} from "../legacy/core.js";
/* words for grades 8 and 9 (the Swedish test words of each lesson) */
{const B="(?<![a-zåäö])",E="(?![a-zåäö])";
/* ---- shared instruction verbs ---- */
TERM("berakna",{sv:"beräkna",m:new RegExp(B+"beräkna(r|s|t|d)?"+E,"i"),d:t3("Räkna ut och svara med ett tal.","Work it out and answer with a number.","أوجد الناتج وأجب بعدد."),ex:"Beräkna 3 · 4 → 12",tr:{en:"calculate",ar:"احسب"}});
TERM("bestam",{sv:"bestäm",m:new RegExp(B+"bestäm(ma|mer|s|t)?"+E,"i"),d:t3("Ta reda på vilket tal eller värde som söks.","Find out which number or value is asked for.","اعرف العدد أو القيمة المطلوبة."),ex:"Bestäm x: x + 2 = 5 → 3",tr:{en:"find / determine",ar:"أوجد / حدّد"}});
TERM("forenkla",{sv:"förenkla",m:new RegExp(B+"förenkla(r|s|t|d)?"+E,"i"),d:t3("Skriv kortare och enklare, med samma värde.","Write it shorter and simpler, with the same value.","اكتبه بشكل أقصر وأبسط وبالقيمة نفسها."),ex:"a · a · a = a³",tr:{en:"simplify",ar:"بسّط"}});
/* ---- pow8 ---- */
TERM("potens",{sv:"potens",m:new RegExp(B+"potens(en|er|erna)?"+E,"i"),d:t3("Ett tal skrivet med bas och exponent, t.ex. 2⁵.","A number written with a base and an exponent, e.g. 2⁵.","عدد مكتوب بأساس وأس، مثل 2⁵."),ex:"2⁵ = 2 · 2 · 2 · 2 · 2",tr:{en:"power",ar:"قوة"}});
TERM("bas",{sv:"bas",m:new RegExp(B+"bas(en)?"+E,"i"),d:t3("I en potens: talet som multipliceras med sig självt.","In a power: the number that is multiplied by itself.","في القوة: العدد الذي يُضرب في نفسه."),ex:"2⁵: basen är 2",tr:{en:"base",ar:"الأساس"}});
TERM("exponent",{sv:"exponent",m:new RegExp(B+"exponent(en|er|erna)?"+E,"i"),d:t3("Det lilla talet uppe till höger som visar antalet faktorer.","The small raised number that shows how many factors there are.","العدد الصغير المرفوع الذي يبيّن عدد العوامل."),ex:"2⁵: exponenten är 5",tr:{en:"exponent",ar:"الأس"}});
TERM("faktor",{sv:"faktor",m:new RegExp(B+"faktor(n|er|erna)?"+E,"i"),d:t3("Ett av talen som multipliceras.","One of the numbers that are multiplied.","أحد الأعداد التي نضربها."),ex:"3 · 4: faktorerna 3 och 4",tr:{en:"factor",ar:"عامل"}});
TERM("produkt",{sv:"produkt",m:new RegExp(B+"produkt(en|er|erna)?"+E,"i"),d:t3("Svaret när man multiplicerar.","The answer when you multiply.","ناتج عملية الضرب."),ex:"produkten av 3 och 4 är 12",tr:{en:"product",ar:"حاصل الضرب"}});
/* ---- root8 ---- */
TERM("kvadrattal",{sv:"kvadrattal",m:new RegExp(B+"kvadrattal(et|en)?"+E,"i"),d:t3("Ett heltal gånger sig självt, t.ex. 49 = 7 · 7.","A whole number times itself, e.g. 49 = 7 × 7.","عدد صحيح مضروب في نفسه، مثل 49 = 7 × 7."),ex:"1, 4, 9, 16, 25 …",tr:{en:"square number",ar:"عدد مربع"}});
TERM("kvadratrot",{sv:"kvadratrot / roten ur",m:new RegExp(B+"(kvadratrot(en|ter|terna)?|roten ur)"+E,"i"),d:t3("Talet som gånger sig självt ger talet under roten.","The number that times itself gives the number under the root.","العدد الذي إذا ضُرب في نفسه أعطى العدد تحت الجذر."),ex:"√49 = 7",tr:{en:"square root",ar:"الجذر التربيعي"}});
TERM("kvadrera",{sv:"kvadrera",m:new RegExp(B+"kvadrer(a|ar|as|at|ing)"+E,"i"),d:t3("Multiplicera ett tal med sig självt.","Multiply a number by itself.","اضرب العدد في نفسه."),ex:"6² = 6 · 6 = 36",tr:{en:"square",ar:"ربّع"}});
TERM("area",{sv:"area",m:new RegExp(B+"area(n|or|orna)?"+E,"i"),d:t3("Hur stor en yta är, t.ex. i m² eller cm².","How big a surface is, e.g. in m² or cm².","حجم السطح، مثلًا بالمتر المربع أو السنتيمتر المربع."),ex:"3 m · 4 m = 12 m²",tr:{en:"area",ar:"المساحة"}});
TERM("omkrets",{sv:"omkrets",m:new RegExp(B+"omkrets(en|ar)?"+E,"i"),d:t3("Längden runt hela figuren.","The length all the way round a shape.","الطول حول الشكل كله."),ex:"kvadrat 5 m: 4 · 5 = 20 m",tr:{en:"perimeter",ar:"المحيط"}});
/* ---- sci8 ---- */
TERM("grundpotensform",{sv:"grundpotensform",m:new RegExp(B+"grundpotensform(en)?"+E,"i"),d:t3("Ett tal från 1 till under 10 gånger en tiopotens.","A number from 1 to under 10 times a power of ten.","عدد من 1 إلى أقل من 10 مضروب في قوة للعشرة."),ex:"0,00035 = 3,5 · 10⁻⁴",tr:{en:"scientific notation",ar:"الصيغة العلمية"}});
TERM("tiopotens",{sv:"tiopotens",m:new RegExp(B+"tiopotens(en|er|erna)?"+E,"i"),d:t3("En potens med basen 10.","A power with base 10.","قوة أساسها 10."),ex:"10³ = 1 000, 10⁻² = 0,01",tr:{en:"power of ten",ar:"قوة العشرة"}});
TERM("prefix",{sv:"prefix",m:new RegExp(B+"prefix(et|en|ets)?"+E,"i"),d:t3("Början på en enhet som står för en tiopotens.","The start of a unit that stands for a power of ten.","بداية الوحدة وتدل على قوة للعشرة."),ex:"milli: 1 mm = 10⁻³ m",tr:{en:"prefix",ar:"بادئة"}});
TERM("mikro",{sv:"mikro (µ)",m:new RegExp(B+"(mikro(meter|metern)?|µm)"+E,"i"),d:t3("En miljondel, alltså 10⁻⁶.","A millionth, which is 10⁻⁶.","جزء من مليون، أي 10⁻⁶."),ex:"7 µm = 7 · 10⁻⁶ m",tr:{en:"micro",ar:"ميكرو"}});
/* ---- speed8 ---- */
TERM("hastighet",{sv:"hastighet",m:new RegExp(B+"hastighet(en|er|erna)?"+E,"i"),d:t3("Hur lång sträcka man hinner på en viss tid.","How far you get in a certain time.","المسافة التي تقطعها في زمن معيّن."),ex:"150 km på 2 h: 75 km/h",tr:{en:"speed",ar:"السرعة"}});
TERM("medelhastighet",{sv:"medelhastighet",m:new RegExp(B+"medelhastighet(en)?"+E,"i"),d:t3("Hela sträckan delat med hela tiden.","The whole distance divided by the whole time.","المسافة كلها مقسومة على الزمن كله."),ex:"300 km / 4 h = 75 km/h",tr:{en:"average speed",ar:"متوسط السرعة"}});
TERM("stracka",{sv:"sträcka",m:new RegExp(B+"sträck(a|an|or|orna)"+E,"i"),d:t3("Hur långt man åker, t.ex. i km eller m.","How far you travel, e.g. in km or m.","كم تقطع من المسافة، مثلًا بالكيلومتر أو المتر."),ex:"s = v · t",tr:{en:"distance",ar:"المسافة"}});
TERM("kmh",{sv:"km/h",m:new RegExp(B+"km/h"+E,"i"),d:t3("Kilometer i timmen: hur många km man kommer på 1 h.","Kilometres per hour: how many km you get in 1 h.","كيلومتر في الساعة: كم كيلومترًا تقطع في ساعة."),ex:"80 km/h: 80 km på 1 h",tr:{en:"km/h",ar:"كيلومتر في الساعة"}});
TERM("omvandla",{sv:"omvandla",m:new RegExp(B+"omvandla(r|s|t|d)?"+E,"i"),d:t3("Byta till en annan enhet utan att ändra värdet.","Change to another unit without changing the value.","التحويل إلى وحدة أخرى دون تغيير القيمة."),ex:"2 m/s = 7,2 km/h",tr:{en:"convert",ar:"حوّل"}});
/* ---- pct8 ---- */
TERM("procent",{sv:"procent (%)",m:new RegExp(B+"procent(en|uell|uella|uellt)?"+E,"i"),d:t3("Hundradelar, där 1 % betyder 1 av 100.","Hundredths, where 1% means 1 out of 100.","أجزاء من مئة، و1% تعني 1 من 100."),ex:"25 % = 0,25",tr:{en:"percent",ar:"في المئة"}});
TERM("forandringsfaktor",{sv:"förändringsfaktor",m:new RegExp(B+"förändringsfaktor(n|er|erna)?"+E,"i"),d:t3("Talet du gångrar med när något ökar eller minskar.","The number you multiply by when something goes up or down.","العدد الذي تضرب فيه عندما يزيد شيء أو ينقص."),ex:"+15 % → · 1,15",tr:{en:"change factor",ar:"معامل التغيّر"}});
TERM("procentenhet",{sv:"procentenhet",m:new RegExp(B+"procentenhet(en|er|erna)?"+E,"i"),d:t3("Skillnaden mellan två procentsatser.","The difference between two percentages.","الفرق بين نسبتين مئويتين."),ex:"40 % → 50 %: +10 p.e.",tr:{en:"percentage point",ar:"نقطة مئوية"}});
TERM("okning",{sv:"öka / ökning",m:new RegExp(B+"(ök(at|t|ning|ningen)|höj(a|s|er|des|ts|ning))"+E,"i"),d:t3("Hur mycket större något blir: nytt minus gammalt.","How much bigger something gets: new minus old.","مقدار ما يكبر به الشيء: الجديد ناقص القديم."),ex:"200 → 250: ökning 50",tr:{en:"increase",ar:"زيادة"}});
TERM("minskning",{sv:"minska / minskning",m:new RegExp(B+"(minsk(at|t|ning|ningen)|sänk(a|s|er|tes|ts|ning))"+E,"i"),d:t3("Hur mycket mindre något blir: gammalt minus nytt.","How much smaller something gets: old minus new.","مقدار ما يصغر به الشيء: القديم ناقص الجديد."),ex:"250 → 200: minskning 50",tr:{en:"decrease",ar:"نقصان"}});
TERM("andel",{sv:"andel",m:new RegExp(B+"andel(en|ar|arna)?"+E,"i"),d:t3("Hur stor del av det hela, ofta i procent.","How big a part of the whole, often in percent.","كم يمثّل الجزء من الكل، غالبًا بالنسبة المئوية."),ex:"15 av 60 = 25 %",tr:{en:"proportion / share",ar:"نسبة"}});
/* ---- interest8 ---- */
TERM("ranta",{sv:"ränta",m:new RegExp(B+"ränt(a|an|or|orna)"+E,"i"),d:t3("Det man betalar för ett lån, eller får när man sparar.","What you pay for a loan, or get when you save.","ما تدفعه مقابل القرض، أو ما تحصل عليه عند الادخار."),ex:"3 % av 5 000 kr = 150 kr",tr:{en:"interest",ar:"فائدة"}});
TERM("rantesats",{sv:"räntesats",m:new RegExp(B+"räntesats(en|er)?"+E,"i"),d:t3("Räntan i procent per år.","The interest in percent per year.","الفائدة بالنسبة المئوية في السنة."),ex:"räntesats 3 % per år",tr:{en:"interest rate",ar:"سعر الفائدة"}});
TERM("rantaparanta",{sv:"ränta på ränta",m:new RegExp(B+"ränta på ränta"+E,"i"),d:t3("Man får ränta även på förra årens ränta.","You also get interest on earlier years' interest.","تحصل على فائدة على فوائد السنوات السابقة أيضًا."),ex:"5 000 · 1,03³ ≈ 5 464",tr:{en:"compound interest",ar:"الفائدة المركّبة"}});
TERM("lan",{sv:"lån",m:new RegExp(B+"lån(et|en|a|ar|ade)?"+E,"i"),d:t3("Pengar man lånar och betalar tillbaka, med ränta.","Money you borrow and pay back, with interest.","مال تقترضه وتردّه مع الفائدة."),ex:"lån 20 000 kr, 6 % ränta",tr:{en:"loan",ar:"قرض"}});
TERM("belopp",{sv:"belopp",m:new RegExp(B+"belopp(et|en)?"+E,"i"),d:t3("En summa pengar.","A sum of money.","مبلغ من المال."),ex:"beloppet 5 000 kr",tr:{en:"amount",ar:"المبلغ"}});
TERM("avbetalning",{sv:"avbetalning",m:new RegExp(B+"avbetalning(en|ar)?"+E,"i"),d:t3("Man betalar lite i taget, varje månad.","You pay a little at a time, every month.","تدفع جزءًا صغيرًا كل شهر."),ex:"24 · 449 kr = 10 776 kr",tr:{en:"instalments",ar:"التقسيط"}});
/* ---- paren8 ---- */
TERM("parentes",{sv:"parentes",m:new RegExp(B+"parentes(en|er|erna)?"+E,"i"),d:t3("Tecknen ( ) som gör det inuti till en enda del.","The signs ( ) that make what is inside one part.","العلامتان ( ) تجعلان ما بداخلهما جزءًا واحدًا."),ex:"3(x + 4)",tr:{en:"brackets",ar:"أقواس"}});
TERM("multin",{sv:"multiplicera in",m:new RegExp(B+"multiplicera(r)? in"+E,"i"),d:t3("Gånga talet framför parentesen med varje term inuti.","Multiply the number in front by each term inside the brackets.","اضرب العدد الذي أمام القوس في كل حدّ داخله."),ex:"3(x + 4) = 3x + 12",tr:{en:"expand",ar:"فكّ الأقواس"}});
TERM("brytut",{sv:"bryta ut",m:new RegExp(B+"bry(t|ter|ta) ut"+E,"i"),d:t3("Skriv som en faktor gånger en parentes.","Write as a factor times a bracket.","اكتب العبارة على شكل عامل × قوس."),ex:"6x + 15 = 3(2x + 5)",tr:{en:"factor out",ar:"أخرج عاملًا مشتركًا"}});
TERM("faktorisera",{sv:"faktorisera",m:new RegExp(B+"faktoriser(a|ar|as|ing|ingen)"+E,"i"),d:t3("Skriv som en produkt, alltså faktorer gånger varandra.","Write as a product: factors times each other.","اكتب على شكل حاصل ضرب عوامل."),ex:"12a + 18 = 6(2a + 3)",tr:{en:"factorise",ar:"حلّل إلى عوامل"}});
TERM("term",{sv:"term",m:new RegExp(B+"term(en|er|erna)?"+E,"i"),d:t3("En del av ett uttryck som skiljs av + eller −.","A part of an expression, separated by + or −.","جزء من العبارة يفصله + أو −."),ex:"3x + 5: termerna 3x och 5",tr:{en:"term",ar:"حدّ"}});
TERM("uttryck",{sv:"uttryck",m:new RegExp(B+"uttryck(et|en|ets)?"+E,"i"),d:t3("Tal, bokstäver och räknetecken, utan likhetstecken.","Numbers, letters and operations, with no equals sign.","أعداد وحروف وعمليات، بلا علامة يساوي."),ex:"3x + 5",tr:{en:"expression",ar:"عبارة"}});
TERM("gemfaktor",{sv:"gemensam faktor",m:new RegExp(B+"gemensam(ma)? faktor(n|er)?"+E,"i"),d:t3("En faktor som går jämnt upp i alla termer.","A factor that divides every term exactly.","عامل يقسم كل الحدود دون باقٍ."),ex:"6x och 15: 3",tr:{en:"common factor",ar:"عامل مشترك"}});
/* ---- eq8 ---- */
TERM("ekvation",{sv:"ekvation",m:new RegExp(B+"ekvation(en|er|erna)?"+E,"i"),d:t3("En likhet med ett okänt tal, t.ex. x + 3 = 7.","An equality with an unknown number, e.g. x + 3 = 7.","مساواة فيها عدد مجهول، مثل x + 3 = 7."),ex:"x + 3 = 7 ger x = 4",tr:{en:"equation",ar:"معادلة"}});
TERM("losa",{sv:"lös / lösning",m:new RegExp(B+"lös(a|er|t|ning|ningen|ningar|ningarna)?"+E,"i"),d:t3("Ta reda på vilket värde x måste ha.","Find out which value x must have.","اعرف القيمة التي يجب أن تكون لـ x."),ex:"2x = 10 → x = 5",tr:{en:"solve / solution",ar:"حلّ"}});
TERM("namnare",{sv:"nämnare",m:new RegExp(B+"nämnar(e|en|na)"+E,"i"),d:t3("Talet under bråkstrecket.","The number under the fraction line.","العدد تحت خط الكسر."),ex:"3/4: nämnaren är 4",tr:{en:"denominator",ar:"المقام"}});
TERM("mgn",{sv:"minsta gemensamma nämnare",m:new RegExp(B+"minsta gemensamma nämnar(e|en)"+E,"i"),d:t3("Minsta tal som alla nämnarna går jämnt upp i.","The smallest number all the denominators divide into.","أصغر عدد تقسمه كل المقامات دون باقٍ."),ex:"x/2 + x/3: MGN = 6",tr:{en:"lowest common denominator",ar:"المقام المشترك الأصغر"}});
TERM("stallaupp",{sv:"ställ upp en ekvation",m:new RegExp(B+"ställ(a|er)? upp"+E,"i"),d:t3("Skriv texten som en ekvation med x för det okända.","Write the text as an equation, with x for the unknown.","اكتب النص معادلةً، وx للمجهول."),ex:"3(x + 40) = 1 020",tr:{en:"set up an equation",ar:"كوّن معادلة"}});
/* ---- pyth8 ---- */
TERM("katet",{sv:"katet",m:new RegExp(B+"katet(en|er|erna|ernas)?"+E,"i"),d:t3("En av de två sidorna vid den räta vinkeln.","One of the two sides next to the right angle.","أحد الضلعين المجاورين للزاوية القائمة."),ex:"3, 4, 5: kateterna 3 och 4",tr:{en:"leg",ar:"ضلع القائمة"}});
TERM("hypotenusa",{sv:"hypotenusa",m:new RegExp(B+"hypotenus(a|an|ans)"+E,"i"),d:t3("Längsta sidan, mitt emot den räta vinkeln.","The longest side, opposite the right angle.","أطول ضلع، مقابل الزاوية القائمة."),ex:"3, 4, 5: hypotenusan är 5",tr:{en:"hypotenuse",ar:"الوتر"}});
TERM("pythagoras",{sv:"Pythagoras sats",m:new RegExp(B+"pythagoras( sats)?"+E,"i"),d:t3("I en rätvinklig triangel är a² + b² = c².","In a right triangle, a² + b² = c².","في المثلث القائم: a² + b² = c²."),ex:"3² + 4² = 5²",tr:{en:"Pythagoras' theorem",ar:"مبرهنة فيثاغورس"}});
TERM("diagonal",{sv:"diagonal",m:new RegExp(B+"diagonal(en|er|erna)?"+E,"i"),d:t3("En sträcka från ett hörn till ett hörn som inte är granne.","A line from one corner to a corner that is not next to it.","قطعة من رأس إلى رأس غير مجاور له."),ex:"snett över, hörn till hörn",tr:{en:"diagonal",ar:"قطر المستطيل"}});
TERM("avgora",{sv:"avgör",m:new RegExp(B+"avgör(a|s)?"+E,"i"),d:t3("Bestäm om något stämmer, och visa varför.","Decide whether something is true, and show why.","قرّر هل الأمر صحيح، وبيّن السبب."),ex:"Avgör om hörnet är 90°",tr:{en:"decide",ar:"حدّد"}});
/* ---- vol8 ---- */
TERM("prisma",{sv:"prisma",m:new RegExp(B+"prism(a|an|or|orna|ats)"+E,"i"),d:t3("En kropp med två likadana basytor och raka sidor.","A solid with two equal bases and straight sides.","مجسّم له قاعدتان متطابقتان وأوجه جانبية مستقيمة."),ex:"V = B · h",tr:{en:"prism",ar:"منشور"}});
TERM("cylinder",{sv:"cylinder",m:new RegExp(B+"cylind(er|ern|rar|rarna)"+E,"i"),d:t3("En kropp med en cirkel som basyta, som en burk.","A solid with a circle as its base, like a can.","مجسّم قاعدته دائرة، مثل العلبة."),ex:"V = π · r² · h",tr:{en:"cylinder",ar:"أسطوانة"}});
TERM("basyta",{sv:"basyta",m:new RegExp(B+"basyt(a|an|or|orna|ans)"+E,"i"),d:t3("Ytan som kroppen står på, med arean B.","The face the solid stands on, with area B.","الوجه الذي يقف عليه المجسّم، ومساحته B."),ex:"B = 4 · 3 = 12 cm²",tr:{en:"base",ar:"القاعدة"}});
/* ---- sim8 ---- */
TERM("likformig",{sv:"likformig",m:new RegExp(B+"likformig(a|t|het|heten)?"+E,"i"),d:t3("Samma form och samma vinklar men olika storlek.","Same shape and same angles but a different size.","الشكل نفسه والزوايا نفسها لكن بحجم مختلف."),ex:"3-4-5 och 6-8-10",tr:{en:"similar",ar:"متشابه"}});
TERM("skalfaktor",{sv:"skalfaktor",m:new RegExp(B+"skalfaktor(n|er)?"+E,"i"),d:t3("Hur många gånger större alla sidor blir.","How many times bigger all the sides become.","كم مرة تكبر كل الأضلاع."),ex:"12 / 6 = 2: k = 2",tr:{en:"scale factor",ar:"معامل التشابه"}});
TERM("motsvarande",{sv:"motsvarande sidor",m:new RegExp(B+"(motsvarande|hör ihop)"+E,"i"),d:t3("Sidor på samma plats i två likformiga figurer.","Sides in the same place in two similar shapes.","أضلاع في الموضع نفسه في شكلين متشابهين."),ex:"6 cm och 12 cm hör ihop",tr:{en:"corresponding",ar:"متناظرة"}});
/* ---- poly8 ---- */
TERM("regelbunden",{sv:"regelbunden",m:new RegExp(B+"regelbund(en|na|et)"+E,"i"),d:t3("Alla sidor och alla vinklar är lika stora.","All sides and all angles are equal.","كل الأضلاع وكل الزوايا متساوية."),ex:"liksidig triangel, kvadrat",tr:{en:"regular",ar:"منتظم"}});
/* ---- lin8 ---- */
TERM("linjar",{sv:"linjär funktion",m:new RegExp(B+"linjär(a|t)?( funktion(en|er)?)?"+E,"i"),d:t3("En funktion vars graf är en rät linje: y = kx + m.","A function whose graph is a straight line: y = kx + m.","دالة تمثيلها البياني خط مستقيم: y = kx + m."),ex:"y = 2x + 1",tr:{en:"linear function",ar:"دالة خطية"}});
TERM("lutning",{sv:"lutning (k)",m:new RegExp(B+"(lutning(en)?|lutar)"+E,"i"),d:t3("Hur mycket y ändras när x ökar med 1.","How much y changes when x goes up by 1.","مقدار تغيّر y عندما تزيد x بمقدار 1."),ex:"y = 2x + 1: k = 2",tr:{en:"slope",ar:"الميل"}});
TERM("skar",{sv:"skär y-axeln (m)",m:new RegExp(B+"skär(er)?( linjen)? y-axeln"+E,"i"),d:t3("Där linjen korsar y-axeln, vid talet m.","Where the line crosses the y-axis, at the number m.","النقطة التي يقطع فيها المستقيم المحور y، عند العدد m."),ex:"y = 2x + 1: m = 1",tr:{en:"y-intercept",ar:"المقطع الصادي"}});
TERM("ratlinje",{sv:"rät linje",m:new RegExp(B+"rät(a|t)? linje(n|r|rna)?"+E,"i"),d:t3("En helt rak linje.","A completely straight line.","خط مستقيم تمامًا."),ex:"y = kx + m",tr:{en:"straight line",ar:"خط مستقيم"}});
TERM("fastavgift",{sv:"fast avgift",m:new RegExp(B+"fast(a)? avgift(en)?"+E,"i"),d:t3("En kostnad som är lika stor varje gång.","A cost that is the same every time.","تكلفة تبقى نفسها في كل مرة."),ex:"40 kr i månaden",tr:{en:"fixed fee",ar:"رسم ثابت"}});
/* ---- seq8 ---- */
TERM("formel",{sv:"formel",m:new RegExp(B+"(formel(n)?|formler(na)?)"+E,"i"),d:t3("En regel skriven med bokstäver och tal.","A rule written with letters and numbers.","قاعدة مكتوبة بحروف وأعداد."),ex:"aₙ = 3n + 1",tr:{en:"formula",ar:"صيغة"}});
TERM("nte",{sv:"tal nummer n (aₙ)",m:new RegExp("(n:te|aₙ|"+B+"tal nummer)"+E,"i"),d:t3("aₙ betyder tal nummer n i talföljden.","aₙ means term number n in the sequence.","aₙ تعني الحد رقم n في المتتالية."),ex:"4, 7, 10: a₃ = 10",tr:{en:"term n",ar:"الحد رقم n"}});
/* ---- spread8 ---- */
TERM("variationsbredd",{sv:"variationsbredd",m:new RegExp(B+"variationsbredd(en)?"+E,"i"),d:t3("Största värdet minus minsta värdet.","The largest value minus the smallest value.","أكبر قيمة ناقص أصغر قيمة."),ex:"20 − 4 = 16",tr:{en:"range of the data",ar:"المدى"}});
TERM("kvartil",{sv:"kvartil (nedre / övre)",m:new RegExp(B+"kvartil(en|er|erna)?"+E,"i"),d:t3("Mitten av den nedre eller den övre halvan av värdena.","The middle of the lower or the upper half of the values.","منتصف النصف الأدنى أو النصف الأعلى من القيم."),ex:"Q1 nedre, Q3 övre",tr:{en:"quartile",ar:"الربيع"}});
TERM("kvartilavstand",{sv:"kvartilavstånd",m:new RegExp(B+"kvartilavstånd(et)?"+E,"i"),d:t3("Övre kvartilen minus nedre kvartilen.","The upper quartile minus the lower quartile.","الربيع الأعلى ناقص الربيع الأدنى."),ex:"18 − 7 = 11",tr:{en:"interquartile range",ar:"المدى الربيعي"}});
TERM("ladagram",{sv:"lådagram",m:new RegExp(B+"lådagram(met|men)?"+E,"i"),d:t3("En bild med en låda som visar hur värdena är spridda.","A picture with a box that shows how the values are spread.","رسم فيه صندوق يبيّن كيف تتوزع القيم."),ex:"min, Q1, median, Q3, max",tr:{en:"box plot",ar:"مخطط صندوقي"}});
TERM("spridning",{sv:"spridning",m:new RegExp(B+"(spridning(en)?|utspridd(a)?)"+E,"i"),d:t3("Hur mycket värdena skiljer sig från varandra.","How much the values differ from each other.","مقدار اختلاف القيم بعضها عن بعض."),ex:"4, 12, 20: stor spridning",tr:{en:"spread",ar:"التشتت"}});
/* ---- tree8 ---- */
TERM("traddiagram",{sv:"träddiagram",m:new RegExp(B+"träddiagram(met|men)?"+E,"i"),d:t3("Ett diagram med en gren för varje möjligt utfall.","A diagram with a branch for each possible outcome.","مخطط فيه فرع لكل نتيجة ممكنة."),ex:"två straffar: 4 utfall",tr:{en:"tree diagram",ar:"مخطط شجري"}});
TERM("exakt",{sv:"exakt",m:new RegExp(B+"exakt"+E,"i"),d:t3("Precis så många, inte fler och inte färre.","Precisely that many, no more and no fewer.","هذا العدد تمامًا، لا أكثر ولا أقل."),ex:"exakt ett mål: 0,32",tr:{en:"exactly",ar:"بالضبط"}});
TERM("gren",{sv:"gren",m:new RegExp(B+"gren(en|ar|arna)"+E,"i"),d:t3("En linje i träddiagrammet med en sannolikhet.","A line in a tree diagram with a probability.","خط في المخطط الشجري عليه احتمال."),ex:"0,8 + 0,2 = 1",tr:{en:"branch",ar:"فرع"}});
/* ---- quad9 ---- */
TERM("kvadreringsregel",{sv:"kvadreringsreglerna",m:new RegExp(B+"kvadreringsreg(el|eln|ler|lerna)"+E,"i"),d:t3("Regler för (a + b)² och (a − b)² med termen 2ab.","Rules for (a + b)² and (a − b)² with the term 2ab.","قاعدتا (a + b)² و(a − b)² مع الحد 2ab."),ex:"(x + 3)² = x² + 6x + 9",tr:{en:"squaring rules",ar:"قاعدتا التربيع"}});
TERM("konjugatregel",{sv:"konjugatregeln",m:new RegExp(B+"konjugatreg(el|eln)"+E,"i"),d:t3("(a + b)(a − b) blir a² − b², för mittentermerna tar ut varandra.","(a + b)(a − b) is a² − b², as the middle terms cancel.","(a + b)(a − b) = a² − b² لأن الحدّين الأوسطين يلغيان بعضهما."),ex:"(x + 5)(x − 5) = x² − 25",tr:{en:"difference of two squares",ar:"الفرق بين مربعين"}});
TERM("utanraknare",{sv:"utan räknare",m:new RegExp(B+"utan (minir|r)äknare(n)?"+E,"i"),d:t3("Räkna i huvudet eller på papper, inte på räknaren.","Work it out in your head or on paper, not on a calculator.","احسب ذهنيًا أو على الورق، لا بالآلة الحاسبة."),ex:"21 · 19 = 400 − 1 = 399",tr:{en:"without a calculator",ar:"دون آلة حاسبة"}});
TERM("utveckla",{sv:"utveckla",m:new RegExp(B+"utveckla(r|s|t|d)?"+E,"i"),d:t3("Multiplicera bort parenteserna och skriv som en summa.","Multiply out the brackets and write it as a sum.","فكّ الأقواس بالضرب واكتب العبارة مجموعًا."),ex:"(x + 2)² = x² + 4x + 4",tr:{en:"expand",ar:"افكّ"}});
/* ---- qeq9 ---- */
TERM("andragrad",{sv:"andragradsekvation",m:new RegExp(B+"andragradsekvation(en|er|erna)?"+E,"i"),d:t3("En ekvation där x² är den högsta potensen av x.","An equation where x² is the highest power of x.","معادلة أعلى قوة فيها للمتغير هي x²."),ex:"x² + 6x − 16 = 0",tr:{en:"quadratic equation",ar:"معادلة تربيعية"}});
TERM("nollprodukt",{sv:"nollproduktmetoden",m:new RegExp(B+"nollprodukt(metoden|en)?"+E,"i"),d:t3("Är en produkt 0 måste någon av faktorerna vara 0.","If a product is 0, one of the factors must be 0.","إذا كان حاصل الضرب 0 فأحد العوامل يساوي 0."),ex:"(x − 3)(x + 5) = 0",tr:{en:"zero product rule",ar:"قاعدة حاصل الضرب الصفري"}});
TERM("pqformel",{sv:"pq-formeln",m:new RegExp(B+"pq-formel(n)?"+E,"i"),d:t3("En formel som löser x² + px + q = 0.","A formula that solves x² + px + q = 0.","صيغة تحلّ المعادلة x² + px + q = 0."),ex:"x = −p/2 ± √((p/2)² − q)",tr:{en:"pq formula",ar:"صيغة pq"}});
TERM("kvadkompl",{sv:"kvadratkomplettering",m:new RegExp(B+"kvadratkomplettering(en)?"+E,"i"),d:t3("Lägg till ett tal så att ena sidan blir en kvadrat.","Add a number so that one side becomes a square.","أضف عددًا ليصبح أحد الطرفين مربعًا كاملًا."),ex:"x² + 6x + 9 = (x + 3)²",tr:{en:"completing the square",ar:"إكمال المربع"}});
/* ---- formula9 ---- */
TERM("sattain",{sv:"sätta in",m:new RegExp(B+"sätt(a|er)? in"+E,"i"),d:t3("Byt ut bokstaven i formeln mot ett tal.","Replace the letter in the formula with a number.","ضع عددًا مكان الحرف في الصيغة."),ex:"P = 220 − a, a = 15",tr:{en:"substitute",ar:"عوّض"}});
TERM("losaut",{sv:"lösa ut",m:new RegExp(B+"(lös(a|er)? ut|står ensam(t)?)"+E,"i"),d:t3("Skriv om formeln så att en bokstav står ensam.","Rewrite the formula so that one letter is on its own.","أعد كتابة الصيغة ليصبح حرف واحد وحده."),ex:"s = v · t ger t = s / v",tr:{en:"rearrange",ar:"اجعل المتغير موضوع القانون"}});
/* ---- sys9 ---- */
TERM("ekvsystem",{sv:"ekvationssystem",m:new RegExp(B+"ekvationssystem(et|en)?"+E,"i"),d:t3("Två ekvationer som ska gälla samtidigt för samma x och y.","Two equations that must both be true for the same x and y.","معادلتان يجب أن تتحققا معًا لقيمتَي x وy نفسيهما."),ex:"y = 2x + 1 och x + y = 7",tr:{en:"system of equations",ar:"نظام معادلات"}});
TERM("skarningspunkt",{sv:"skärningspunkt",m:new RegExp(B+"(skärningspunkt(en|er)?|skär(er)? (linjerna )?varandra)"+E,"i"),d:t3("Punkten där två linjer korsar varandra.","The point where two lines cross.","النقطة التي يتقاطع فيها خطان."),ex:"(5, 300)",tr:{en:"point of intersection",ar:"نقطة التقاطع"}});
TERM("substitution",{sv:"substitutionsmetoden",m:new RegExp(B+"substitution(smetoden|en)?"+E,"i"),d:t3("Byt ut y i ena ekvationen mot uttrycket från den andra.","Replace y in one equation with the expression from the other.","ضع عبارة y من إحدى المعادلتين في الأخرى."),ex:"x + (2x + 1) = 7",tr:{en:"substitution",ar:"طريقة التعويض"}});
TERM("grafiskt",{sv:"grafiskt",m:new RegExp(B+"grafisk(t|a)?"+E,"i"),d:t3("Med en graf: rita linjerna och läs av.","With a graph: draw the lines and read off.","باستخدام الرسم البياني: ارسم الخطوط واقرأ القيم."),ex:"linjerna skär i (2, 5)",tr:{en:"graphically",ar:"بيانيًا"}});
TERM("funktion",{sv:"funktion",m:new RegExp(B+"funktion(en|er|erna)?"+E,"i"),d:t3("En regel som ger exakt ett y-värde för varje x.","A rule that gives exactly one y-value for each x.","قاعدة تعطي قيمة y واحدة لكل x."),ex:"y = 2x + 1",tr:{en:"function",ar:"دالة"}});
TERM("vardetabell",{sv:"värdetabell",m:new RegExp(B+"värdetabell(en|er)?"+E,"i"),d:t3("En tabell med x-värden och de y-värden de ger.","A table of x-values and the y-values they give.","جدول فيه قيم x وقيم y الناتجة عنها."),ex:"x: 1, 2, 3 → y: 2, 4, 6",tr:{en:"table of values",ar:"جدول القيم"}});
TERM("parabel",{sv:"parabel",m:new RegExp(B+"parabel(n|ler)?"+E,"i"),d:t3("Den böjda kurvan du får när du ritar y = x².","The curved graph you get when you draw y = x².","المنحنى الذي تحصل عليه عند رسم y = x²."),ex:"y = x²",tr:{en:"parabola",ar:"قطع مكافئ"}});
TERM("hyperbel",{sv:"hyperbel",m:new RegExp(B+"hyperbel(n|ler)?"+E,"i"),d:t3("Kurvan till y = k / x, som aldrig når axlarna.","The graph of y = k / x, which never reaches the axes.","منحنى y = k / x الذي لا يصل إلى المحورين أبدًا."),ex:"y = 24 / x",tr:{en:"hyperbola",ar:"قطع زائد"}});
TERM("omvprop",{sv:"omvänt proportionell",m:new RegExp(B+"(omvänt proportionell(a|t)?|omvänd proportionalitet(en)?)"+E,"i"),d:t3("Dubbelt så mycket av x ger hälften så mycket y.","Twice as much x gives half as much y.","مضاعفة x تجعل y نصف ما كانت."),ex:"x · y = 24",tr:{en:"inversely proportional",ar:"تناسب عكسي"}});
TERM("exponentiell",{sv:"exponentiell förändring",m:new RegExp(B+"exponentiell(a|t)?( förändring| ökning| tillväxt| minskning)?"+E,"i"),d:t3("Värdet gångras med samma faktor i varje steg.","The value is multiplied by the same factor at each step.","تُضرب القيمة في المعامل نفسه في كل خطوة."),ex:"y = C · aˣ",tr:{en:"exponential",ar:"أسّي"}});
TERM("halveringstid",{sv:"halveringstid",m:new RegExp(B+"halveringstid(en|er)?"+E,"i"),d:t3("Tiden det tar för en mängd att bli hälften så stor.","The time it takes for an amount to become half as big.","الزمن الذي تحتاجه كمية لتصبح نصف ما كانت."),ex:"160 mg → 80 mg",tr:{en:"half-life",ar:"عمر النصف"}});
TERM("moms",{sv:"moms",m:new RegExp(B+"moms(en)?"+E,"i"),d:t3("En skatt som läggs på priset när du köper något.","A tax added to the price when you buy something.","ضريبة تُضاف إلى السعر عند الشراء."),ex:"400 kr + 25 % = 500 kr",tr:{en:"VAT",ar:"ضريبة القيمة المضافة"}});
TERM("startvarde",{sv:"startvärde (C)",m:new RegExp(B+"startvärde(t|n)?"+E,"i"),d:t3("Värdet i början, innan någon förändring har skett.","The value at the start, before any change.","القيمة في البداية قبل أي تغيّر."),ex:"y = 500 · 2ˣ → C = 500",tr:{en:"starting value",ar:"القيمة الابتدائية"}});
TERM("kon",{sv:"kon",m:new RegExp(B+"kon(en|er|erna|ens)?"+E,"i"),d:t3("En kropp med rund botten som smalnar av till en spets.","A solid with a round base that narrows to a point.","مجسّم قاعدته دائرية ويضيق حتى رأس مدبّب."),ex:"V = π · r² · h / 3",tr:{en:"cone",ar:"مخروط"}});
TERM("pyramid",{sv:"pyramid",m:new RegExp(B+"pyramid(en|er|erna|ens)?"+E,"i"),d:t3("En kropp med månghörnig botten och sidor som möts i en spets.","A solid with a polygon base and sides that meet at a point.","مجسّم قاعدته مضلّع وأوجهه تلتقي في رأس."),ex:"V = B · h / 3",tr:{en:"pyramid",ar:"هرم"}});
TERM("klot",{sv:"klot",m:new RegExp(B+"klot(et|ets)?"+E,"i"),d:t3("En helt rund kropp, som en boll.","A completely round solid, like a ball.","مجسّم مستدير تمامًا مثل الكرة."),ex:"V = 4 · π · r³ / 3",tr:{en:"sphere",ar:"كرة"}});
TERM("begransningsarea",{sv:"begränsningsarea",m:new RegExp(B+"begränsningsarea(n)?"+E,"i"),d:t3("Summan av arean av alla ytor runt en kropp.","The total area of all the faces around a solid.","مجموع مساحات كل الأوجه حول المجسّم."),ex:"6 rektanglar",tr:{en:"surface area",ar:"المساحة الكلية"}});
TERM("mantelyta",{sv:"mantelyta",m:new RegExp(B+"mantelyta(n)?"+E,"i"),d:t3("Den böjda sidan på en cylinder, en rektangel när den rullas ut.","The curved side of a cylinder, a rectangle when unrolled.","الجانب المنحني للأسطوانة، ويصير مستطيلًا إذا فُرد."),ex:"π · d · h",tr:{en:"curved surface",ar:"المساحة الجانبية"}});
TERM("langdskala",{sv:"längdskala",m:new RegExp(B+"längdskala(n)?"+E,"i"),d:t3("Hur många gånger längre allt är i den stora figuren.","How many times longer everything is in the big figure.","كم مرة تكون الأطوال أكبر في الشكل الكبير."),ex:"k = 12 / 6 = 2",tr:{en:"length scale",ar:"مقياس الطول"}});
TERM("areaskala",{sv:"areaskala",m:new RegExp(B+"areaskala(n)?"+E,"i"),d:t3("Hur många gånger större arean blir, alltså k².","How many times bigger the area gets, that is k².","كم مرة تكبر المساحة، أي k²."),ex:"k = 2 → 2² = 4",tr:{en:"area scale",ar:"مقياس المساحة"}});
TERM("volymskala",{sv:"volymskala",m:new RegExp(B+"volymskala(n)?"+E,"i"),d:t3("Hur många gånger större volymen blir, alltså k³.","How many times bigger the volume gets, that is k³.","كم مرة يكبر الحجم، أي k³."),ex:"k = 2 → 2³ = 8",tr:{en:"volume scale",ar:"مقياس الحجم"}});
TERM("kombination",{sv:"kombination",m:new RegExp(B+"kombination(en|er|erna)?"+E,"i"),d:t3("Ett sätt att välja saker tillsammans, till exempel tröja och byxor.","One way to choose things together, like a top and trousers.","طريقة لاختيار أشياء معًا، مثل قميص وبنطال."),ex:"3 · 2 = 6",tr:{en:"combination",ar:"تشكيلة"}});
TERM("multprincip",{sv:"multiplikationsprincipen",m:new RegExp(B+"multiplikationsprincip(en)?"+E,"i"),d:t3("Antalet sätt är antalet val i varje steg gånger varandra.","The number of ways is the choices at each step multiplied.","عدد الطرق هو حاصل ضرب عدد الخيارات في كل خطوة."),ex:"3 · 2 · 2 = 12",tr:{en:"multiplication principle",ar:"مبدأ الضرب"}});
TERM("fakultet",{sv:"fakultet (n!)",m:new RegExp(B+"fakultet(en)?"+E,"i"),d:t3("Alla heltal från n ner till 1 gånger varandra.","All whole numbers from n down to 1 multiplied.","ضرب كل الأعداد الصحيحة من n نزولًا إلى 1."),ex:"4! = 4 · 3 · 2 · 1",tr:{en:"factorial",ar:"مضروب"}});
TERM("aterlaggning",{sv:"återläggning",m:new RegExp(B+"(återläggning(en)?|lägg(a|er)? tillbaka|läggs tillbaka)"+E,"i"),d:t3("Det du tar läggs tillbaka innan du tar nästa.","What you take is put back before you take the next.","ما تأخذه تعيده قبل أن تأخذ التالي."),ex:"3/5 · 3/5",tr:{en:"replacement",ar:"الإرجاع"}});
TERM("urval",{sv:"urval",m:new RegExp(B+"urval(et|en)?"+E,"i"),d:t3("De personer du väljer ut att fråga.","The people you pick out to ask.","الأشخاص الذين تختارهم لتسألهم."),ex:"50 av 600 elever",tr:{en:"sample",ar:"عيّنة"}});
TERM("slumpvis",{sv:"slumpvis / slumpmässigt",m:new RegExp(B+"(slumpvis|slumpmässig(t|a)?)"+E,"i"),d:t3("Alla har samma chans att bli valda.","Everyone has the same chance of being chosen.","لكل واحد الفرصة نفسها في أن يُختار."),ex:"dra lott",tr:{en:"randomly",ar:"عشوائيًا"}});
TERM("samband",{sv:"samband",m:new RegExp(B+"samband(et|en)?"+E,"i"),d:t3("Två saker ändras ihop, men den ena behöver inte orsaka den andra.","Two things change together, but one need not cause the other.","شيئان يتغيّران معًا، ولا يعني ذلك أن أحدهما سبب الآخر."),ex:"samband ≠ orsak",tr:{en:"connection",ar:"علاقة"}});
TERM("missvisande",{sv:"missvisande",m:new RegExp(B+"missvisande"+E,"i"),d:t3("Ger en felaktig bild, fast siffrorna kan vara rätt.","Gives a wrong picture, even if the numbers are right.","يعطي صورة خاطئة حتى لو كانت الأرقام صحيحة."),ex:"y-axeln börjar på 92",tr:{en:"misleading",ar:"مضلِّل"}});
TERM("slumptal",{sv:"slumptal",m:new RegExp(B+"(slumptal(et|en)?|random)"+E,"i"),d:t3("Ett tal som datorn väljer på måfå.","A number the computer picks by chance.","عدد يختاره الحاسوب عشوائيًا."),ex:"randint(1, 6)",tr:{en:"random number",ar:"عدد عشوائي"}});
WORDS.pow8=["potens","bas","exponent","faktor","produkt","forenkla","berakna","bestam"];
WORDS.root8=["kvadrattal","kvadratrot","kvadrera","heltal","avrunda","area","omkrets","berakna"];
WORDS.sci8=["grundpotensform","tiopotens","exponent","prefix","mikro","decimal","bestam"];
WORDS.speed8=["hastighet","medelhastighet","stracka","kmh","omvandla","berakna"];
WORDS.pct8=["forandringsfaktor","procent","procentenhet","okning","minskning","andel","decimal","berakna","bestam"];
WORDS.interest8=["ranta","rantesats","rantaparanta","lan","belopp","avbetalning","forandringsfaktor","berakna"];
WORDS.paren8=["parentes","multin","brytut","faktorisera","term","uttryck","gemfaktor","forenkla"];
WORDS.eq8=["ekvation","losa","parentes","namnare","mgn","stallaupp","bestam","berakna"];
WORDS.pyth8=["katet","hypotenusa","pythagoras","ratvinkel","kvadratrot","avrunda","tiondel","diagonal","avgora"];
WORDS.vol8=["volym","prisma","cylinder","basyta","rymma","liter","radie","avrunda","berakna"];
WORDS.sim8=["likformig","skalfaktor","motsvarande","forstoring","avgora","berakna","bestam"];
WORDS.poly8=["vinkelsumma","manghorning","regelbunden","horn","diagonal","vinkel","bestam","berakna"];
WORDS.lin8=["linjar","lutning","skar","ratlinje","koordinatsystem","fastavgift","bestam","berakna"];
WORDS.seq8=["talfoljd","formel","nte","okar","ekvation","stallaupp","bestam"];
WORDS.spread8=["variationsbredd","median","kvartil","kvartilavstand","ladagram","spridning","ungefar","bestam"];
WORDS.quad9=["kvadreringsregel","konjugatregel","utveckla","uttryck","term","forenkla","utanraknare","parentes"];
WORDS.qeq9=["andragrad","nollprodukt","pqformel","kvadkompl","kvadratrot","losa","ekvation","bestam"];
WORDS.formula9=["formel","sattain","losaut","variabel","berakna","bestam"];
WORDS.sys9=["ekvsystem","skarningspunkt","substitution","grafiskt","ekvation","losa","bestam"];
WORDS.line9=["linjar","lutning","skar","ratlinje","ekvation","bestam","avgora"];
WORDS.nonlin9=["funktion","vardetabell","parabel","hyperbel","omvprop","area","berakna","bestam"];
WORDS.exp9=["exponentiell","forandringsfaktor","startvarde","halveringstid","linjar","procent","avgora"];
WORDS.pct9=["forandringsfaktor","procent","moms","rabatt","berakna"];
WORDS.cone9=["kon","pyramid","klot","volym","radie","diameter","avrunda","liter"];
WORDS.surf9=["begransningsarea","mantelyta","ratblock","cylinder","area","radie","avrunda","berakna"];
WORDS.scale9=["likformig","langdskala","areaskala","volymskala","area","volym","bestam"];
WORDS.pythapp9=["pythagoras","hypotenusa","katet","diagonal","ratvinkel","avstand","avrunda","avgora"];
WORDS.comb9=["kombination","multprincip","fakultet","traddiagram","berakna"];
WORDS.prob9=["sannolikhet","aterlaggning","traddiagram","minst","utfall","namnare"];
WORDS.crit9=["missvisande","urval","slumpvis","samband","procent","avgora"];
WORDS.prog9=["program","funktion","loop","villkor","slumptal","variabel","bestam"];
WORDS.tree8=["sannolikhet","traddiagram","gren","utfall","exakt","minst","berakna"];
}
