// Keeps the module wiring right: each lesson file imports exactly the engine names it uses,
// and core.js / sv-0engine.js export every top-level name. Run by build.sh; safe to run any time.
// usage: node tools/fix-imports.mjs
import {Linter} from "eslint";import fs from "fs";import path from "path";
const ENGINES=["app/src/legacy/core.js","app/src/lessons/sv-0engine.js"];
const files=["app/src/legacy/core.js",...fs.readdirSync("app/src/lessons").filter(f=>f.endsWith(".js")).sort().map(f=>"app/src/lessons/"+f)];
const GEN=/^import \{[^}]*\} from "\.{1,2}\/[^"]*(core|sv-0engine)\.js";\n/mg,EXP=/\nexport \{[^}]*\};\n*$/;
const body=f=>fs.readFileSync(f,"utf8").replace(GEN,"").replace(EXP,"\n");
function scan(src){const res={defs:[],uses:new Set()};const l=new Linter({configType:"flat"});
  const m=l.verify(src,[{languageOptions:{ecmaVersion:"latest",sourceType:"module"},plugins:{x:{rules:{r:{create(ctx){return{"Program:exit"(){const ms=ctx.sourceCode.scopeManager.globalScope.childScopes[0];
    res.defs=ms.variables.filter(v=>v.defs.every(d=>d.type!=="ImportBinding")).map(v=>v.name);for(const r of ms.through)res.uses.add(r.identifier.name)}}}}}}},rules:{"x/r":"error"}}]);
  const bad=m.filter(x=>x.fatal);if(bad.length)throw new Error(bad.map(b=>b.message+" line "+b.line).join("; "));return res}
const info={};for(const f of files){try{info[f]=scan(body(f))}catch(e){console.error(f+": "+e.message);process.exit(1)}}
const owner={};for(const f of ENGINES)for(const d of info[f].defs)owner[d]=f;
for(const f of files){const imp={};for(const n of info[f].uses){const o=owner[n];if(o&&o!==f)(imp[o]=imp[o]||[]).push(n)}
  let head="";for(const [o,ns] of Object.entries(imp).sort()){let rel=path.relative(path.dirname(f),o);if(!rel.startsWith("."))rel="./"+rel;head+=`import {${ns.sort().join(",")}} from "${rel}";\n`}
  const exp=ENGINES.includes(f)?`\nexport {${info[f].defs.filter(d=>d!=="start").join(",")}};\n`:"";
  /* loose types for the TypeScript screens until the engine itself is typed */
  if(ENGINES.includes(f)){const dts="// generated by tools/fix-imports.mjs\n"+info[f].defs.map(d=>`export declare const ${d}: any;`).join("\n")+"\n";const df=f.replace(/\.js$/,".d.ts");if(!fs.existsSync(df)||fs.readFileSync(df,"utf8")!==dts)fs.writeFileSync(df,dts)}
  const out=head+body(f).replace(/\n+$/,"\n")+exp;if(out!==fs.readFileSync(f,"utf8"))fs.writeFileSync(f,out)}
