#!/usr/bin/env python3
"""Make the Year 1 voice clips with Piper (Swedish voice sv_SE-nst-medium) and write app/src/little/clips.ts.
Usage: python3 tools/make-voice-piper.py path/to/sv_SE-nst-medium.onnx   (the .onnx.json must sit next to it)
Needs: pip install piper-tts; ffmpeg optional (mp3, smaller), else wav."""
import base64, io, json, re, shutil, subprocess, sys, wave
from piper import PiperVoice

voice = PiperVoice.load(sys.argv[1])
src = open("app/src/little/voice.ts", encoding="utf8").read()
letters = re.findall(r'"?([A-ZÅÄÖ])"?: \["([^"]+)"', src)
nums = ["noll", "ett", "två", "tre", "fyra", "fem", "sex", "sju", "åtta", "nio", "tio"]
# how a letter's name sounds when read alone
NAME = {"A": "a", "B": "be", "C": "se", "D": "de", "E": "e", "F": "eff", "G": "ge", "H": "hå", "I": "i", "J": "ji", "K": "kå",
        "L": "ell", "M": "emm", "N": "enn", "O": "o", "P": "pe", "Q": "ku", "R": "ärr", "S": "ess", "T": "te", "U": "u",
        "V": "ve", "W": "dubbelve", "X": "eks", "Y": "y", "Z": "säta", "Å": "å", "Ä": "ä", "Ö": "ö"}

def clip(text):
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        voice.synthesize_wav(text, w) if hasattr(voice, "synthesize_wav") else voice.synthesize(text, w)
    raw = buf.getvalue()
    if shutil.which("ffmpeg"):
        mp3 = subprocess.run(["ffmpeg", "-loglevel", "error", "-i", "-", "-ac", "1", "-b:a", "40k", "-f", "mp3", "-"],
                             input=raw, capture_output=True, check=True).stdout
        return "data:audio/mpeg;base64," + base64.b64encode(mp3).decode()
    return "data:audio/wav;base64," + base64.b64encode(raw).decode()

clips = {}
for ch, word in letters:
    clips["L:" + ch] = clip(NAME.get(ch, ch.lower()) + ".")
    clips["W:" + word] = clip(word + ".")
for i, n in enumerate(nums):
    clips[f"N:{i}"] = clip(n + ".")
with open("app/src/little/clips.ts", "w", encoding="utf8") as f:
    f.write('/* Generated by tools/make-voice-piper.py: short Swedish clips as data URIs, keyed "L:A", "W:apa", "N:3". */\n')
    f.write("export const CLIPS: Record<string, string> = " + json.dumps(clips, ensure_ascii=False, indent=0) + ";\n")
print(len(clips), "clips,", sum(map(len, clips.values())) // 1024, "KB")
