#!/usr/bin/env python3
"""Make the Year 1 voice clips with Piper (Swedish voice sv_SE-nst-medium) and write app/src/little/clips.ts.
Usage: python3 tools/make-voice-piper.py path/to/sv_SE-nst-medium.onnx   (uses the .onnx.json next to it, else the standard config)
Needs: pip install piper-tts; ffmpeg optional (mp3, smaller), else wav."""
import base64, io, json, os, re, shutil, subprocess, sys, tempfile, wave
from piper import PiperVoice
from piper.phoneme_ids import DEFAULT_PHONEME_ID_MAP

model = sys.argv[1]
cfg = model + ".json"
if not os.path.exists(cfg):  # the standard config of Piper's espeak voices (sv_SE-nst-medium: 22 050 Hz, one speaker)
    cfg = os.path.join(tempfile.mkdtemp(), "sv.json")
    json.dump({"audio": {"sample_rate": 22050}, "espeak": {"voice": "sv"}, "phoneme_type": "espeak", "num_symbols": 256,
               "num_speakers": 1, "inference": {"noise_scale": 0.667, "length_scale": 1, "noise_w": 0.8},
               "phoneme_id_map": DEFAULT_PHONEME_ID_MAP}, open(cfg, "w"))
voice = PiperVoice.load(model, config_path=cfg)
from piper import SynthesisConfig
SLOW = SynthesisConfig(length_scale=1.25)  # a little slower and clearer for children
src = open("app/src/little/voice.ts", encoding="utf8").read()
letters = re.findall(r'"?([A-ZÅÄÖ])"?: \["([^"]+)"', src)
nums = ["noll", "ett", "två", "tre", "fyra", "fem", "sex", "sju", "åtta", "nio", "tio"]
# how a letter's name sounds when read alone
NAME = {"A": "a", "B": "be", "C": "se", "D": "de", "E": "e", "F": "eff", "G": "ge", "H": "hå", "I": "i", "J": "ji", "K": "kå",
        "L": "ell", "M": "emm", "N": "enn", "O": "o", "P": "pe", "Q": "ku", "R": "ärr", "S": "ess", "T": "te", "U": "u",
        "V": "ve", "W": "dubbelve", "X": "eks", "Y": "y", "Z": "säta", "Å": "å", "Ä": "ä", "Ö": "ö"}

def clip(text):
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        voice.synthesize_wav(text, w, syn_config=SLOW)
    raw = buf.getvalue()
    if shutil.which("ffmpeg"):
        mp3 = subprocess.run(["ffmpeg", "-loglevel", "error", "-i", "-", "-ac", "1", "-b:a", "40k", "-f", "mp3", "-"],
                             input=raw, capture_output=True, check=True).stdout
        return "data:audio/mpeg;base64," + base64.b64encode(mp3).decode()
    return "data:audio/wav;base64," + base64.b64encode(raw).decode()

clips = {}
for ch, word in letters:
    clips["L:" + ch] = clip(NAME.get(ch, ch.lower()) + ".")
    clips["W:" + word] = clip(word + ".")
for i, n in enumerate(nums):
    clips[f"N:{i}"] = clip(n + ".")
with open("app/src/little/clips.ts", "w", encoding="utf8") as f:
    f.write('/* Generated by tools/make-voice-piper.py: short Swedish clips as data URIs, keyed "L:A", "W:apa", "N:3". */\n')
    f.write("export const CLIPS: Record<string, string> = " + json.dumps(clips, ensure_ascii=False, indent=0) + ";\n")
print(len(clips), "clips,", sum(map(len, clips.values())) // 1024, "KB")
