#!/usr/bin/env python3
"""Make the Year 1 voice clips with Amazon Polly (Swedish neural voice "Elin") and write
app/src/little/clips.ts. Needs real AWS credentials in the environment (polly:SynthesizeSpeech).
Run once: python3 tools/make-voice.py   (pip install boto3 first)"""
import base64, json, re, boto3

src = open("app/src/little/voice.ts", encoding="utf8").read()
letters = re.findall(r'"?([A-ZÅÄÖ])"?: \["([^"]+)"', src)
nums = ["noll", "ett", "två", "tre", "fyra", "fem", "sex", "sju", "åtta", "nio", "tio"]

polly = boto3.client("polly", region_name="eu-north-1")
def mp3(ssml):
    r = polly.synthesize_speech(Engine="neural", VoiceId="Elin", LanguageCode="sv-SE", OutputFormat="mp3",
                                SampleRate="22050", TextType="ssml", Text=f"<speak>{ssml}</speak>")
    return "data:audio/mpeg;base64," + base64.b64encode(r["AudioStream"].read()).decode()

clips = {}
for ch, word in letters:
    clips["L:" + ch] = mp3(f'<prosody rate="85%"><say-as interpret-as="characters">{ch}</say-as></prosody>')
    clips["W:" + word] = mp3(f'<prosody rate="85%">{word}</prosody>')
for i, n in enumerate(nums):
    clips[f"N:{i}"] = mp3(f'<prosody rate="85%">{n}</prosody>')

with open("app/src/little/clips.ts", "w", encoding="utf8") as f:
    f.write('/* Generated by tools/make-voice.py: short Swedish clips as data URIs, keyed "L:A", "W:apa", "N:3". */\n')
    f.write("export const CLIPS: Record<string, string> = " + json.dumps(clips, ensure_ascii=False, indent=0) + ";\n")
print(len(clips), "clips,", sum(map(len, clips.values())) // 1024, "KB")
